name: sj_presensi_mobile
description: My Success Apps.
publish_to: 'none'
version: 3.2.0

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  bloc: ^8.1.1
  cached_network_image: ^3.2.3
  camera: ^0.10.5+5
  change_app_package_name: ^1.1.0
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_datetime_picker: ^1.5.1
  flutter_image_compress: ^2.0.4
  flutter_launcher_icons: ^0.13.1
  font_awesome_flutter: ^10.5.0
  datepicker_dropdown: ^0.0.8
  flutter_svg: ^2.0.7
  form_field_validator: ^1.1.0
  freezed_annotation: ^2.1.0
  geocoding: ^2.0.5
  geolocator: ^10.1.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  month_picker_dialog: ^2.0.2
  google_fonts: ^6.1.0
  url_launcher: ^6.2.1
  http: ^1.1.0
  easy_stepper: ^0.8.2
  # image_picker:
  #   git:
  #     url: https://github.com/Gusrinda/image_picker_custom
  intl: ^0.18.1
  lottie: ^2.2.0
  shared_preferences: ^2.0.18
  flutter_screenutil: ^5.9.0
  file_picker: ^6.1.1
  flutter_pdfview: ^1.3.2

dev_dependencies:
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter_icons:
  android: "ic_sj_logo"
  ios: true
  image_path: "assets/images/logo_SJ.png"

flutter:
  uses-material-design: true
  assets:
  - assets/lotties/gif/
  - assets/lotties/json/
  - assets/images/
  - assets/icons/

fonts:
  - family: Poppins
    fonts:
    - asset: fonts/Poppins-Thin.ttf
      weight: 100
    - asset: fonts/Poppins-ExtraLight.ttf
      weight: 200
    - asset: fonts/Poppins-Light.ttf
      weight: 300
    - asset: fonts/Poppins-Regular.ttf
      weight: 400
    - asset: fonts/Poppins-Medium.ttf
      weight: 500
    - asset: fonts/Poppins-SemiBold.ttf
      weight: 600
    - asset: fonts/Poppins-Bold.ttf
      weight: 700
    - asset: fonts/Poppins-ExtraBold.ttf
      weight: 800
    - asset: fonts/Poppins-Black.ttf
      weight: 900
