name: ql_absensi_express_mobile
description: QL Absensi Express Apps.
publish_to: 'none'
version: 2.0.0+16

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.18
  http: ^1.1.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  flutter_svg: ^2.0.7
  form_field_validator: ^1.1.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.0
  month_picker_dialog: ^2.0.2
  intl: ^0.18.1
  lottie: ^2.2.0
  equatable: ^2.0.5
  cached_network_image: ^3.2.3
  geolocator: ^10.1.0
  geocoding: ^2.0.5
  flutter_launcher_icons: ^0.13.1
  connectivity_plus: ^4.0.2
  flutter_image_compress: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "ic_ql_logo"
  ios: true
  image_path: "assets/images/logo_ql.png"

flutter:
  uses-material-design: true
  assets:
  - assets/lotties/gif/
  - assets/lotties/json/
  - assets/images/
  - assets/icons/




























