import 'package:freezed_annotation/freezed_annotation.dart';
import 'dart:convert';

part 'list_cuti_model.freezed.dart';
part 'list_cuti_model.g.dart';

@freezed
class ListCutiModel with _$ListCutiModel {
    const factory ListCutiModel({
        @JsonKey(name: "data")
        List<Datum>? data,
        @JsonKey(name: "total")
        int? total,
        @JsonKey(name: "current_page")
        int? currentPage,
        @JsonKey(name: "per_page")
        int? perPage,
        @JsonKey(name: "from")
        int? from,
        @JsonKey(name: "to")
        int? to,
        @JsonKey(name: "last_page")
        int? lastPage,
        @JsonKey(name: "has_next")
        bool? hasNext,
        @JsonKey(name: "prev")
        dynamic prev,
        @JsonKey(name: "next")
        dynamic next,
        @JsonKey(name: "processed_time")
        double? processedTime,
    }) = _ListCutiModel;

    factory ListCutiModel.fromJson(Map<String, dynamic> json) => _$ListCutiModelFromJson(json);
}

@freezed
class Datum with _$Datum {
    const factory Datum({
        @JsonKey(name: "meta_read")
        bool? metaRead,
        @JsonKey(name: "meta_delete")
        bool? metaDelete,
        @JsonKey(name: "meta_update")
        bool? metaUpdate,
        @JsonKey(name: "meta_create")
        bool? metaCreate,
        @JsonKey(name: "id")
        int? id,
        @JsonKey(name: "nomor")
        String? nomor,
        @JsonKey(name: "m_comp_id")
        int? datumMCompId,
        @JsonKey(name: "m_dir_id")
        int? datumMDirId,
        @JsonKey(name: "m_kary_id")
        dynamic datumMKaryId,
        @JsonKey(name: "alasan_id")
        int? datumAlasanId,
        @JsonKey(name: "tipe_cuti_id")
        int? datumTipeCutiId,
        @JsonKey(name: "date_from")
        String? dateFrom,
        @JsonKey(name: "date_to")
        String? dateTo,
        @JsonKey(name: "time_from")
        String? timeFrom,
        @JsonKey(name: "time_to")
        String? timeTo,
        @JsonKey(name: "keterangan")
        String? keterangan,
        @JsonKey(name: "status")
        String? status,
        @JsonKey(name: "creator_id")
        int? datumCreatorId,
        @JsonKey(name: "last_editor_id")
        dynamic datumLastEditorId,
        @JsonKey(name: "created_at")
        String? createdAt,
        @JsonKey(name: "updated_at")
        String? updatedAt,
        @JsonKey(name: "m_comp.id")
        int? mCompId,
        @JsonKey(name: "m_comp.nama")
        String? mCompNama,
        @JsonKey(name: "m_comp.is_active")
        bool? mCompIsActive,
        @JsonKey(name: "m_comp.desc")
        dynamic mCompDesc,
        @JsonKey(name: "m_comp.creator_id")
        dynamic mCompCreatorId,
        @JsonKey(name: "m_comp.last_editor_id")
        dynamic mCompLastEditorId,
        @JsonKey(name: "m_comp.created_at")
        dynamic mCompCreatedAt,
        @JsonKey(name: "m_comp.updated_at")
        dynamic mCompUpdatedAt,
        @JsonKey(name: "m_dir.id")
        int? mDirId,
        @JsonKey(name: "m_dir.m_comp_id")
        int? mDirMCompId,
        @JsonKey(name: "m_dir.nama")
        String? mDirNama,
        @JsonKey(name: "m_dir.desc")
        dynamic mDirDesc,
        @JsonKey(name: "m_dir.is_active")
        bool? mDirIsActive,
        @JsonKey(name: "m_dir.creator_id")
        dynamic mDirCreatorId,
        @JsonKey(name: "m_dir.last_editor_id")
        dynamic mDirLastEditorId,
        @JsonKey(name: "m_dir.created_at")
        dynamic mDirCreatedAt,
        @JsonKey(name: "m_dir.updated_at")
        dynamic mDirUpdatedAt,
        @JsonKey(name: "m_kary.id")
        dynamic mKaryId,
        @JsonKey(name: "m_kary.m_comp_id")
        dynamic mKaryMCompId,
        @JsonKey(name: "m_kary.m_dir_id")
        dynamic mKaryMDirId,
        @JsonKey(name: "m_kary.m_divisi_id")
        dynamic mKaryMDivisiId,
        @JsonKey(name: "m_kary.m_dept_id")
        dynamic mKaryMDeptId,
        @JsonKey(name: "m_kary.m_zona_id")
        dynamic mKaryMZonaId,
        @JsonKey(name: "m_kary.grading_id")
        dynamic mKaryGradingId,
        @JsonKey(name: "m_kary.costcontre_id")
        dynamic mKaryCostcontreId,
        @JsonKey(name: "m_kary.kode")
        dynamic mKaryKode,
        @JsonKey(name: "m_kary.m_posisi_id")
        dynamic mKaryMPosisiId,
        @JsonKey(name: "m_kary.m_jam_kerja_id")
        dynamic mKaryMJamKerjaId,
        @JsonKey(name: "m_kary.kode_presensi")
        dynamic mKaryKodePresensi,
        @JsonKey(name: "m_kary.nik")
        dynamic mKaryNik,
        @JsonKey(name: "m_kary.nama_depan")
        dynamic mKaryNamaDepan,
        @JsonKey(name: "m_kary.nama_belakang")
        dynamic mKaryNamaBelakang,
        @JsonKey(name: "m_kary.nama_lengkap")
        dynamic mKaryNamaLengkap,
        @JsonKey(name: "m_kary.nama_panggilan")
        dynamic mKaryNamaPanggilan,
        @JsonKey(name: "m_kary.jk_id")
        dynamic mKaryJkId,
        @JsonKey(name: "m_kary.tempat_lahir")
        dynamic mKaryTempatLahir,
        @JsonKey(name: "m_kary.tgl_lahir")
        dynamic mKaryTglLahir,
        @JsonKey(name: "m_kary.provinsi_id")
        dynamic mKaryProvinsiId,
        @JsonKey(name: "m_kary.kota_id")
        dynamic mKaryKotaId,
        @JsonKey(name: "m_kary.kecamatan_id")
        dynamic mKaryKecamatanId,
        @JsonKey(name: "m_kary.kode_pos")
        dynamic mKaryKodePos,
        @JsonKey(name: "m_kary.alamat_asli")
        dynamic mKaryAlamatAsli,
        @JsonKey(name: "m_kary.alamat_domisili")
        dynamic mKaryAlamatDomisili,
        @JsonKey(name: "m_kary.no_tlp")
        dynamic mKaryNoTlp,
        @JsonKey(name: "m_kary.no_tlp_lainnya")
        dynamic mKaryNoTlpLainnya,
        @JsonKey(name: "m_kary.no_darurat")
        dynamic mKaryNoDarurat,
        @JsonKey(name: "m_kary.nama_kontak_darurat")
        dynamic mKaryNamaKontakDarurat,
        @JsonKey(name: "m_kary.agama_id")
        dynamic mKaryAgamaId,
        @JsonKey(name: "m_kary.gol_darah_id")
        dynamic mKaryGolDarahId,
        @JsonKey(name: "m_kary.status_nikah_id")
        dynamic mKaryStatusNikahId,
        @JsonKey(name: "m_kary.jml_tanggungan")
        dynamic mKaryJmlTanggungan,
        @JsonKey(name: "m_kary.hub_dgn_karyawan")
        dynamic mKaryHubDgnKaryawan,
        @JsonKey(name: "m_kary.cuti_jatah_reguler")
        dynamic mKaryCutiJatahReguler,
        @JsonKey(name: "m_kary.cuti_sisa_reguler")
        dynamic mKaryCutiSisaReguler,
        @JsonKey(name: "m_kary.cuti_panjang")
        dynamic mKaryCutiPanjang,
        @JsonKey(name: "m_kary.cuti_sisa_panjang")
        dynamic mKaryCutiSisaPanjang,
        @JsonKey(name: "m_kary.status_kary_id")
        dynamic mKaryStatusKaryId,
        @JsonKey(name: "m_kary.lama_kontrak_awal")
        dynamic mKaryLamaKontrakAwal,
        @JsonKey(name: "m_kary.lama_kontrak_akhir")
        dynamic mKaryLamaKontrakAkhir,
        @JsonKey(name: "m_kary.tgl_masuk")
        dynamic mKaryTglMasuk,
        @JsonKey(name: "m_kary.tgl_berhenti")
        dynamic mKaryTglBerhenti,
        @JsonKey(name: "m_kary.alasan_berhenti")
        dynamic mKaryAlasanBerhenti,
        @JsonKey(name: "m_kary.uk_baju")
        dynamic mKaryUkBaju,
        @JsonKey(name: "m_kary.uk_celana")
        dynamic mKaryUkCelana,
        @JsonKey(name: "m_kary.uk_sepatu")
        dynamic mKaryUkSepatu,
        @JsonKey(name: "m_kary.desc")
        dynamic mKaryDesc,
        @JsonKey(name: "m_kary.is_active")
        dynamic mKaryIsActive,
        @JsonKey(name: "m_kary.creator_id")
        dynamic mKaryCreatorId,
        @JsonKey(name: "m_kary.last_editor_id")
        dynamic mKaryLastEditorId,
        @JsonKey(name: "m_kary.created_at")
        dynamic mKaryCreatedAt,
        @JsonKey(name: "m_kary.updated_at")
        dynamic mKaryUpdatedAt,
        @JsonKey(name: "alasan.id")
        int? alasanId,
        @JsonKey(name: "alasan.m_comp_id")
        int? alasanMCompId,
        @JsonKey(name: "alasan.m_dir_id")
        dynamic alasanMDirId,
        @JsonKey(name: "alasan.group")
        String? alasanGroup,
        @JsonKey(name: "alasan.key")
        String? alasanKey,
        @JsonKey(name: "alasan.code")
        String? alasanCode,
        @JsonKey(name: "alasan.value")
        String? alasanValue,
        @JsonKey(name: "alasan.is_active")
        bool? alasanIsActive,
        @JsonKey(name: "alasan.creator_id")
        dynamic alasanCreatorId,
        @JsonKey(name: "alasan.last_editor_id")
        dynamic alasanLastEditorId,
        @JsonKey(name: "alasan.created_at")
        String? alasanCreatedAt,
        @JsonKey(name: "alasan.updated_at")
        String? alasanUpdatedAt,
        @JsonKey(name: "tipe_cuti.id")
        int? tipeCutiId,
        @JsonKey(name: "tipe_cuti.m_comp_id")
        int? tipeCutiMCompId,
        @JsonKey(name: "tipe_cuti.m_dir_id")
        dynamic tipeCutiMDirId,
        @JsonKey(name: "tipe_cuti.group")
        String? tipeCutiGroup,
        @JsonKey(name: "tipe_cuti.key")
        String? tipeCutiKey,
        @JsonKey(name: "tipe_cuti.code")
        String? tipeCutiCode,
        @JsonKey(name: "tipe_cuti.value")
        String? tipeCutiValue,
        @JsonKey(name: "tipe_cuti.is_active")
        bool? tipeCutiIsActive,
        @JsonKey(name: "tipe_cuti.creator_id")
        dynamic tipeCutiCreatorId,
        @JsonKey(name: "tipe_cuti.last_editor_id")
        dynamic tipeCutiLastEditorId,
        @JsonKey(name: "tipe_cuti.created_at")
        String? tipeCutiCreatedAt,
        @JsonKey(name: "tipe_cuti.updated_at")
        String? tipeCutiUpdatedAt,
        @JsonKey(name: "creator.id")
        int? creatorId,
        @JsonKey(name: "creator.name")
        String? creatorName,
        @JsonKey(name: "creator.email")
        String? creatorEmail,
        @JsonKey(name: "creator.username")
        String? creatorUsername,
        @JsonKey(name: "creator.email_verified_at")
        dynamic creatorEmailVerifiedAt,
        @JsonKey(name: "creator.password")
        String? creatorPassword,
        @JsonKey(name: "creator.m_comp_id")
        int? creatorMCompId,
        @JsonKey(name: "creator.m_dir_id")
        int? creatorMDirId,
        @JsonKey(name: "creator.is_active")
        bool? creatorIsActive,
        @JsonKey(name: "creator.creator_id")
        dynamic creatorCreatorId,
        @JsonKey(name: "creator.last_editor_id")
        dynamic creatorLastEditorId,
        @JsonKey(name: "creator.remember_token")
        dynamic creatorRememberToken,
        @JsonKey(name: "creator.created_at")
        dynamic creatorCreatedAt,
        @JsonKey(name: "creator.updated_at")
        dynamic creatorUpdatedAt,
        @JsonKey(name: "creator.profil_image")
        dynamic creatorProfilImage,
        @JsonKey(name: "creator.telp")
        dynamic creatorTelp,
        @JsonKey(name: "creator.m_kary_id")
        dynamic creatorMKaryId,
        @JsonKey(name: "last_editor.id")
        dynamic lastEditorId,
        @JsonKey(name: "last_editor.name")
        dynamic lastEditorName,
        @JsonKey(name: "last_editor.email")
        dynamic lastEditorEmail,
        @JsonKey(name: "last_editor.username")
        dynamic lastEditorUsername,
        @JsonKey(name: "last_editor.email_verified_at")
        dynamic lastEditorEmailVerifiedAt,
        @JsonKey(name: "last_editor.password")
        dynamic lastEditorPassword,
        @JsonKey(name: "last_editor.m_comp_id")
        dynamic lastEditorMCompId,
        @JsonKey(name: "last_editor.m_dir_id")
        dynamic lastEditorMDirId,
        @JsonKey(name: "last_editor.is_active")
        dynamic lastEditorIsActive,
        @JsonKey(name: "last_editor.creator_id")
        dynamic lastEditorCreatorId,
        @JsonKey(name: "last_editor.last_editor_id")
        dynamic lastEditorLastEditorId,
        @JsonKey(name: "last_editor.remember_token")
        dynamic lastEditorRememberToken,
        @JsonKey(name: "last_editor.created_at")
        dynamic lastEditorCreatedAt,
        @JsonKey(name: "last_editor.updated_at")
        dynamic lastEditorUpdatedAt,
        @JsonKey(name: "last_editor.profil_image")
        dynamic lastEditorProfilImage,
        @JsonKey(name: "last_editor.telp")
        dynamic lastEditorTelp,
        @JsonKey(name: "last_editor.m_kary_id")
        dynamic lastEditorMKaryId,
    }) = _Datum;

    factory Datum.fromJson(Map<String, dynamic> json) => _$DatumFromJson(json);
}
