import 'package:freezed_annotation/freezed_annotation.dart';
import 'dart:convert';

part 'list_cuti_model.freezed.dart';
part 'list_cuti_model.g.dart';

@freezed
class ListCutiModel with _$ListCutiModel {
    const factory ListCutiModel({
        @JsonKey(name: "data")
        List<DataListCuti>? data,
        @JsonKey(name: "total")
        int? total,
        @JsonKey(name: "current_page")
        int? currentPage,
        @JsonKey(name: "per_page")
        int? perPage,
        @JsonKey(name: "from")
        int? from,
        @JsonKey(name: "to")
        int? to,
        @JsonKey(name: "last_page")
        int? lastPage,
        @JsonKey(name: "has_next")
        bool? hasNext,
        @JsonKey(name: "prev")
        dynamic prev,
        @JsonKey(name: "next")
        dynamic next,
        @JsonKey(name: "processed_time")
        double? processedTime,
    }) = _ListCutiModel;

    factory ListCutiModel.fromJson(Map<String, dynamic> json) => _$ListCutiModelFromJson(json);
}

@freezed
class DataListCuti with _$DataListCuti {
    const factory DataListCuti({
        @JsonKey(name: "meta_read")
        bool? metaRead,
        @JsonKey(name: "meta_delete")
        bool? metaDelete,
        @JsonKey(name: "meta_update")
        bool? metaUpdate,
        @JsonKey(name: "meta_create")
        bool? metaCreate,
        @JsonKey(name: "id")
        int? id,
        @JsonKey(name: "nomor")
        String? nomor,
        @JsonKey(name: "m_comp_id")
        int? datumMCompId,
        @JsonKey(name: "m_dir_id")
        int? datumMDirId,
        @JsonKey(name: "m_kary_id")
        int? datumMKaryId,
        @JsonKey(name: "alasan_id")
        int? datumAlasanId,
        @JsonKey(name: "tipe_cuti_id")
        int? datumTipeCutiId,
        @JsonKey(name: "date_from")
        String? dateFrom,
        @JsonKey(name: "date_to")
        String? dateTo,
        @JsonKey(name: "time_from")
        dynamic timeFrom,
        @JsonKey(name: "time_to")
        dynamic timeTo,
        @JsonKey(name: "keterangan")
        String? keterangan,
        @JsonKey(name: "status")
        String? status,
        @JsonKey(name: "creator_id")
        int? datumCreatorId,
        @JsonKey(name: "last_editor_id")
        dynamic datumLastEditorId,
        @JsonKey(name: "created_at")
        String? createdAt,
        @JsonKey(name: "updated_at")
        String? updatedAt,
        @JsonKey(name: "attachment")
        dynamic attachment,
        @JsonKey(name: "interval")
        int? interval,
        @JsonKey(name: "m_comp.id")
        int? mCompId,
        @JsonKey(name: "m_comp.nama")
        String? mCompNama,
        @JsonKey(name: "m_comp.is_active")
        bool? mCompIsActive,
        @JsonKey(name: "m_comp.desc")
        dynamic mCompDesc,
        @JsonKey(name: "m_comp.creator_id")
        dynamic mCompCreatorId,
        @JsonKey(name: "m_comp.last_editor_id")
        dynamic mCompLastEditorId,
        @JsonKey(name: "m_comp.created_at")
        dynamic mCompCreatedAt,
        @JsonKey(name: "m_comp.updated_at")
        dynamic mCompUpdatedAt,
        @JsonKey(name: "m_dir.id")
        dynamic mDirId,
        @JsonKey(name: "m_dir.m_comp_id")
        dynamic mDirMCompId,
        @JsonKey(name: "m_dir.nama")
        dynamic mDirNama,
        @JsonKey(name: "m_dir.desc")
        dynamic mDirDesc,
        @JsonKey(name: "m_dir.is_active")
        dynamic mDirIsActive,
        @JsonKey(name: "m_dir.creator_id")
        dynamic mDirCreatorId,
        @JsonKey(name: "m_dir.last_editor_id")
        dynamic mDirLastEditorId,
        @JsonKey(name: "m_dir.created_at")
        dynamic mDirCreatedAt,
        @JsonKey(name: "m_dir.updated_at")
        dynamic mDirUpdatedAt,
        @JsonKey(name: "m_kary.id")
        int? mKaryId,
        @JsonKey(name: "m_kary.m_comp_id")
        int? mKaryMCompId,
        @JsonKey(name: "m_kary.m_dir_id")
        int? mKaryMDirId,
        @JsonKey(name: "m_kary.m_divisi_id")
        int? mKaryMDivisiId,
        @JsonKey(name: "m_kary.m_dept_id")
        int? mKaryMDeptId,
        @JsonKey(name: "m_kary.m_zona_id")
        int? mKaryMZonaId,
        @JsonKey(name: "m_kary.grading_id")
        dynamic mKaryGradingId,
        @JsonKey(name: "m_kary.costcontre_id")
        int? mKaryCostcontreId,
        @JsonKey(name: "m_kary.kode")
        String? mKaryKode,
        @JsonKey(name: "m_kary.m_posisi_id")
        int? mKaryMPosisiId,
        @JsonKey(name: "m_kary.m_jam_kerja_id")
        int? mKaryMJamKerjaId,
        @JsonKey(name: "m_kary.kode_presensi")
        String? mKaryKodePresensi,
        @JsonKey(name: "m_kary.nik")
        String? mKaryNik,
        @JsonKey(name: "m_kary.nama_depan")
        String? mKaryNamaDepan,
        @JsonKey(name: "m_kary.nama_belakang")
        String? mKaryNamaBelakang,
        @JsonKey(name: "m_kary.nama_lengkap")
        String? mKaryNamaLengkap,
        @JsonKey(name: "m_kary.nama_panggilan")
        String? mKaryNamaPanggilan,
        @JsonKey(name: "m_kary.jk_id")
        int? mKaryJkId,
        @JsonKey(name: "m_kary.tempat_lahir")
        String? mKaryTempatLahir,
        @JsonKey(name: "m_kary.tgl_lahir")
        String? mKaryTglLahir,
        @JsonKey(name: "m_kary.provinsi_id")
        int? mKaryProvinsiId,
        @JsonKey(name: "m_kary.kota_id")
        int? mKaryKotaId,
        @JsonKey(name: "m_kary.kecamatan_id")
        int? mKaryKecamatanId,
        @JsonKey(name: "m_kary.kode_pos")
        String? mKaryKodePos,
        @JsonKey(name: "m_kary.alamat_asli")
        String? mKaryAlamatAsli,
        @JsonKey(name: "m_kary.alamat_domisili")
        String? mKaryAlamatDomisili,
        @JsonKey(name: "m_kary.no_tlp")
        String? mKaryNoTlp,
        @JsonKey(name: "m_kary.no_tlp_lainnya")
        String? mKaryNoTlpLainnya,
        @JsonKey(name: "m_kary.no_darurat")
        String? mKaryNoDarurat,
        @JsonKey(name: "m_kary.nama_kontak_darurat")
        String? mKaryNamaKontakDarurat,
        @JsonKey(name: "m_kary.agama_id")
        int? mKaryAgamaId,
        @JsonKey(name: "m_kary.gol_darah_id")
        int? mKaryGolDarahId,
        @JsonKey(name: "m_kary.status_nikah_id")
        int? mKaryStatusNikahId,
        @JsonKey(name: "m_kary.tanggungan_id")
        int? mKaryTanggunganId,
        @JsonKey(name: "m_kary.hub_dgn_karyawan")
        String? mKaryHubDgnKaryawan,
        @JsonKey(name: "m_kary.cuti_jatah_reguler")
        int? mKaryCutiJatahReguler,
        @JsonKey(name: "m_kary.cuti_sisa_reguler")
        int? mKaryCutiSisaReguler,
        @JsonKey(name: "m_kary.cuti_panjang")
        int? mKaryCutiPanjang,
        @JsonKey(name: "m_kary.cuti_sisa_panjang")
        int? mKaryCutiSisaPanjang,
        @JsonKey(name: "m_kary.status_kary_id")
        dynamic mKaryStatusKaryId,
        @JsonKey(name: "m_kary.lama_kontrak_awal")
        dynamic mKaryLamaKontrakAwal,
        @JsonKey(name: "m_kary.lama_kontrak_akhir")
        dynamic mKaryLamaKontrakAkhir,
        @JsonKey(name: "m_kary.tgl_masuk")
        String? mKaryTglMasuk,
        @JsonKey(name: "m_kary.tgl_berhenti")
        dynamic mKaryTglBerhenti,
        @JsonKey(name: "m_kary.alasan_berhenti")
        dynamic mKaryAlasanBerhenti,
        @JsonKey(name: "m_kary.uk_baju")
        String? mKaryUkBaju,
        @JsonKey(name: "m_kary.uk_celana")
        String? mKaryUkCelana,
        @JsonKey(name: "m_kary.uk_sepatu")
        String? mKaryUkSepatu,
        @JsonKey(name: "m_kary.desc")
        String? mKaryDesc,
        @JsonKey(name: "m_kary.is_active")
        bool? mKaryIsActive,
        @JsonKey(name: "m_kary.creator_id")
        dynamic mKaryCreatorId,
        @JsonKey(name: "m_kary.last_editor_id")
        int? mKaryLastEditorId,
        @JsonKey(name: "m_kary.created_at")
        String? mKaryCreatedAt,
        @JsonKey(name: "m_kary.updated_at")
        String? mKaryUpdatedAt,
        @JsonKey(name: "m_kary.m_standart_gaji_id")
        int? mKaryMStandartGajiId,
        @JsonKey(name: "m_kary.periode_gaji_id")
        int? mKaryPeriodeGajiId,
        @JsonKey(name: "m_kary.ref_id")
        dynamic mKaryRefId,
        @JsonKey(name: "m_kary.presensi_lokasi_default_id")
        dynamic mKaryPresensiLokasiDefaultId,
        @JsonKey(name: "m_kary.exp_date_cuti")
        dynamic mKaryExpDateCuti,
        @JsonKey(name: "m_kary.limit_potong")
        int? mKaryLimitPotong,
        @JsonKey(name: "m_kary.atasan_id")
        int? mKaryAtasanId,
        @JsonKey(name: "m_kary.cuti_p24")
        dynamic mKaryCutiP24,
        @JsonKey(name: "m_kary.cuti_sisa_p24")
        dynamic mKaryCutiSisaP24,
        @JsonKey(name: "alasan.id")
        int? alasanId,
        @JsonKey(name: "alasan.m_comp_id")
        int? alasanMCompId,
        @JsonKey(name: "alasan.m_dir_id")
        dynamic alasanMDirId,
        @JsonKey(name: "alasan.group")
        String? alasanGroup,
        @JsonKey(name: "alasan.key")
        String? alasanKey,
        @JsonKey(name: "alasan.code")
        String? alasanCode,
        @JsonKey(name: "alasan.value")
        String? alasanValue,
        @JsonKey(name: "alasan.is_active")
        bool? alasanIsActive,
        @JsonKey(name: "alasan.creator_id")
        dynamic alasanCreatorId,
        @JsonKey(name: "alasan.last_editor_id")
        dynamic alasanLastEditorId,
        @JsonKey(name: "alasan.created_at")
        dynamic alasanCreatedAt,
        @JsonKey(name: "alasan.updated_at")
        dynamic alasanUpdatedAt,
        @JsonKey(name: "alasan.value_2")
        dynamic alasanValue2,
        @JsonKey(name: "alasan.value_3")
        dynamic alasanValue3,
        @JsonKey(name: "tipe_cuti.id")
        int? tipeCutiId,
        @JsonKey(name: "tipe_cuti.m_comp_id")
        int? tipeCutiMCompId,
        @JsonKey(name: "tipe_cuti.m_dir_id")
        int? tipeCutiMDirId,
        @JsonKey(name: "tipe_cuti.group")
        String? tipeCutiGroup,
        @JsonKey(name: "tipe_cuti.key")
        String? tipeCutiKey,
        @JsonKey(name: "tipe_cuti.code")
        String? tipeCutiCode,
        @JsonKey(name: "tipe_cuti.value")
        String? tipeCutiValue,
        @JsonKey(name: "tipe_cuti.is_active")
        bool? tipeCutiIsActive,
        @JsonKey(name: "tipe_cuti.creator_id")
        dynamic tipeCutiCreatorId,
        @JsonKey(name: "tipe_cuti.last_editor_id")
        dynamic tipeCutiLastEditorId,
        @JsonKey(name: "tipe_cuti.created_at")
        dynamic tipeCutiCreatedAt,
        @JsonKey(name: "tipe_cuti.updated_at")
        String? tipeCutiUpdatedAt,
        @JsonKey(name: "tipe_cuti.value_2")
        dynamic tipeCutiValue2,
        @JsonKey(name: "tipe_cuti.value_3")
        dynamic tipeCutiValue3,
        @JsonKey(name: "creator.id")
        int? creatorId,
        @JsonKey(name: "creator.name")
        String? creatorName,
        @JsonKey(name: "creator.email")
        String? creatorEmail,
        @JsonKey(name: "creator.username")
        String? creatorUsername,
        @JsonKey(name: "creator.email_verified_at")
        dynamic creatorEmailVerifiedAt,
        @JsonKey(name: "creator.password")
        String? creatorPassword,
        @JsonKey(name: "creator.m_comp_id")
        int? creatorMCompId,
        @JsonKey(name: "creator.m_dir_id")
        int? creatorMDirId,
        @JsonKey(name: "creator.is_active")
        bool? creatorIsActive,
        @JsonKey(name: "creator.creator_id")
        dynamic creatorCreatorId,
        @JsonKey(name: "creator.last_editor_id")
        int? creatorLastEditorId,
        @JsonKey(name: "creator.remember_token")
        dynamic creatorRememberToken,
        @JsonKey(name: "creator.created_at")
        dynamic creatorCreatedAt,
        @JsonKey(name: "creator.updated_at")
        String? creatorUpdatedAt,
        @JsonKey(name: "creator.profil_image")
        String? creatorProfilImage,
        @JsonKey(name: "creator.telp")
        String? creatorTelp,
        @JsonKey(name: "creator.m_kary_id")
        int? creatorMKaryId,
        @JsonKey(name: "last_editor.id")
        dynamic lastEditorId,
        @JsonKey(name: "last_editor.name")
        dynamic lastEditorName,
        @JsonKey(name: "last_editor.email")
        dynamic lastEditorEmail,
        @JsonKey(name: "last_editor.username")
        dynamic lastEditorUsername,
        @JsonKey(name: "last_editor.email_verified_at")
        dynamic lastEditorEmailVerifiedAt,
        @JsonKey(name: "last_editor.password")
        dynamic lastEditorPassword,
        @JsonKey(name: "last_editor.m_comp_id")
        dynamic lastEditorMCompId,
        @JsonKey(name: "last_editor.m_dir_id")
        dynamic lastEditorMDirId,
        @JsonKey(name: "last_editor.is_active")
        dynamic lastEditorIsActive,
        @JsonKey(name: "last_editor.creator_id")
        dynamic lastEditorCreatorId,
        @JsonKey(name: "last_editor.last_editor_id")
        dynamic lastEditorLastEditorId,
        @JsonKey(name: "last_editor.remember_token")
        dynamic lastEditorRememberToken,
        @JsonKey(name: "last_editor.created_at")
        dynamic lastEditorCreatedAt,
        @JsonKey(name: "last_editor.updated_at")
        dynamic lastEditorUpdatedAt,
        @JsonKey(name: "last_editor.profil_image")
        dynamic lastEditorProfilImage,
        @JsonKey(name: "last_editor.telp")
        dynamic lastEditorTelp,
        @JsonKey(name: "last_editor.m_kary_id")
        dynamic lastEditorMKaryId,
        @JsonKey(name: "approval_note")
        String? approvalNote,
    }) = _DataListCuti;

    factory DataListCuti.fromJson(Map<String, dynamic> json) => _$DataListCutiFromJson(json);
}
