import 'package:freezed_annotation/freezed_annotation.dart';
import 'dart:convert';

part 'get_posisi_model.freezed.dart';
part 'get_posisi_model.g.dart';

@freezed
class GetPosisiModel with _$GetPosisiModel {
    const factory GetPosisiModel({
        @JsonKey(name: "data")
        List<DataPosisi>? data,
        @JsonKey(name: "total")
        int? total,
        @JsonKey(name: "current_page")
        int? currentPage,
        @JsonKey(name: "per_page")
        int? perPage,
        @JsonKey(name: "from")
        int? from,
        @JsonKey(name: "to")
        int? to,
        @JsonKey(name: "last_page")
        int? lastPage,
        @JsonKey(name: "has_next")
        bool? hasNext,
        @JsonKey(name: "prev")
        dynamic prev,
        @JsonKey(name: "next")
        dynamic next,
        @JsonKey(name: "processed_time")
        double? processedTime,
    }) = _GetPosisiModel;

    factory GetPosisiModel.fromJson(Map<String, dynamic> json) => _$GetPosisiModelFromJson(json);
}

@freezed
class DataPosisi with _$DataPosisi {
    const factory DataPosisi({
        @JsonKey(name: "meta_read")
        bool? metaRead,
        @JsonKey(name: "meta_delete")
        bool? metaDelete,
        @JsonKey(name: "meta_update")
        bool? metaUpdate,
        @JsonKey(name: "meta_create")
        bool? metaCreate,
        @JsonKey(name: "id")
        int? id,
        @JsonKey(name: "m_comp_id")
        int? datumMCompId,
        @JsonKey(name: "m_dir_id")
        int? datumMDirId,
        @JsonKey(name: "kode")
        String? kode,
        @JsonKey(name: "desc_kerja")
        String? descKerja,
        @JsonKey(name: "desc_kerja_1")
        String? descKerja1,
        @JsonKey(name: "desc_kerja_2")
        String? descKerja2,
        @JsonKey(name: "min_pengalaman")
        String? minPengalaman,
        @JsonKey(name: "min_pendidikan_id")
        int? datumMinPendidikanId,
        @JsonKey(name: "min_gaji_pokok")
        int? minGajiPokok,
        @JsonKey(name: "max_gaji_pokok")
        int? maxGajiPokok,
        @JsonKey(name: "biaya")
        dynamic biaya,
        @JsonKey(name: "tipe_bpjs_id")
        int? datumTipeBpjsId,
        @JsonKey(name: "potongan_bpjs")
        int? potonganBpjs,
        @JsonKey(name: "desc")
        String? desc,
        @JsonKey(name: "is_active")
        bool? isActive,
        @JsonKey(name: "creator_id")
        dynamic datumCreatorId,
        @JsonKey(name: "last_editor_id")
        dynamic datumLastEditorId,
        @JsonKey(name: "created_at")
        String? createdAt,
        @JsonKey(name: "updated_at")
        String? updatedAt,
        @JsonKey(name: "m_comp.id")
        int? mCompId,
        @JsonKey(name: "m_comp.nama")
        String? mCompNama,
        @JsonKey(name: "m_comp.is_active")
        bool? mCompIsActive,
        @JsonKey(name: "m_comp.desc")
        dynamic mCompDesc,
        @JsonKey(name: "m_comp.creator_id")
        dynamic mCompCreatorId,
        @JsonKey(name: "m_comp.last_editor_id")
        dynamic mCompLastEditorId,
        @JsonKey(name: "m_comp.created_at")
        dynamic mCompCreatedAt,
        @JsonKey(name: "m_comp.updated_at")
        dynamic mCompUpdatedAt,
        @JsonKey(name: "m_dir.id")
        int? mDirId,
        @JsonKey(name: "m_dir.m_comp_id")
        int? mDirMCompId,
        @JsonKey(name: "m_dir.nama")
        String? mDirNama,
        @JsonKey(name: "m_dir.desc")
        dynamic mDirDesc,
        @JsonKey(name: "m_dir.is_active")
        bool? mDirIsActive,
        @JsonKey(name: "m_dir.creator_id")
        dynamic mDirCreatorId,
        @JsonKey(name: "m_dir.last_editor_id")
        dynamic mDirLastEditorId,
        @JsonKey(name: "m_dir.created_at")
        dynamic mDirCreatedAt,
        @JsonKey(name: "m_dir.updated_at")
        dynamic mDirUpdatedAt,
        @JsonKey(name: "min_pendidikan.id")
        int? minPendidikanId,
        @JsonKey(name: "min_pendidikan.m_comp_id")
        int? minPendidikanMCompId,
        @JsonKey(name: "min_pendidikan.m_dir_id")
        dynamic minPendidikanMDirId,
        @JsonKey(name: "min_pendidikan.group")
        String? minPendidikanGroup,
        @JsonKey(name: "min_pendidikan.key")
        String? minPendidikanKey,
        @JsonKey(name: "min_pendidikan.code")
        String? minPendidikanCode,
        @JsonKey(name: "min_pendidikan.value")
        String? minPendidikanValue,
        @JsonKey(name: "min_pendidikan.is_active")
        bool? minPendidikanIsActive,
        @JsonKey(name: "min_pendidikan.creator_id")
        dynamic minPendidikanCreatorId,
        @JsonKey(name: "min_pendidikan.last_editor_id")
        dynamic minPendidikanLastEditorId,
        @JsonKey(name: "min_pendidikan.created_at")
        String? minPendidikanCreatedAt,
        @JsonKey(name: "min_pendidikan.updated_at")
        String? minPendidikanUpdatedAt,
        @JsonKey(name: "min_pendidikan.value_2")
        dynamic minPendidikanValue2,
        @JsonKey(name: "min_pendidikan.value_3")
        dynamic minPendidikanValue3,
        @JsonKey(name: "tipe_bpjs.id")
        int? tipeBpjsId,
        @JsonKey(name: "tipe_bpjs.m_comp_id")
        int? tipeBpjsMCompId,
        @JsonKey(name: "tipe_bpjs.m_dir_id")
        dynamic tipeBpjsMDirId,
        @JsonKey(name: "tipe_bpjs.group")
        String? tipeBpjsGroup,
        @JsonKey(name: "tipe_bpjs.key")
        String? tipeBpjsKey,
        @JsonKey(name: "tipe_bpjs.code")
        String? tipeBpjsCode,
        @JsonKey(name: "tipe_bpjs.value")
        String? tipeBpjsValue,
        @JsonKey(name: "tipe_bpjs.is_active")
        bool? tipeBpjsIsActive,
        @JsonKey(name: "tipe_bpjs.creator_id")
        dynamic tipeBpjsCreatorId,
        @JsonKey(name: "tipe_bpjs.last_editor_id")
        dynamic tipeBpjsLastEditorId,
        @JsonKey(name: "tipe_bpjs.created_at")
        String? tipeBpjsCreatedAt,
        @JsonKey(name: "tipe_bpjs.updated_at")
        String? tipeBpjsUpdatedAt,
        @JsonKey(name: "tipe_bpjs.value_2")
        dynamic tipeBpjsValue2,
        @JsonKey(name: "tipe_bpjs.value_3")
        dynamic tipeBpjsValue3,
        @JsonKey(name: "creator.id")
        dynamic creatorId,
        @JsonKey(name: "creator.name")
        dynamic creatorName,
        @JsonKey(name: "creator.email")
        dynamic creatorEmail,
        @JsonKey(name: "creator.username")
        dynamic creatorUsername,
        @JsonKey(name: "creator.email_verified_at")
        dynamic creatorEmailVerifiedAt,
        @JsonKey(name: "creator.password")
        dynamic creatorPassword,
        @JsonKey(name: "creator.m_comp_id")
        dynamic creatorMCompId,
        @JsonKey(name: "creator.m_dir_id")
        dynamic creatorMDirId,
        @JsonKey(name: "creator.is_active")
        dynamic creatorIsActive,
        @JsonKey(name: "creator.creator_id")
        dynamic creatorCreatorId,
        @JsonKey(name: "creator.last_editor_id")
        dynamic creatorLastEditorId,
        @JsonKey(name: "creator.remember_token")
        dynamic creatorRememberToken,
        @JsonKey(name: "creator.created_at")
        dynamic creatorCreatedAt,
        @JsonKey(name: "creator.updated_at")
        dynamic creatorUpdatedAt,
        @JsonKey(name: "creator.profil_image")
        dynamic creatorProfilImage,
        @JsonKey(name: "creator.telp")
        dynamic creatorTelp,
        @JsonKey(name: "creator.m_kary_id")
        dynamic creatorMKaryId,
        @JsonKey(name: "last_editor.id")
        dynamic lastEditorId,
        @JsonKey(name: "last_editor.name")
        dynamic lastEditorName,
        @JsonKey(name: "last_editor.email")
        dynamic lastEditorEmail,
        @JsonKey(name: "last_editor.username")
        dynamic lastEditorUsername,
        @JsonKey(name: "last_editor.email_verified_at")
        dynamic lastEditorEmailVerifiedAt,
        @JsonKey(name: "last_editor.password")
        dynamic lastEditorPassword,
        @JsonKey(name: "last_editor.m_comp_id")
        dynamic lastEditorMCompId,
        @JsonKey(name: "last_editor.m_dir_id")
        dynamic lastEditorMDirId,
        @JsonKey(name: "last_editor.is_active")
        dynamic lastEditorIsActive,
        @JsonKey(name: "last_editor.creator_id")
        dynamic lastEditorCreatorId,
        @JsonKey(name: "last_editor.last_editor_id")
        dynamic lastEditorLastEditorId,
        @JsonKey(name: "last_editor.remember_token")
        dynamic lastEditorRememberToken,
        @JsonKey(name: "last_editor.created_at")
        dynamic lastEditorCreatedAt,
        @JsonKey(name: "last_editor.updated_at")
        dynamic lastEditorUpdatedAt,
        @JsonKey(name: "last_editor.profil_image")
        dynamic lastEditorProfilImage,
        @JsonKey(name: "last_editor.telp")
        dynamic lastEditorTelp,
        @JsonKey(name: "last_editor.m_kary_id")
        dynamic lastEditorMKaryId,
    }) = _DataPosisi;

    factory DataPosisi.fromJson(Map<String, dynamic> json) => _$DataPosisiFromJson(json);
}
