// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'response_biodata_karyawan.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ResponseBiodataKaryawanImpl _$$ResponseBiodataKaryawanImplFromJson(
        Map<String, dynamic> json) =>
    _$ResponseBiodataKaryawanImpl(
      timestamp: json['timestamp'] as String?,
      code: json['code'] as int?,
      message: json['message'] as String?,
      data: json['data'] == null
          ? null
          : Biodata.fromJson(json['data'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$$ResponseBiodataKaryawanImplToJson(
        _$ResponseBiodataKaryawanImpl instance) =>
    <String, dynamic>{
      'timestamp': instance.timestamp,
      'code': instance.code,
      'message': instance.message,
      'data': instance.data,
    };

_$BiodataImpl _$$BiodataImplFromJson(Map<String, dynamic> json) =>
    _$BiodataImpl(
      id: json['id'] as int?,
      mCompId: json['m_comp_id'] as int?,
      mDirId: json['m_dir_id'] as int?,
      mDivisiId: json['m_divisi_id'] as int?,
      mDeptId: json['m_dept_id'] as int?,
      mZonaId: json['m_zona_id'] as int?,
      gradingId: json['grading_id'],
      costcontreId: json['costcontre_id'] as int?,
      kode: json['kode'] as String?,
      mPosisiId: json['m_posisi_id'] as int?,
      mJamKerjaId: json['m_jam_kerja_id'] as int?,
      kodePresensi: json['kode_presensi'] as String?,
      nik: json['nik'] as String?,
      namaDepan: json['nama_depan'] as String?,
      namaBelakang: json['nama_belakang'] as String?,
      namaLengkap: json['nama_lengkap'] as String?,
      namaPanggilan: json['nama_panggilan'] as String?,
      jkId: json['jk_id'] as int?,
      tempatLahir: json['tempat_lahir'] as String?,
      tglLahir: json['tgl_lahir'] == null
          ? null
          : DateTime.parse(json['tgl_lahir'] as String),
      provinsiId: json['provinsi_id'] as int?,
      kotaId: json['kota_id'] as int?,
      kecamatanId: json['kecamatan_id'] as int?,
      kodePos: json['kode_pos'] as String?,
      alamatAsli: json['alamat_asli'] as String?,
      alamatDomisili: json['alamat_domisili'] as String?,
      noTlp: json['no_tlp'] as String?,
      noTlpLainnya: json['no_tlp_lainnya'] as String?,
      noDarurat: json['no_darurat'] as String?,
      namaKontakDarurat: json['nama_kontak_darurat'] as String?,
      agamaId: json['agama_id'] as int?,
      golDarahId: json['gol_darah_id'] as int?,
      statusNikahId: json['status_nikah_id'] as int?,
      tanggunganId: json['tanggungan_id'] as int?,
      hubDgnKaryawan: json['hub_dgn_karyawan'] as String?,
      cutiJatahReguler: json['cuti_jatah_reguler'] as int?,
      cutiSisaReguler: json['cuti_sisa_reguler'] as int?,
      cutiPanjang: json['cuti_panjang'] as int?,
      cutiSisaPanjang: json['cuti_sisa_panjang'] as int?,
      statusKaryId: json['status_kary_id'],
      lamaKontrakAwal: json['lama_kontrak_awal'],
      lamaKontrakAkhir: json['lama_kontrak_akhir'],
      tglMasuk: json['tgl_masuk'] == null
          ? null
          : DateTime.parse(json['tgl_masuk'] as String),
      tglBerhenti: json['tgl_berhenti'],
      alasanBerhenti: json['alasan_berhenti'],
      ukBaju: json['uk_baju'] as String?,
      ukCelana: json['uk_celana'] as String?,
      ukSepatu: json['uk_sepatu'] as String?,
      desc: json['desc'],
      isActive: json['is_active'] as bool?,
      creatorId: json['creator_id'] as int?,
      lastEditorId: json['last_editor_id'] as int?,
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
      mStandartGajiId: json['m_standart_gaji_id'] as int?,
      periodeGajiId: json['periode_gaji_id'] as int?,
      refId: json['ref_id'],
      presensiLokasiDefaultId: json['presensi_lokasi_default_id'],
      expDateCuti: json['exp_date_cuti'] == null
          ? null
          : DateTime.parse(json['exp_date_cuti'] as String),
      dir: json['dir'] as String?,
      div: json['div'] as String?,
      dept: json['dept'] as String?,
      zona: json['zona'] as String?,
      grading: json['grading'],
      posisi: json['posisi'] as String?,
      jamKerja: json['jam_kerja'] as String?,
      jk: json['jk'] as String?,
      provinsi: json['provinsi'] as String?,
      kota: json['kota'] as String?,
      kecamatan: json['kecamatan'] as String?,
      agama: json['agama'] as String?,
      golDarah: json['gol_darah'] as String?,
      tanggungan: json['tanggungan'] as String?,
      costcontre: json['costcontre'] as String?,
      statusNikah: json['status_nikah'] as String?,
      ktpNo: json['ktp_no'] as String?,
      ktpFoto: json['ktp_foto'] as String?,
      pasFoto: json['pas_foto'] as String?,
      kkNo: json['kk_no'] as String?,
      kkFoto: json['kk_foto'] as String?,
      npwpNo: json['npwp_no'] as String?,
      npwpFoto: json['npwp_foto'] as String?,
      npwpTglBerlaku: json['npwp_tgl_berlaku'] == null
          ? null
          : DateTime.parse(json['npwp_tgl_berlaku'] as String),
      bpjsTipeId: json['bpjs_tipe_id'] as int?,
      bpjsNo: json['bpjs_no'] as String?,
      bpjsFoto: json['bpjs_foto'] as String?,
      berkasLain: json['berkas_lain'] as String?,
      descFile: json['desc_file'],
    );

Map<String, dynamic> _$$BiodataImplToJson(_$BiodataImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'm_comp_id': instance.mCompId,
      'm_dir_id': instance.mDirId,
      'm_divisi_id': instance.mDivisiId,
      'm_dept_id': instance.mDeptId,
      'm_zona_id': instance.mZonaId,
      'grading_id': instance.gradingId,
      'costcontre_id': instance.costcontreId,
      'kode': instance.kode,
      'm_posisi_id': instance.mPosisiId,
      'm_jam_kerja_id': instance.mJamKerjaId,
      'kode_presensi': instance.kodePresensi,
      'nik': instance.nik,
      'nama_depan': instance.namaDepan,
      'nama_belakang': instance.namaBelakang,
      'nama_lengkap': instance.namaLengkap,
      'nama_panggilan': instance.namaPanggilan,
      'jk_id': instance.jkId,
      'tempat_lahir': instance.tempatLahir,
      'tgl_lahir': instance.tglLahir?.toIso8601String(),
      'provinsi_id': instance.provinsiId,
      'kota_id': instance.kotaId,
      'kecamatan_id': instance.kecamatanId,
      'kode_pos': instance.kodePos,
      'alamat_asli': instance.alamatAsli,
      'alamat_domisili': instance.alamatDomisili,
      'no_tlp': instance.noTlp,
      'no_tlp_lainnya': instance.noTlpLainnya,
      'no_darurat': instance.noDarurat,
      'nama_kontak_darurat': instance.namaKontakDarurat,
      'agama_id': instance.agamaId,
      'gol_darah_id': instance.golDarahId,
      'status_nikah_id': instance.statusNikahId,
      'tanggungan_id': instance.tanggunganId,
      'hub_dgn_karyawan': instance.hubDgnKaryawan,
      'cuti_jatah_reguler': instance.cutiJatahReguler,
      'cuti_sisa_reguler': instance.cutiSisaReguler,
      'cuti_panjang': instance.cutiPanjang,
      'cuti_sisa_panjang': instance.cutiSisaPanjang,
      'status_kary_id': instance.statusKaryId,
      'lama_kontrak_awal': instance.lamaKontrakAwal,
      'lama_kontrak_akhir': instance.lamaKontrakAkhir,
      'tgl_masuk': instance.tglMasuk?.toIso8601String(),
      'tgl_berhenti': instance.tglBerhenti,
      'alasan_berhenti': instance.alasanBerhenti,
      'uk_baju': instance.ukBaju,
      'uk_celana': instance.ukCelana,
      'uk_sepatu': instance.ukSepatu,
      'desc': instance.desc,
      'is_active': instance.isActive,
      'creator_id': instance.creatorId,
      'last_editor_id': instance.lastEditorId,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      'm_standart_gaji_id': instance.mStandartGajiId,
      'periode_gaji_id': instance.periodeGajiId,
      'ref_id': instance.refId,
      'presensi_lokasi_default_id': instance.presensiLokasiDefaultId,
      'exp_date_cuti': instance.expDateCuti?.toIso8601String(),
      'dir': instance.dir,
      'div': instance.div,
      'dept': instance.dept,
      'zona': instance.zona,
      'grading': instance.grading,
      'posisi': instance.posisi,
      'jam_kerja': instance.jamKerja,
      'jk': instance.jk,
      'provinsi': instance.provinsi,
      'kota': instance.kota,
      'kecamatan': instance.kecamatan,
      'agama': instance.agama,
      'gol_darah': instance.golDarah,
      'tanggungan': instance.tanggungan,
      'costcontre': instance.costcontre,
      'status_nikah': instance.statusNikah,
      'ktp_no': instance.ktpNo,
      'ktp_foto': instance.ktpFoto,
      'pas_foto': instance.pasFoto,
      'kk_no': instance.kkNo,
      'kk_foto': instance.kkFoto,
      'npwp_no': instance.npwpNo,
      'npwp_foto': instance.npwpFoto,
      'npwp_tgl_berlaku': instance.npwpTglBerlaku?.toIso8601String(),
      'bpjs_tipe_id': instance.bpjsTipeId,
      'bpjs_no': instance.bpjsNo,
      'bpjs_foto': instance.bpjsFoto,
      'berkas_lain': instance.berkasLain,
      'desc_file': instance.descFile,
    };
