// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'detail_realisasi_dinas_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$DetailRealisasiDinasModelImpl _$$DetailRealisasiDinasModelImplFromJson(
        Map<String, dynamic> json) =>
    _$DetailRealisasiDinasModelImpl(
      data: json['data'] == null
          ? null
          : DetailRealisasiData.fromJson(json['data'] as Map<String, dynamic>),
      processedTime: (json['processed_time'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$$DetailRealisasiDinasModelImplToJson(
        _$DetailRealisasiDinasModelImpl instance) =>
    <String, dynamic>{
      'data': instance.data,
      'processed_time': instance.processedTime,
    };

_$DetailRealisasiDataImpl _$$DetailRealisasiDataImplFromJson(
        Map<String, dynamic> json) =>
    _$DetailRealisasiDataImpl(
      id: json['id'] as int?,
      nomor: json['nomor'] as String?,
      dataMCompId: json['m_comp_id'] as int?,
      dataTSpdId: json['t_spd_id'] as int?,
      totalBiayaSpd: json['total_biaya_spd'] as int?,
      totalBiayaSelisih: json['total_biaya_selisih'] as int?,
      pengambilanSpd: json['pengambilan_spd'],
      keterangan: json['keterangan'] as String?,
      status: json['status'] as String?,
      dataCreatorId: json['creator_id'] as int?,
      dataLastEditorId: json['last_editor_id'] as int?,
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
      mCompId: json['m_comp.id'] as int?,
      mCompNama: json['m_comp.nama'] as String?,
      mCompIsActive: json['m_comp.is_active'] as bool?,
      mCompDesc: json['m_comp.desc'],
      mCompCreatorId: json['m_comp.creator_id'],
      mCompLastEditorId: json['m_comp.last_editor_id'],
      mCompCreatedAt: json['m_comp.created_at'],
      mCompUpdatedAt: json['m_comp.updated_at'],
      tSpdId: json['t_spd.id'] as int?,
      tSpdNomor: json['t_spd.nomor'] as String?,
      tSpdMCompId: json['t_spd.m_comp_id'] as int?,
      tSpdMSpdId: json['t_spd.m_spd_id'] as int?,
      tSpdMDirId: json['t_spd.m_dir_id'] as int?,
      tSpdMDivisiId: json['t_spd.m_divisi_id'] as int?,
      tSpdMDeptId: json['t_spd.m_dept_id'] as int?,
      tSpdMPosisiId: json['t_spd.m_posisi_id'] as int?,
      tSpdTanggal: json['t_spd.tanggal'] as String?,
      tSpdTglAcaraAwal: json['t_spd.tgl_acara_awal'] as String?,
      tSpdTglAcaraAkhir: json['t_spd.tgl_acara_akhir'] as String?,
      tSpdJenisSpdId: json['t_spd.jenis_spd_id'] as int?,
      tSpdMZonaAsalId: json['t_spd.m_zona_asal_id'] as int?,
      tSpdMZonaTujuanId: json['t_spd.m_zona_tujuan_id'] as int?,
      tSpdMLokasiTujuanId: json['t_spd.m_lokasi_tujuan_id'] as int?,
      tSpdMKaryId: json['t_spd.m_kary_id'] as int?,
      tSpdPicId: json['t_spd.pic_id'] as int?,
      tSpdTotalBiaya: json['t_spd.total_biaya'] as String?,
      tSpdKegiatan: json['t_spd.kegiatan'] as String?,
      tSpdKeterangan: json['t_spd.keterangan'] as String?,
      tSpdStatus: json['t_spd.status'] as String?,
      tSpdCreatorId: json['t_spd.creator_id'] as int?,
      tSpdLastEditorId: json['t_spd.last_editor_id'],
      tSpdCreatedAt: json['t_spd.created_at'] as String?,
      tSpdUpdatedAt: json['t_spd.updated_at'] as String?,
      tSpdIsKendDinas: json['t_spd.is_kend_dinas'] as bool?,
      creatorId: json['creator.id'] as int?,
      creatorName: json['creator.name'] as String?,
      creatorEmail: json['creator.email'] as String?,
      creatorUsername: json['creator.username'] as String?,
      creatorEmailVerifiedAt: json['creator.email_verified_at'],
      creatorPassword: json['creator.password'] as String?,
      creatorMCompId: json['creator.m_comp_id'] as int?,
      creatorMDirId: json['creator.m_dir_id'] as int?,
      creatorIsActive: json['creator.is_active'] as bool?,
      creatorCreatorId: json['creator.creator_id'] as int?,
      creatorLastEditorId: json['creator.last_editor_id'] as int?,
      creatorRememberToken: json['creator.remember_token'],
      creatorCreatedAt: json['creator.created_at'] as String?,
      creatorUpdatedAt: json['creator.updated_at'] as String?,
      creatorProfilImage: json['creator.profil_image'] as String?,
      creatorTelp: json['creator.telp'],
      creatorMKaryId: json['creator.m_kary_id'] as int?,
      lastEditorId: json['last_editor.id'] as int?,
      lastEditorName: json['last_editor.name'] as String?,
      lastEditorEmail: json['last_editor.email'] as String?,
      lastEditorUsername: json['last_editor.username'] as String?,
      lastEditorEmailVerifiedAt: json['last_editor.email_verified_at'],
      lastEditorPassword: json['last_editor.password'] as String?,
      lastEditorMCompId: json['last_editor.m_comp_id'] as int?,
      lastEditorMDirId: json['last_editor.m_dir_id'] as int?,
      lastEditorIsActive: json['last_editor.is_active'] as bool?,
      lastEditorCreatorId: json['last_editor.creator_id'] as int?,
      lastEditorLastEditorId: json['last_editor.last_editor_id'] as int?,
      lastEditorRememberToken: json['last_editor.remember_token'],
      lastEditorCreatedAt: json['last_editor.created_at'] as String?,
      lastEditorUpdatedAt: json['last_editor.updated_at'] as String?,
      lastEditorProfilImage: json['last_editor.profil_image'] as String?,
      lastEditorTelp: json['last_editor.telp'],
      lastEditorMKaryId: json['last_editor.m_kary_id'] as int?,
      tRpdDet: (json['t_rpd_det'] as List<dynamic>?)
          ?.map((e) => TRpdDet.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$$DetailRealisasiDataImplToJson(
        _$DetailRealisasiDataImpl instance) =>
    <String, dynamic>{
      'id': instance.id,
      'nomor': instance.nomor,
      'm_comp_id': instance.dataMCompId,
      't_spd_id': instance.dataTSpdId,
      'total_biaya_spd': instance.totalBiayaSpd,
      'total_biaya_selisih': instance.totalBiayaSelisih,
      'pengambilan_spd': instance.pengambilanSpd,
      'keterangan': instance.keterangan,
      'status': instance.status,
      'creator_id': instance.dataCreatorId,
      'last_editor_id': instance.dataLastEditorId,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      'm_comp.id': instance.mCompId,
      'm_comp.nama': instance.mCompNama,
      'm_comp.is_active': instance.mCompIsActive,
      'm_comp.desc': instance.mCompDesc,
      'm_comp.creator_id': instance.mCompCreatorId,
      'm_comp.last_editor_id': instance.mCompLastEditorId,
      'm_comp.created_at': instance.mCompCreatedAt,
      'm_comp.updated_at': instance.mCompUpdatedAt,
      't_spd.id': instance.tSpdId,
      't_spd.nomor': instance.tSpdNomor,
      't_spd.m_comp_id': instance.tSpdMCompId,
      't_spd.m_spd_id': instance.tSpdMSpdId,
      't_spd.m_dir_id': instance.tSpdMDirId,
      't_spd.m_divisi_id': instance.tSpdMDivisiId,
      't_spd.m_dept_id': instance.tSpdMDeptId,
      't_spd.m_posisi_id': instance.tSpdMPosisiId,
      't_spd.tanggal': instance.tSpdTanggal,
      't_spd.tgl_acara_awal': instance.tSpdTglAcaraAwal,
      't_spd.tgl_acara_akhir': instance.tSpdTglAcaraAkhir,
      't_spd.jenis_spd_id': instance.tSpdJenisSpdId,
      't_spd.m_zona_asal_id': instance.tSpdMZonaAsalId,
      't_spd.m_zona_tujuan_id': instance.tSpdMZonaTujuanId,
      't_spd.m_lokasi_tujuan_id': instance.tSpdMLokasiTujuanId,
      't_spd.m_kary_id': instance.tSpdMKaryId,
      't_spd.pic_id': instance.tSpdPicId,
      't_spd.total_biaya': instance.tSpdTotalBiaya,
      't_spd.kegiatan': instance.tSpdKegiatan,
      't_spd.keterangan': instance.tSpdKeterangan,
      't_spd.status': instance.tSpdStatus,
      't_spd.creator_id': instance.tSpdCreatorId,
      't_spd.last_editor_id': instance.tSpdLastEditorId,
      't_spd.created_at': instance.tSpdCreatedAt,
      't_spd.updated_at': instance.tSpdUpdatedAt,
      't_spd.is_kend_dinas': instance.tSpdIsKendDinas,
      'creator.id': instance.creatorId,
      'creator.name': instance.creatorName,
      'creator.email': instance.creatorEmail,
      'creator.username': instance.creatorUsername,
      'creator.email_verified_at': instance.creatorEmailVerifiedAt,
      'creator.password': instance.creatorPassword,
      'creator.m_comp_id': instance.creatorMCompId,
      'creator.m_dir_id': instance.creatorMDirId,
      'creator.is_active': instance.creatorIsActive,
      'creator.creator_id': instance.creatorCreatorId,
      'creator.last_editor_id': instance.creatorLastEditorId,
      'creator.remember_token': instance.creatorRememberToken,
      'creator.created_at': instance.creatorCreatedAt,
      'creator.updated_at': instance.creatorUpdatedAt,
      'creator.profil_image': instance.creatorProfilImage,
      'creator.telp': instance.creatorTelp,
      'creator.m_kary_id': instance.creatorMKaryId,
      'last_editor.id': instance.lastEditorId,
      'last_editor.name': instance.lastEditorName,
      'last_editor.email': instance.lastEditorEmail,
      'last_editor.username': instance.lastEditorUsername,
      'last_editor.email_verified_at': instance.lastEditorEmailVerifiedAt,
      'last_editor.password': instance.lastEditorPassword,
      'last_editor.m_comp_id': instance.lastEditorMCompId,
      'last_editor.m_dir_id': instance.lastEditorMDirId,
      'last_editor.is_active': instance.lastEditorIsActive,
      'last_editor.creator_id': instance.lastEditorCreatorId,
      'last_editor.last_editor_id': instance.lastEditorLastEditorId,
      'last_editor.remember_token': instance.lastEditorRememberToken,
      'last_editor.created_at': instance.lastEditorCreatedAt,
      'last_editor.updated_at': instance.lastEditorUpdatedAt,
      'last_editor.profil_image': instance.lastEditorProfilImage,
      'last_editor.telp': instance.lastEditorTelp,
      'last_editor.m_kary_id': instance.lastEditorMKaryId,
      't_rpd_det': instance.tRpdDet,
    };

_$TRpdDetImpl _$$TRpdDetImplFromJson(Map<String, dynamic> json) =>
    _$TRpdDetImpl(
      metaRead: json['meta_read'] as bool?,
      metaDelete: json['meta_delete'] as bool?,
      metaUpdate: json['meta_update'] as bool?,
      metaCreate: json['meta_create'] as bool?,
      id: json['id'] as int?,
      tRpdId: json['t_rpd_id'] as int?,
      tRpdDetTSpdDetId: json['t_spd_det_id'] as int?,
      tRpdDetTipeSpdId: json['tipe_spd_id'] as int?,
      biaya: json['biaya'] as int?,
      biayaRealisasi: json['biaya_realisasi'] as int?,
      detailTransport: json['detail_transport'],
      tRpdDetMKndDinasId: json['m_knd_dinas_id'],
      isKendaraanDinas: json['is_kendaraan_dinas'] as bool?,
      catatanRealisasi: json['catatan_realisasi'] as String?,
      tRpdDetCreatorId: json['creator_id'],
      tRpdDetLastEditorId: json['last_editor_id'],
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
      tSpdDetId: json['t_spd_det.id'] as int?,
      tSpdDetTSpdId: json['t_spd_det.t_spd_id'] as int?,
      tSpdDetTipeSpdId: json['t_spd_det.tipe_spd_id'] as int?,
      tSpdDetBiaya: json['t_spd_det.biaya'] as String?,
      tSpdDetBiayaRealisasi: json['t_spd_det.biaya_realisasi'],
      tSpdDetDetailTransport: json['t_spd_det.detail_transport'],
      tSpdDetMKndDinasId: json['t_spd_det.m_knd_dinas_id'],
      tSpdDetIsKendaraanDinas: json['t_spd_det.is_kendaraan_dinas'] as bool?,
      tSpdDetKeterangan: json['t_spd_det.keterangan'] as String?,
      tSpdDetCatatanRealisasi: json['t_spd_det.catatan_realisasi'],
      tSpdDetIsNow: json['t_spd_det.is_now'],
      tSpdDetCreatorId: json['t_spd_det.creator_id'],
      tSpdDetLastEditorId: json['t_spd_det.last_editor_id'],
      tSpdDetCreatedAt: json['t_spd_det.created_at'] as String?,
      tSpdDetUpdatedAt: json['t_spd_det.updated_at'] as String?,
      tipeSpdId: json['tipe_spd.id'] as int?,
      tipeSpdMCompId: json['tipe_spd.m_comp_id'] as int?,
      tipeSpdMDirId: json['tipe_spd.m_dir_id'],
      tipeSpdGroup: json['tipe_spd.group'] as String?,
      tipeSpdKey: json['tipe_spd.key'] as String?,
      tipeSpdCode: json['tipe_spd.code'] as String?,
      tipeSpdValue: json['tipe_spd.value'] as String?,
      tipeSpdIsActive: json['tipe_spd.is_active'] as bool?,
      tipeSpdCreatorId: json['tipe_spd.creator_id'],
      tipeSpdLastEditorId: json['tipe_spd.last_editor_id'],
      tipeSpdCreatedAt: json['tipe_spd.created_at'] as String?,
      tipeSpdUpdatedAt: json['tipe_spd.updated_at'] as String?,
      tipeSpdValue2: json['tipe_spd.value_2'],
      tipeSpdValue3: json['tipe_spd.value_3'],
      mKndDinasId: json['m_knd_dinas.id'],
      mKndDinasMCompId: json['m_knd_dinas.m_comp_id'],
      mKndDinasMDirId: json['m_knd_dinas.m_dir_id'],
      mKndDinasNama: json['m_knd_dinas.nama'],
      mKndDinasNopol: json['m_knd_dinas.nopol'],
      mKndDinasMLokasiId: json['m_knd_dinas.m_lokasi_id'],
      mKndDinasDesc: json['m_knd_dinas.desc'],
      mKndDinasIsActive: json['m_knd_dinas.is_active'],
      mKndDinasCreatorId: json['m_knd_dinas.creator_id'],
      mKndDinasLastEditorId: json['m_knd_dinas.last_editor_id'],
      mKndDinasCreatedAt: json['m_knd_dinas.created_at'],
      mKndDinasUpdatedAt: json['m_knd_dinas.updated_at'],
      creatorId: json['creator.id'],
      creatorName: json['creator.name'],
      creatorEmail: json['creator.email'],
      creatorUsername: json['creator.username'],
      creatorEmailVerifiedAt: json['creator.email_verified_at'],
      creatorPassword: json['creator.password'],
      creatorMCompId: json['creator.m_comp_id'],
      creatorMDirId: json['creator.m_dir_id'],
      creatorIsActive: json['creator.is_active'],
      creatorCreatorId: json['creator.creator_id'],
      creatorLastEditorId: json['creator.last_editor_id'],
      creatorRememberToken: json['creator.remember_token'],
      creatorCreatedAt: json['creator.created_at'],
      creatorUpdatedAt: json['creator.updated_at'],
      creatorProfilImage: json['creator.profil_image'],
      creatorTelp: json['creator.telp'],
      creatorMKaryId: json['creator.m_kary_id'],
      lastEditorId: json['last_editor.id'],
      lastEditorName: json['last_editor.name'],
      lastEditorEmail: json['last_editor.email'],
      lastEditorUsername: json['last_editor.username'],
      lastEditorEmailVerifiedAt: json['last_editor.email_verified_at'],
      lastEditorPassword: json['last_editor.password'],
      lastEditorMCompId: json['last_editor.m_comp_id'],
      lastEditorMDirId: json['last_editor.m_dir_id'],
      lastEditorIsActive: json['last_editor.is_active'],
      lastEditorCreatorId: json['last_editor.creator_id'],
      lastEditorLastEditorId: json['last_editor.last_editor_id'],
      lastEditorRememberToken: json['last_editor.remember_token'],
      lastEditorCreatedAt: json['last_editor.created_at'],
      lastEditorUpdatedAt: json['last_editor.updated_at'],
      lastEditorProfilImage: json['last_editor.profil_image'],
      lastEditorTelp: json['last_editor.telp'],
      lastEditorMKaryId: json['last_editor.m_kary_id'],
    );

Map<String, dynamic> _$$TRpdDetImplToJson(_$TRpdDetImpl instance) =>
    <String, dynamic>{
      'meta_read': instance.metaRead,
      'meta_delete': instance.metaDelete,
      'meta_update': instance.metaUpdate,
      'meta_create': instance.metaCreate,
      'id': instance.id,
      't_rpd_id': instance.tRpdId,
      't_spd_det_id': instance.tRpdDetTSpdDetId,
      'tipe_spd_id': instance.tRpdDetTipeSpdId,
      'biaya': instance.biaya,
      'biaya_realisasi': instance.biayaRealisasi,
      'detail_transport': instance.detailTransport,
      'm_knd_dinas_id': instance.tRpdDetMKndDinasId,
      'is_kendaraan_dinas': instance.isKendaraanDinas,
      'catatan_realisasi': instance.catatanRealisasi,
      'creator_id': instance.tRpdDetCreatorId,
      'last_editor_id': instance.tRpdDetLastEditorId,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      't_spd_det.id': instance.tSpdDetId,
      't_spd_det.t_spd_id': instance.tSpdDetTSpdId,
      't_spd_det.tipe_spd_id': instance.tSpdDetTipeSpdId,
      't_spd_det.biaya': instance.tSpdDetBiaya,
      't_spd_det.biaya_realisasi': instance.tSpdDetBiayaRealisasi,
      't_spd_det.detail_transport': instance.tSpdDetDetailTransport,
      't_spd_det.m_knd_dinas_id': instance.tSpdDetMKndDinasId,
      't_spd_det.is_kendaraan_dinas': instance.tSpdDetIsKendaraanDinas,
      't_spd_det.keterangan': instance.tSpdDetKeterangan,
      't_spd_det.catatan_realisasi': instance.tSpdDetCatatanRealisasi,
      't_spd_det.is_now': instance.tSpdDetIsNow,
      't_spd_det.creator_id': instance.tSpdDetCreatorId,
      't_spd_det.last_editor_id': instance.tSpdDetLastEditorId,
      't_spd_det.created_at': instance.tSpdDetCreatedAt,
      't_spd_det.updated_at': instance.tSpdDetUpdatedAt,
      'tipe_spd.id': instance.tipeSpdId,
      'tipe_spd.m_comp_id': instance.tipeSpdMCompId,
      'tipe_spd.m_dir_id': instance.tipeSpdMDirId,
      'tipe_spd.group': instance.tipeSpdGroup,
      'tipe_spd.key': instance.tipeSpdKey,
      'tipe_spd.code': instance.tipeSpdCode,
      'tipe_spd.value': instance.tipeSpdValue,
      'tipe_spd.is_active': instance.tipeSpdIsActive,
      'tipe_spd.creator_id': instance.tipeSpdCreatorId,
      'tipe_spd.last_editor_id': instance.tipeSpdLastEditorId,
      'tipe_spd.created_at': instance.tipeSpdCreatedAt,
      'tipe_spd.updated_at': instance.tipeSpdUpdatedAt,
      'tipe_spd.value_2': instance.tipeSpdValue2,
      'tipe_spd.value_3': instance.tipeSpdValue3,
      'm_knd_dinas.id': instance.mKndDinasId,
      'm_knd_dinas.m_comp_id': instance.mKndDinasMCompId,
      'm_knd_dinas.m_dir_id': instance.mKndDinasMDirId,
      'm_knd_dinas.nama': instance.mKndDinasNama,
      'm_knd_dinas.nopol': instance.mKndDinasNopol,
      'm_knd_dinas.m_lokasi_id': instance.mKndDinasMLokasiId,
      'm_knd_dinas.desc': instance.mKndDinasDesc,
      'm_knd_dinas.is_active': instance.mKndDinasIsActive,
      'm_knd_dinas.creator_id': instance.mKndDinasCreatorId,
      'm_knd_dinas.last_editor_id': instance.mKndDinasLastEditorId,
      'm_knd_dinas.created_at': instance.mKndDinasCreatedAt,
      'm_knd_dinas.updated_at': instance.mKndDinasUpdatedAt,
      'creator.id': instance.creatorId,
      'creator.name': instance.creatorName,
      'creator.email': instance.creatorEmail,
      'creator.username': instance.creatorUsername,
      'creator.email_verified_at': instance.creatorEmailVerifiedAt,
      'creator.password': instance.creatorPassword,
      'creator.m_comp_id': instance.creatorMCompId,
      'creator.m_dir_id': instance.creatorMDirId,
      'creator.is_active': instance.creatorIsActive,
      'creator.creator_id': instance.creatorCreatorId,
      'creator.last_editor_id': instance.creatorLastEditorId,
      'creator.remember_token': instance.creatorRememberToken,
      'creator.created_at': instance.creatorCreatedAt,
      'creator.updated_at': instance.creatorUpdatedAt,
      'creator.profil_image': instance.creatorProfilImage,
      'creator.telp': instance.creatorTelp,
      'creator.m_kary_id': instance.creatorMKaryId,
      'last_editor.id': instance.lastEditorId,
      'last_editor.name': instance.lastEditorName,
      'last_editor.email': instance.lastEditorEmail,
      'last_editor.username': instance.lastEditorUsername,
      'last_editor.email_verified_at': instance.lastEditorEmailVerifiedAt,
      'last_editor.password': instance.lastEditorPassword,
      'last_editor.m_comp_id': instance.lastEditorMCompId,
      'last_editor.m_dir_id': instance.lastEditorMDirId,
      'last_editor.is_active': instance.lastEditorIsActive,
      'last_editor.creator_id': instance.lastEditorCreatorId,
      'last_editor.last_editor_id': instance.lastEditorLastEditorId,
      'last_editor.remember_token': instance.lastEditorRememberToken,
      'last_editor.created_at': instance.lastEditorCreatedAt,
      'last_editor.updated_at': instance.lastEditorUpdatedAt,
      'last_editor.profil_image': instance.lastEditorProfilImage,
      'last_editor.telp': instance.lastEditorTelp,
      'last_editor.m_kary_id': instance.lastEditorMKaryId,
    };
