import 'package:freezed_annotation/freezed_annotation.dart';
import 'dart:convert';

part 'detail_realisasi_dinas_model.freezed.dart';
part 'detail_realisasi_dinas_model.g.dart';

@freezed
class DetailRealisasiDinasModel with _$DetailRealisasiDinasModel {
    const factory DetailRealisasiDinasModel({
        @JsonKey(name: "data")
        DetailRealisasiData? data,
        @JsonKey(name: "processed_time")
        double? processedTime,
    }) = _DetailRealisasiDinasModel;

    factory DetailRealisasiDinasModel.fromJson(Map<String, dynamic> json) => _$DetailRealisasiDinasModelFromJson(json);
}

@freezed
class DetailRealisasiData with _$DetailRealisasiData {
    const factory DetailRealisasiData({
        @JsonKey(name: "id")
        int? id,
        @JsonKey(name: "nomor")
        String? nomor,
        @JsonKey(name: "m_comp_id")
        int? dataMCompId,
        @JsonKey(name: "t_spd_id")
        int? dataTSpdId,
        @JsonKey(name: "total_biaya_spd")
        int? totalBiayaSpd,
        @JsonKey(name: "total_biaya_selisih")
        int? totalBiayaSelisih,
        @JsonKey(name: "pengambilan_spd")
        dynamic pengambilanSpd,
        @JsonKey(name: "keterangan")
        String? keterangan,
        @JsonKey(name: "status")
        String? status,
        @JsonKey(name: "creator_id")
        int? dataCreatorId,
        @JsonKey(name: "last_editor_id")
        int? dataLastEditorId,
        @JsonKey(name: "created_at")
        String? createdAt,
        @JsonKey(name: "updated_at")
        String? updatedAt,
        @JsonKey(name: "m_comp.id")
        int? mCompId,
        @JsonKey(name: "m_comp.nama")
        String? mCompNama,
        @JsonKey(name: "m_comp.is_active")
        bool? mCompIsActive,
        @JsonKey(name: "m_comp.desc")
        dynamic mCompDesc,
        @JsonKey(name: "m_comp.creator_id")
        dynamic mCompCreatorId,
        @JsonKey(name: "m_comp.last_editor_id")
        dynamic mCompLastEditorId,
        @JsonKey(name: "m_comp.created_at")
        dynamic mCompCreatedAt,
        @JsonKey(name: "m_comp.updated_at")
        dynamic mCompUpdatedAt,
        @JsonKey(name: "t_spd.id")
        int? tSpdId,
        @JsonKey(name: "t_spd.nomor")
        String? tSpdNomor,
        @JsonKey(name: "t_spd.m_comp_id")
        int? tSpdMCompId,
        @JsonKey(name: "t_spd.m_spd_id")
        int? tSpdMSpdId,
        @JsonKey(name: "t_spd.m_dir_id")
        int? tSpdMDirId,
        @JsonKey(name: "t_spd.m_divisi_id")
        int? tSpdMDivisiId,
        @JsonKey(name: "t_spd.m_dept_id")
        int? tSpdMDeptId,
        @JsonKey(name: "t_spd.m_posisi_id")
        int? tSpdMPosisiId,
        @JsonKey(name: "t_spd.tanggal")
        String? tSpdTanggal,
        @JsonKey(name: "t_spd.tgl_acara_awal")
        String? tSpdTglAcaraAwal,
        @JsonKey(name: "t_spd.tgl_acara_akhir")
        String? tSpdTglAcaraAkhir,
        @JsonKey(name: "t_spd.jenis_spd_id")
        int? tSpdJenisSpdId,
        @JsonKey(name: "t_spd.m_zona_asal_id")
        int? tSpdMZonaAsalId,
        @JsonKey(name: "t_spd.m_zona_tujuan_id")
        int? tSpdMZonaTujuanId,
        @JsonKey(name: "t_spd.m_lokasi_tujuan_id")
        int? tSpdMLokasiTujuanId,
        @JsonKey(name: "t_spd.m_kary_id")
        int? tSpdMKaryId,
        @JsonKey(name: "t_spd.pic_id")
        int? tSpdPicId,
        @JsonKey(name: "t_spd.total_biaya")
        String? tSpdTotalBiaya,
        @JsonKey(name: "t_spd.kegiatan")
        String? tSpdKegiatan,
        @JsonKey(name: "t_spd.keterangan")
        String? tSpdKeterangan,
        @JsonKey(name: "t_spd.status")
        String? tSpdStatus,
        @JsonKey(name: "t_spd.creator_id")
        int? tSpdCreatorId,
        @JsonKey(name: "t_spd.last_editor_id")
        dynamic tSpdLastEditorId,
        @JsonKey(name: "t_spd.created_at")
        String? tSpdCreatedAt,
        @JsonKey(name: "t_spd.updated_at")
        String? tSpdUpdatedAt,
        @JsonKey(name: "t_spd.is_kend_dinas")
        bool? tSpdIsKendDinas,
        @JsonKey(name: "creator.id")
        int? creatorId,
        @JsonKey(name: "creator.name")
        String? creatorName,
        @JsonKey(name: "creator.email")
        String? creatorEmail,
        @JsonKey(name: "creator.username")
        String? creatorUsername,
        @JsonKey(name: "creator.email_verified_at")
        dynamic creatorEmailVerifiedAt,
        @JsonKey(name: "creator.password")
        String? creatorPassword,
        @JsonKey(name: "creator.m_comp_id")
        int? creatorMCompId,
        @JsonKey(name: "creator.m_dir_id")
        int? creatorMDirId,
        @JsonKey(name: "creator.is_active")
        bool? creatorIsActive,
        @JsonKey(name: "creator.creator_id")
        int? creatorCreatorId,
        @JsonKey(name: "creator.last_editor_id")
        int? creatorLastEditorId,
        @JsonKey(name: "creator.remember_token")
        dynamic creatorRememberToken,
        @JsonKey(name: "creator.created_at")
        String? creatorCreatedAt,
        @JsonKey(name: "creator.updated_at")
        String? creatorUpdatedAt,
        @JsonKey(name: "creator.profil_image")
        String? creatorProfilImage,
        @JsonKey(name: "creator.telp")
        dynamic creatorTelp,
        @JsonKey(name: "creator.m_kary_id")
        int? creatorMKaryId,
        @JsonKey(name: "last_editor.id")
        int? lastEditorId,
        @JsonKey(name: "last_editor.name")
        String? lastEditorName,
        @JsonKey(name: "last_editor.email")
        String? lastEditorEmail,
        @JsonKey(name: "last_editor.username")
        String? lastEditorUsername,
        @JsonKey(name: "last_editor.email_verified_at")
        dynamic lastEditorEmailVerifiedAt,
        @JsonKey(name: "last_editor.password")
        String? lastEditorPassword,
        @JsonKey(name: "last_editor.m_comp_id")
        int? lastEditorMCompId,
        @JsonKey(name: "last_editor.m_dir_id")
        int? lastEditorMDirId,
        @JsonKey(name: "last_editor.is_active")
        bool? lastEditorIsActive,
        @JsonKey(name: "last_editor.creator_id")
        int? lastEditorCreatorId,
        @JsonKey(name: "last_editor.last_editor_id")
        int? lastEditorLastEditorId,
        @JsonKey(name: "last_editor.remember_token")
        dynamic lastEditorRememberToken,
        @JsonKey(name: "last_editor.created_at")
        String? lastEditorCreatedAt,
        @JsonKey(name: "last_editor.updated_at")
        String? lastEditorUpdatedAt,
        @JsonKey(name: "last_editor.profil_image")
        String? lastEditorProfilImage,
        @JsonKey(name: "last_editor.telp")
        dynamic lastEditorTelp,
        @JsonKey(name: "last_editor.m_kary_id")
        int? lastEditorMKaryId,
        @JsonKey(name: "t_rpd_det")
        List<TRpdDet>? tRpdDet,
    }) = _DetailRealisasiData;

    factory DetailRealisasiData.fromJson(Map<String, dynamic> json) => _$DetailRealisasiDataFromJson(json);
}

@freezed
class TRpdDet with _$TRpdDet {
    const factory TRpdDet({
        @JsonKey(name: "meta_read")
        bool? metaRead,
        @JsonKey(name: "meta_delete")
        bool? metaDelete,
        @JsonKey(name: "meta_update")
        bool? metaUpdate,
        @JsonKey(name: "meta_create")
        bool? metaCreate,
        @JsonKey(name: "id")
        int? id,
        @JsonKey(name: "t_rpd_id")
        int? tRpdId,
        @JsonKey(name: "t_spd_det_id")
        int? tRpdDetTSpdDetId,
        @JsonKey(name: "tipe_spd_id")
        int? tRpdDetTipeSpdId,
        @JsonKey(name: "biaya")
        int? biaya,
        @JsonKey(name: "biaya_realisasi")
        int? biayaRealisasi,
        @JsonKey(name: "detail_transport")
        dynamic detailTransport,
        @JsonKey(name: "m_knd_dinas_id")
        dynamic tRpdDetMKndDinasId,
        @JsonKey(name: "is_kendaraan_dinas")
        bool? isKendaraanDinas,
        @JsonKey(name: "catatan_realisasi")
        String? catatanRealisasi,
        @JsonKey(name: "creator_id")
        dynamic tRpdDetCreatorId,
        @JsonKey(name: "last_editor_id")
        dynamic tRpdDetLastEditorId,
        @JsonKey(name: "created_at")
        String? createdAt,
        @JsonKey(name: "updated_at")
        String? updatedAt,
        @JsonKey(name: "t_spd_det.id")
        int? tSpdDetId,
        @JsonKey(name: "t_spd_det.t_spd_id")
        int? tSpdDetTSpdId,
        @JsonKey(name: "t_spd_det.tipe_spd_id")
        int? tSpdDetTipeSpdId,
        @JsonKey(name: "t_spd_det.biaya")
        String? tSpdDetBiaya,
        @JsonKey(name: "t_spd_det.biaya_realisasi")
        dynamic tSpdDetBiayaRealisasi,
        @JsonKey(name: "t_spd_det.detail_transport")
        dynamic tSpdDetDetailTransport,
        @JsonKey(name: "t_spd_det.m_knd_dinas_id")
        dynamic tSpdDetMKndDinasId,
        @JsonKey(name: "t_spd_det.is_kendaraan_dinas")
        bool? tSpdDetIsKendaraanDinas,
        @JsonKey(name: "t_spd_det.keterangan")
        String? tSpdDetKeterangan,
        @JsonKey(name: "t_spd_det.catatan_realisasi")
        dynamic tSpdDetCatatanRealisasi,
        @JsonKey(name: "t_spd_det.is_now")
        dynamic tSpdDetIsNow,
        @JsonKey(name: "t_spd_det.creator_id")
        dynamic tSpdDetCreatorId,
        @JsonKey(name: "t_spd_det.last_editor_id")
        dynamic tSpdDetLastEditorId,
        @JsonKey(name: "t_spd_det.created_at")
        String? tSpdDetCreatedAt,
        @JsonKey(name: "t_spd_det.updated_at")
        String? tSpdDetUpdatedAt,
        @JsonKey(name: "tipe_spd.id")
        int? tipeSpdId,
        @JsonKey(name: "tipe_spd.m_comp_id")
        int? tipeSpdMCompId,
        @JsonKey(name: "tipe_spd.m_dir_id")
        dynamic tipeSpdMDirId,
        @JsonKey(name: "tipe_spd.group")
        String? tipeSpdGroup,
        @JsonKey(name: "tipe_spd.key")
        String? tipeSpdKey,
        @JsonKey(name: "tipe_spd.code")
        String? tipeSpdCode,
        @JsonKey(name: "tipe_spd.value")
        String? tipeSpdValue,
        @JsonKey(name: "tipe_spd.is_active")
        bool? tipeSpdIsActive,
        @JsonKey(name: "tipe_spd.creator_id")
        dynamic tipeSpdCreatorId,
        @JsonKey(name: "tipe_spd.last_editor_id")
        dynamic tipeSpdLastEditorId,
        @JsonKey(name: "tipe_spd.created_at")
        String? tipeSpdCreatedAt,
        @JsonKey(name: "tipe_spd.updated_at")
        String? tipeSpdUpdatedAt,
        @JsonKey(name: "tipe_spd.value_2")
        dynamic tipeSpdValue2,
        @JsonKey(name: "tipe_spd.value_3")
        dynamic tipeSpdValue3,
        @JsonKey(name: "m_knd_dinas.id")
        dynamic mKndDinasId,
        @JsonKey(name: "m_knd_dinas.m_comp_id")
        dynamic mKndDinasMCompId,
        @JsonKey(name: "m_knd_dinas.m_dir_id")
        dynamic mKndDinasMDirId,
        @JsonKey(name: "m_knd_dinas.nama")
        dynamic mKndDinasNama,
        @JsonKey(name: "m_knd_dinas.nopol")
        dynamic mKndDinasNopol,
        @JsonKey(name: "m_knd_dinas.m_lokasi_id")
        dynamic mKndDinasMLokasiId,
        @JsonKey(name: "m_knd_dinas.desc")
        dynamic mKndDinasDesc,
        @JsonKey(name: "m_knd_dinas.is_active")
        dynamic mKndDinasIsActive,
        @JsonKey(name: "m_knd_dinas.creator_id")
        dynamic mKndDinasCreatorId,
        @JsonKey(name: "m_knd_dinas.last_editor_id")
        dynamic mKndDinasLastEditorId,
        @JsonKey(name: "m_knd_dinas.created_at")
        dynamic mKndDinasCreatedAt,
        @JsonKey(name: "m_knd_dinas.updated_at")
        dynamic mKndDinasUpdatedAt,
        @JsonKey(name: "creator.id")
        dynamic creatorId,
        @JsonKey(name: "creator.name")
        dynamic creatorName,
        @JsonKey(name: "creator.email")
        dynamic creatorEmail,
        @JsonKey(name: "creator.username")
        dynamic creatorUsername,
        @JsonKey(name: "creator.email_verified_at")
        dynamic creatorEmailVerifiedAt,
        @JsonKey(name: "creator.password")
        dynamic creatorPassword,
        @JsonKey(name: "creator.m_comp_id")
        dynamic creatorMCompId,
        @JsonKey(name: "creator.m_dir_id")
        dynamic creatorMDirId,
        @JsonKey(name: "creator.is_active")
        dynamic creatorIsActive,
        @JsonKey(name: "creator.creator_id")
        dynamic creatorCreatorId,
        @JsonKey(name: "creator.last_editor_id")
        dynamic creatorLastEditorId,
        @JsonKey(name: "creator.remember_token")
        dynamic creatorRememberToken,
        @JsonKey(name: "creator.created_at")
        dynamic creatorCreatedAt,
        @JsonKey(name: "creator.updated_at")
        dynamic creatorUpdatedAt,
        @JsonKey(name: "creator.profil_image")
        dynamic creatorProfilImage,
        @JsonKey(name: "creator.telp")
        dynamic creatorTelp,
        @JsonKey(name: "creator.m_kary_id")
        dynamic creatorMKaryId,
        @JsonKey(name: "last_editor.id")
        dynamic lastEditorId,
        @JsonKey(name: "last_editor.name")
        dynamic lastEditorName,
        @JsonKey(name: "last_editor.email")
        dynamic lastEditorEmail,
        @JsonKey(name: "last_editor.username")
        dynamic lastEditorUsername,
        @JsonKey(name: "last_editor.email_verified_at")
        dynamic lastEditorEmailVerifiedAt,
        @JsonKey(name: "last_editor.password")
        dynamic lastEditorPassword,
        @JsonKey(name: "last_editor.m_comp_id")
        dynamic lastEditorMCompId,
        @JsonKey(name: "last_editor.m_dir_id")
        dynamic lastEditorMDirId,
        @JsonKey(name: "last_editor.is_active")
        dynamic lastEditorIsActive,
        @JsonKey(name: "last_editor.creator_id")
        dynamic lastEditorCreatorId,
        @JsonKey(name: "last_editor.last_editor_id")
        dynamic lastEditorLastEditorId,
        @JsonKey(name: "last_editor.remember_token")
        dynamic lastEditorRememberToken,
        @JsonKey(name: "last_editor.created_at")
        dynamic lastEditorCreatedAt,
        @JsonKey(name: "last_editor.updated_at")
        dynamic lastEditorUpdatedAt,
        @JsonKey(name: "last_editor.profil_image")
        dynamic lastEditorProfilImage,
        @JsonKey(name: "last_editor.telp")
        dynamic lastEditorTelp,
        @JsonKey(name: "last_editor.m_kary_id")
        dynamic lastEditorMKaryId,
    }) = _TRpdDet;

    factory TRpdDet.fromJson(Map<String, dynamic> json) => _$TRpdDetFromJson(json);
}
