// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'realisasi_dinas_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$RealisasiDinasModelImpl _$$RealisasiDinasModelImplFromJson(
        Map<String, dynamic> json) =>
    _$RealisasiDinasModelImpl(
      data: (json['data'] as List<dynamic>?)
          ?.map((e) => DataRealisasiDinas.fromJson(e as Map<String, dynamic>))
          .toList(),
      total: json['total'] as int?,
      currentPage: json['current_page'] as int?,
      perPage: json['per_page'] as int?,
      from: json['from'] as int?,
      to: json['to'] as int?,
      lastPage: json['last_page'] as int?,
      hasNext: json['has_next'] as bool?,
      prev: json['prev'],
      next: json['next'],
      processedTime: (json['processed_time'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$$RealisasiDinasModelImplToJson(
        _$RealisasiDinasModelImpl instance) =>
    <String, dynamic>{
      'data': instance.data,
      'total': instance.total,
      'current_page': instance.currentPage,
      'per_page': instance.perPage,
      'from': instance.from,
      'to': instance.to,
      'last_page': instance.lastPage,
      'has_next': instance.hasNext,
      'prev': instance.prev,
      'next': instance.next,
      'processed_time': instance.processedTime,
    };

_$DataRealisasiDinasImpl _$$DataRealisasiDinasImplFromJson(
        Map<String, dynamic> json) =>
    _$DataRealisasiDinasImpl(
      metaRead: json['meta_read'] as bool?,
      metaDelete: json['meta_delete'] as bool?,
      metaUpdate: json['meta_update'] as bool?,
      metaCreate: json['meta_create'] as bool?,
      id: json['id'] as int?,
      nomor: json['nomor'] as String?,
      datumMCompId: json['m_comp_id'] as int?,
      datumTSpdId: json['t_spd_id'] as int?,
      totalBiayaSpd: json['total_biaya_spd'] as int?,
      totalBiayaSelisih: json['total_biaya_selisih'] as int?,
      pengambilanSpd: json['pengambilan_spd'] as int?,
      keterangan: json['keterangan'] as String?,
      status: json['status'] as String?,
      datumCreatorId: json['creator_id'] as int?,
      datumLastEditorId: json['last_editor_id'] as int?,
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
      mCompId: json['m_comp.id'] as int?,
      mCompNama: json['m_comp.nama'] as String?,
      mCompIsActive: json['m_comp.is_active'] as bool?,
      mCompDesc: json['m_comp.desc'],
      mCompCreatorId: json['m_comp.creator_id'],
      mCompLastEditorId: json['m_comp.last_editor_id'],
      mCompCreatedAt: json['m_comp.created_at'],
      mCompUpdatedAt: json['m_comp.updated_at'],
      tSpdId: json['t_spd.id'] as int?,
      tSpdNomor: json['t_spd.nomor'] as String?,
      tSpdMCompId: json['t_spd.m_comp_id'] as int?,
      tSpdMSpdId: json['t_spd.m_spd_id'] as int?,
      tSpdMDirId: json['t_spd.m_dir_id'] as int?,
      tSpdMDivisiId: json['t_spd.m_divisi_id'] as int?,
      tSpdMDeptId: json['t_spd.m_dept_id'] as int?,
      tSpdMPosisiId: json['t_spd.m_posisi_id'] as int?,
      tSpdTanggal: json['t_spd.tanggal'] as String?,
      tSpdTglAcaraAwal: json['t_spd.tgl_acara_awal'] as String?,
      tSpdTglAcaraAkhir: json['t_spd.tgl_acara_akhir'] as String?,
      tSpdJenisSpdId: json['t_spd.jenis_spd_id'] as int?,
      tSpdMZonaAsalId: json['t_spd.m_zona_asal_id'] as int?,
      tSpdMZonaTujuanId: json['t_spd.m_zona_tujuan_id'] as int?,
      tSpdMLokasiTujuanId: json['t_spd.m_lokasi_tujuan_id'] as int?,
      tSpdMKaryId: json['t_spd.m_kary_id'] as int?,
      tSpdPicId: json['t_spd.pic_id'] as int?,
      tSpdTotalBiaya: json['t_spd.total_biaya'] as String?,
      tSpdKegiatan: json['t_spd.kegiatan'] as String?,
      tSpdKeterangan: json['t_spd.keterangan'] as String?,
      tSpdStatus: json['t_spd.status'] as String?,
      tSpdCreatorId: json['t_spd.creator_id'] as int?,
      tSpdLastEditorId: json['t_spd.last_editor_id'],
      tSpdCreatedAt: json['t_spd.created_at'] as String?,
      tSpdUpdatedAt: json['t_spd.updated_at'] as String?,
      tSpdIsKendDinas: json['t_spd.is_kend_dinas'] as bool?,
      creatorId: json['creator.id'] as int?,
      creatorName: json['creator.name'] as String?,
      creatorEmail: json['creator.email'] as String?,
      creatorUsername: json['creator.username'] as String?,
      creatorEmailVerifiedAt: json['creator.email_verified_at'],
      creatorPassword: json['creator.password'] as String?,
      creatorMCompId: json['creator.m_comp_id'] as int?,
      creatorMDirId: json['creator.m_dir_id'] as int?,
      creatorIsActive: json['creator.is_active'] as bool?,
      creatorCreatorId: json['creator.creator_id'] as int?,
      creatorLastEditorId: json['creator.last_editor_id'] as int?,
      creatorRememberToken: json['creator.remember_token'],
      creatorCreatedAt: json['creator.created_at'] as String?,
      creatorUpdatedAt: json['creator.updated_at'] as String?,
      creatorProfilImage: json['creator.profil_image'] as String?,
      creatorTelp: json['creator.telp'],
      creatorMKaryId: json['creator.m_kary_id'] as int?,
      lastEditorId: json['last_editor.id'] as int?,
      lastEditorName: json['last_editor.name'] as String?,
      lastEditorEmail: json['last_editor.email'] as String?,
      lastEditorUsername: json['last_editor.username'] as String?,
      lastEditorEmailVerifiedAt: json['last_editor.email_verified_at'],
      lastEditorPassword: json['last_editor.password'] as String?,
      lastEditorMCompId: json['last_editor.m_comp_id'] as int?,
      lastEditorMDirId: json['last_editor.m_dir_id'] as int?,
      lastEditorIsActive: json['last_editor.is_active'] as bool?,
      lastEditorCreatorId: json['last_editor.creator_id'] as int?,
      lastEditorLastEditorId: json['last_editor.last_editor_id'] as int?,
      lastEditorRememberToken: json['last_editor.remember_token'],
      lastEditorCreatedAt: json['last_editor.created_at'] as String?,
      lastEditorUpdatedAt: json['last_editor.updated_at'] as String?,
      lastEditorProfilImage: json['last_editor.profil_image'] as String?,
      lastEditorTelp: json['last_editor.telp'],
      lastEditorMKaryId: json['last_editor.m_kary_id'] as int?,
      approvalNote: json['approval_note'] as String?,
    );

Map<String, dynamic> _$$DataRealisasiDinasImplToJson(
        _$DataRealisasiDinasImpl instance) =>
    <String, dynamic>{
      'meta_read': instance.metaRead,
      'meta_delete': instance.metaDelete,
      'meta_update': instance.metaUpdate,
      'meta_create': instance.metaCreate,
      'id': instance.id,
      'nomor': instance.nomor,
      'm_comp_id': instance.datumMCompId,
      't_spd_id': instance.datumTSpdId,
      'total_biaya_spd': instance.totalBiayaSpd,
      'total_biaya_selisih': instance.totalBiayaSelisih,
      'pengambilan_spd': instance.pengambilanSpd,
      'keterangan': instance.keterangan,
      'status': instance.status,
      'creator_id': instance.datumCreatorId,
      'last_editor_id': instance.datumLastEditorId,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      'm_comp.id': instance.mCompId,
      'm_comp.nama': instance.mCompNama,
      'm_comp.is_active': instance.mCompIsActive,
      'm_comp.desc': instance.mCompDesc,
      'm_comp.creator_id': instance.mCompCreatorId,
      'm_comp.last_editor_id': instance.mCompLastEditorId,
      'm_comp.created_at': instance.mCompCreatedAt,
      'm_comp.updated_at': instance.mCompUpdatedAt,
      't_spd.id': instance.tSpdId,
      't_spd.nomor': instance.tSpdNomor,
      't_spd.m_comp_id': instance.tSpdMCompId,
      't_spd.m_spd_id': instance.tSpdMSpdId,
      't_spd.m_dir_id': instance.tSpdMDirId,
      't_spd.m_divisi_id': instance.tSpdMDivisiId,
      't_spd.m_dept_id': instance.tSpdMDeptId,
      't_spd.m_posisi_id': instance.tSpdMPosisiId,
      't_spd.tanggal': instance.tSpdTanggal,
      't_spd.tgl_acara_awal': instance.tSpdTglAcaraAwal,
      't_spd.tgl_acara_akhir': instance.tSpdTglAcaraAkhir,
      't_spd.jenis_spd_id': instance.tSpdJenisSpdId,
      't_spd.m_zona_asal_id': instance.tSpdMZonaAsalId,
      't_spd.m_zona_tujuan_id': instance.tSpdMZonaTujuanId,
      't_spd.m_lokasi_tujuan_id': instance.tSpdMLokasiTujuanId,
      't_spd.m_kary_id': instance.tSpdMKaryId,
      't_spd.pic_id': instance.tSpdPicId,
      't_spd.total_biaya': instance.tSpdTotalBiaya,
      't_spd.kegiatan': instance.tSpdKegiatan,
      't_spd.keterangan': instance.tSpdKeterangan,
      't_spd.status': instance.tSpdStatus,
      't_spd.creator_id': instance.tSpdCreatorId,
      't_spd.last_editor_id': instance.tSpdLastEditorId,
      't_spd.created_at': instance.tSpdCreatedAt,
      't_spd.updated_at': instance.tSpdUpdatedAt,
      't_spd.is_kend_dinas': instance.tSpdIsKendDinas,
      'creator.id': instance.creatorId,
      'creator.name': instance.creatorName,
      'creator.email': instance.creatorEmail,
      'creator.username': instance.creatorUsername,
      'creator.email_verified_at': instance.creatorEmailVerifiedAt,
      'creator.password': instance.creatorPassword,
      'creator.m_comp_id': instance.creatorMCompId,
      'creator.m_dir_id': instance.creatorMDirId,
      'creator.is_active': instance.creatorIsActive,
      'creator.creator_id': instance.creatorCreatorId,
      'creator.last_editor_id': instance.creatorLastEditorId,
      'creator.remember_token': instance.creatorRememberToken,
      'creator.created_at': instance.creatorCreatedAt,
      'creator.updated_at': instance.creatorUpdatedAt,
      'creator.profil_image': instance.creatorProfilImage,
      'creator.telp': instance.creatorTelp,
      'creator.m_kary_id': instance.creatorMKaryId,
      'last_editor.id': instance.lastEditorId,
      'last_editor.name': instance.lastEditorName,
      'last_editor.email': instance.lastEditorEmail,
      'last_editor.username': instance.lastEditorUsername,
      'last_editor.email_verified_at': instance.lastEditorEmailVerifiedAt,
      'last_editor.password': instance.lastEditorPassword,
      'last_editor.m_comp_id': instance.lastEditorMCompId,
      'last_editor.m_dir_id': instance.lastEditorMDirId,
      'last_editor.is_active': instance.lastEditorIsActive,
      'last_editor.creator_id': instance.lastEditorCreatorId,
      'last_editor.last_editor_id': instance.lastEditorLastEditorId,
      'last_editor.remember_token': instance.lastEditorRememberToken,
      'last_editor.created_at': instance.lastEditorCreatedAt,
      'last_editor.updated_at': instance.lastEditorUpdatedAt,
      'last_editor.profil_image': instance.lastEditorProfilImage,
      'last_editor.telp': instance.lastEditorTelp,
      'last_editor.m_kary_id': instance.lastEditorMKaryId,
      'approval_note': instance.approvalNote,
    };
