import 'package:freezed_annotation/freezed_annotation.dart';
import 'dart:convert';

part 'response_detail_spd.freezed.dart';
part 'response_detail_spd.g.dart';

@freezed
class ResponseDetailSpd with _$ResponseDetailSpd {
    const factory ResponseDetailSpd({
        @JsonKey(name: "data")
        DataDetailDinas? data,
        @JsonKey(name: "processed_time")
        double? processedTime,
    }) = _ResponseDetailSpd;

    factory ResponseDetailSpd.fromJson(Map<String, dynamic> json) => _$ResponseDetailSpdFromJson(json);
}

@freezed
class DataDetailDinas with _$DataDetailDinas {
    const factory DataDetailDinas({
                @JsonKey(name: "id")
        int? id,
        @JsonKey(name: "nomor")
        String? nomor,
        @JsonKey(name: "m_comp_id")
        int? dataMCompId,
        @JsonKey(name: "m_spd_id")
        int? dataMSpdId,
        @JsonKey(name: "m_dir_id")
        int? dataMDirId,
        @JsonKey(name: "m_divisi_id")
        int? dataMDivisiId,
        @JsonKey(name: "m_dept_id")
        int? dataMDeptId,
        @JsonKey(name: "m_posisi_id")
        int? dataMPosisiId,
        @JsonKey(name: "tanggal")
        String? tanggal,
        @JsonKey(name: "tgl_acara_awal")
        String? tglAcaraAwal,
        @JsonKey(name: "tgl_acara_akhir")
        String? tglAcaraAkhir,
        @JsonKey(name: "jenis_spd_id")
        int? dataJenisSpdId,
        @JsonKey(name: "m_zona_asal_id")
        int? dataMZonaAsalId,
        @JsonKey(name: "m_zona_tujuan_id")
        int? dataMZonaTujuanId,
        @JsonKey(name: "m_lokasi_tujuan_id")
        int? dataMLokasiTujuanId,
        @JsonKey(name: "m_kary_id")
        int? dataMKaryId,
        @JsonKey(name: "pic_id")
        int? dataPicId,
        @JsonKey(name: "total_biaya")
        int? totalBiaya,
        @JsonKey(name: "kegiatan")
        dynamic kegiatan,
        @JsonKey(name: "keterangan")
        dynamic keterangan,
        @JsonKey(name: "status")
        String? status,
        @JsonKey(name: "creator_id")
        int? dataCreatorId,
        @JsonKey(name: "last_editor_id")
        dynamic dataLastEditorId,
        @JsonKey(name: "created_at")
        String? createdAt,
        @JsonKey(name: "updated_at")
        String? updatedAt,
        @JsonKey(name: "is_kend_dinas")
        bool? isKendDinas,
        @JsonKey(name: "interval")
        int? interval,
        @JsonKey(name: "catatan_kend")
        String? catatanKend,
        @JsonKey(name: "m_comp.id")
        int? mCompId,
        @JsonKey(name: "m_comp.nama")
        String? mCompNama,
        @JsonKey(name: "m_comp.is_active")
        bool? mCompIsActive,
        @JsonKey(name: "m_comp.desc")
        dynamic mCompDesc,
        @JsonKey(name: "m_comp.creator_id")
        dynamic mCompCreatorId,
        @JsonKey(name: "m_comp.last_editor_id")
        dynamic mCompLastEditorId,
        @JsonKey(name: "m_comp.created_at")
        dynamic mCompCreatedAt,
        @JsonKey(name: "m_comp.updated_at")
        dynamic mCompUpdatedAt,
        @JsonKey(name: "m_spd.id")
        int? mSpdId,
        @JsonKey(name: "m_spd.m_comp_id")
        int? mSpdMCompId,
        @JsonKey(name: "m_spd.m_dir_id")
        int? mSpdMDirId,
        @JsonKey(name: "m_spd.kode")
        String? mSpdKode,
        @JsonKey(name: "m_spd.m_divisi_id")
        int? mSpdMDivisiId,
        @JsonKey(name: "m_spd.m_posisi_id")
        int? mSpdMPosisiId,
        @JsonKey(name: "m_spd.m_dept_id")
        int? mSpdMDeptId,
        @JsonKey(name: "m_spd.m_zona_id")
        int? mSpdMZonaId,
        @JsonKey(name: "m_spd.grading_id")
        dynamic mSpdGradingId,
        @JsonKey(name: "m_spd.grading")
        dynamic mSpdGrading,
        @JsonKey(name: "m_spd.desc")
        String? mSpdDesc,
        @JsonKey(name: "m_spd.is_active")
        bool? mSpdIsActive,
        @JsonKey(name: "m_spd.creator_id")
        dynamic mSpdCreatorId,
        @JsonKey(name: "m_spd.last_editor_id")
        dynamic mSpdLastEditorId,
        @JsonKey(name: "m_spd.created_at")
        String? mSpdCreatedAt,
        @JsonKey(name: "m_spd.updated_at")
        String? mSpdUpdatedAt,
        @JsonKey(name: "m_dir.id")
        dynamic mDirId,
        @JsonKey(name: "m_dir.m_comp_id")
        dynamic mDirMCompId,
        @JsonKey(name: "m_dir.nama")
        dynamic mDirNama,
        @JsonKey(name: "m_dir.desc")
        dynamic mDirDesc,
        @JsonKey(name: "m_dir.is_active")
        dynamic mDirIsActive,
        @JsonKey(name: "m_dir.creator_id")
        dynamic mDirCreatorId,
        @JsonKey(name: "m_dir.last_editor_id")
        dynamic mDirLastEditorId,
        @JsonKey(name: "m_dir.created_at")
        dynamic mDirCreatedAt,
        @JsonKey(name: "m_dir.updated_at")
        dynamic mDirUpdatedAt,
        @JsonKey(name: "m_divisi.id")
        int? mDivisiId,
        @JsonKey(name: "m_divisi.m_comp_id")
        int? mDivisiMCompId,
        @JsonKey(name: "m_divisi.m_dir_id")
        int? mDivisiMDirId,
        @JsonKey(name: "m_divisi.nama")
        String? mDivisiNama,
        @JsonKey(name: "m_divisi.desc")
        dynamic mDivisiDesc,
        @JsonKey(name: "m_divisi.is_active")
        bool? mDivisiIsActive,
        @JsonKey(name: "m_divisi.creator_id")
        dynamic mDivisiCreatorId,
        @JsonKey(name: "m_divisi.last_editor_id")
        dynamic mDivisiLastEditorId,
        @JsonKey(name: "m_divisi.created_at")
        dynamic mDivisiCreatedAt,
        @JsonKey(name: "m_divisi.updated_at")
        dynamic mDivisiUpdatedAt,
        @JsonKey(name: "m_dept.id")
        int? mDeptId,
        @JsonKey(name: "m_dept.m_dir_id")
        int? mDeptMDirId,
        @JsonKey(name: "m_dept.m_divisi_id")
        int? mDeptMDivisiId,
        @JsonKey(name: "m_dept.nama")
        String? mDeptNama,
        @JsonKey(name: "m_dept.desc")
        dynamic mDeptDesc,
        @JsonKey(name: "m_dept.is_active")
        bool? mDeptIsActive,
        @JsonKey(name: "m_dept.creator_id")
        dynamic mDeptCreatorId,
        @JsonKey(name: "m_dept.last_editor_id")
        dynamic mDeptLastEditorId,
        @JsonKey(name: "m_dept.created_at")
        dynamic mDeptCreatedAt,
        @JsonKey(name: "m_dept.updated_at")
        dynamic mDeptUpdatedAt,
        @JsonKey(name: "m_posisi.id")
        int? mPosisiId,
        @JsonKey(name: "m_posisi.m_comp_id")
        int? mPosisiMCompId,
        @JsonKey(name: "m_posisi.m_dir_id")
        int? mPosisiMDirId,
        @JsonKey(name: "m_posisi.kode")
        String? mPosisiKode,
        @JsonKey(name: "m_posisi.desc_kerja")
        String? mPosisiDescKerja,
        @JsonKey(name: "m_posisi.desc_kerja_1")
        String? mPosisiDescKerja1,
        @JsonKey(name: "m_posisi.desc_kerja_2")
        String? mPosisiDescKerja2,
        @JsonKey(name: "m_posisi.min_pengalaman")
        String? mPosisiMinPengalaman,
        @JsonKey(name: "m_posisi.min_pendidikan_id")
        int? mPosisiMinPendidikanId,
        @JsonKey(name: "m_posisi.min_gaji_pokok")
        String? mPosisiMinGajiPokok,
        @JsonKey(name: "m_posisi.max_gaji_pokok")
        String? mPosisiMaxGajiPokok,
        @JsonKey(name: "m_posisi.biaya")
        dynamic mPosisiBiaya,
        @JsonKey(name: "m_posisi.tipe_bpjs_id")
        int? mPosisiTipeBpjsId,
        @JsonKey(name: "m_posisi.potongan_bpjs")
        String? mPosisiPotonganBpjs,
        @JsonKey(name: "m_posisi.desc")
        dynamic mPosisiDesc,
        @JsonKey(name: "m_posisi.is_active")
        bool? mPosisiIsActive,
        @JsonKey(name: "m_posisi.creator_id")
        dynamic mPosisiCreatorId,
        @JsonKey(name: "m_posisi.last_editor_id")
        dynamic mPosisiLastEditorId,
        @JsonKey(name: "m_posisi.created_at")
        String? mPosisiCreatedAt,
        @JsonKey(name: "m_posisi.updated_at")
        String? mPosisiUpdatedAt,
        @JsonKey(name: "jenis_spd.id")
        int? jenisSpdId,
        @JsonKey(name: "jenis_spd.m_comp_id")
        int? jenisSpdMCompId,
        @JsonKey(name: "jenis_spd.m_dir_id")
        dynamic jenisSpdMDirId,
        @JsonKey(name: "jenis_spd.group")
        String? jenisSpdGroup,
        @JsonKey(name: "jenis_spd.key")
        String? jenisSpdKey,
        @JsonKey(name: "jenis_spd.code")
        String? jenisSpdCode,
        @JsonKey(name: "jenis_spd.value")
        String? jenisSpdValue,
        @JsonKey(name: "jenis_spd.is_active")
        bool? jenisSpdIsActive,
        @JsonKey(name: "jenis_spd.creator_id")
        dynamic jenisSpdCreatorId,
        @JsonKey(name: "jenis_spd.last_editor_id")
        dynamic jenisSpdLastEditorId,
        @JsonKey(name: "jenis_spd.created_at")
        dynamic jenisSpdCreatedAt,
        @JsonKey(name: "jenis_spd.updated_at")
        dynamic jenisSpdUpdatedAt,
        @JsonKey(name: "jenis_spd.value_2")
        dynamic jenisSpdValue2,
        @JsonKey(name: "jenis_spd.value_3")
        dynamic jenisSpdValue3,
        @JsonKey(name: "m_zona_asal.id")
        int? mZonaAsalId,
        @JsonKey(name: "m_zona_asal.m_comp_id")
        int? mZonaAsalMCompId,
        @JsonKey(name: "m_zona_asal.m_dir_id")
        int? mZonaAsalMDirId,
        @JsonKey(name: "m_zona_asal.kode")
        String? mZonaAsalKode,
        @JsonKey(name: "m_zona_asal.nama")
        String? mZonaAsalNama,
        @JsonKey(name: "m_zona_asal.desc")
        String? mZonaAsalDesc,
        @JsonKey(name: "m_zona_asal.is_active")
        bool? mZonaAsalIsActive,
        @JsonKey(name: "m_zona_asal.creator_id")
        dynamic mZonaAsalCreatorId,
        @JsonKey(name: "m_zona_asal.last_editor_id")
        dynamic mZonaAsalLastEditorId,
        @JsonKey(name: "m_zona_asal.created_at")
        String? mZonaAsalCreatedAt,
        @JsonKey(name: "m_zona_asal.updated_at")
        String? mZonaAsalUpdatedAt,
        @JsonKey(name: "m_zona_tujuan.id")
        int? mZonaTujuanId,
        @JsonKey(name: "m_zona_tujuan.m_comp_id")
        int? mZonaTujuanMCompId,
        @JsonKey(name: "m_zona_tujuan.m_dir_id")
        int? mZonaTujuanMDirId,
        @JsonKey(name: "m_zona_tujuan.kode")
        String? mZonaTujuanKode,
        @JsonKey(name: "m_zona_tujuan.nama")
        String? mZonaTujuanNama,
        @JsonKey(name: "m_zona_tujuan.desc")
        String? mZonaTujuanDesc,
        @JsonKey(name: "m_zona_tujuan.is_active")
        bool? mZonaTujuanIsActive,
        @JsonKey(name: "m_zona_tujuan.creator_id")
        dynamic mZonaTujuanCreatorId,
        @JsonKey(name: "m_zona_tujuan.last_editor_id")
        dynamic mZonaTujuanLastEditorId,
        @JsonKey(name: "m_zona_tujuan.created_at")
        String? mZonaTujuanCreatedAt,
        @JsonKey(name: "m_zona_tujuan.updated_at")
        String? mZonaTujuanUpdatedAt,
        @JsonKey(name: "m_lokasi_tujuan.id")
        int? mLokasiTujuanId,
        @JsonKey(name: "m_lokasi_tujuan.m_comp_id")
        int? mLokasiTujuanMCompId,
        @JsonKey(name: "m_lokasi_tujuan.m_dir_id")
        int? mLokasiTujuanMDirId,
        @JsonKey(name: "m_lokasi_tujuan.kode")
        String? mLokasiTujuanKode,
        @JsonKey(name: "m_lokasi_tujuan.nama")
        String? mLokasiTujuanNama,
        @JsonKey(name: "m_lokasi_tujuan.desc")
        String? mLokasiTujuanDesc,
        @JsonKey(name: "m_lokasi_tujuan.is_active")
        bool? mLokasiTujuanIsActive,
        @JsonKey(name: "m_lokasi_tujuan.creator_id")
        dynamic mLokasiTujuanCreatorId,
        @JsonKey(name: "m_lokasi_tujuan.last_editor_id")
        dynamic mLokasiTujuanLastEditorId,
        @JsonKey(name: "m_lokasi_tujuan.created_at")
        String? mLokasiTujuanCreatedAt,
        @JsonKey(name: "m_lokasi_tujuan.updated_at")
        String? mLokasiTujuanUpdatedAt,
        @JsonKey(name: "m_kary.id")
        int? mKaryId,
        @JsonKey(name: "m_kary.m_comp_id")
        int? mKaryMCompId,
        @JsonKey(name: "m_kary.m_dir_id")
        int? mKaryMDirId,
        @JsonKey(name: "m_kary.m_divisi_id")
        int? mKaryMDivisiId,
        @JsonKey(name: "m_kary.m_dept_id")
        int? mKaryMDeptId,
        @JsonKey(name: "m_kary.m_zona_id")
        int? mKaryMZonaId,
        @JsonKey(name: "m_kary.grading_id")
        dynamic mKaryGradingId,
        @JsonKey(name: "m_kary.costcontre_id")
        int? mKaryCostcontreId,
        @JsonKey(name: "m_kary.kode")
        String? mKaryKode,
        @JsonKey(name: "m_kary.m_posisi_id")
        int? mKaryMPosisiId,
        @JsonKey(name: "m_kary.m_jam_kerja_id")
        int? mKaryMJamKerjaId,
        @JsonKey(name: "m_kary.kode_presensi")
        String? mKaryKodePresensi,
        @JsonKey(name: "m_kary.nik")
        String? mKaryNik,
        @JsonKey(name: "m_kary.nama_depan")
        String? mKaryNamaDepan,
        @JsonKey(name: "m_kary.nama_belakang")
        String? mKaryNamaBelakang,
        @JsonKey(name: "m_kary.nama_lengkap")
        String? mKaryNamaLengkap,
        @JsonKey(name: "m_kary.nama_panggilan")
        String? mKaryNamaPanggilan,
        @JsonKey(name: "m_kary.jk_id")
        int? mKaryJkId,
        @JsonKey(name: "m_kary.tempat_lahir")
        String? mKaryTempatLahir,
        @JsonKey(name: "m_kary.tgl_lahir")
        String? mKaryTglLahir,
        @JsonKey(name: "m_kary.provinsi_id")
        int? mKaryProvinsiId,
        @JsonKey(name: "m_kary.kota_id")
        int? mKaryKotaId,
        @JsonKey(name: "m_kary.kecamatan_id")
        int? mKaryKecamatanId,
        @JsonKey(name: "m_kary.kode_pos")
        String? mKaryKodePos,
        @JsonKey(name: "m_kary.alamat_asli")
        String? mKaryAlamatAsli,
        @JsonKey(name: "m_kary.alamat_domisili")
        String? mKaryAlamatDomisili,
        @JsonKey(name: "m_kary.no_tlp")
        String? mKaryNoTlp,
        @JsonKey(name: "m_kary.no_tlp_lainnya")
        String? mKaryNoTlpLainnya,
        @JsonKey(name: "m_kary.no_darurat")
        String? mKaryNoDarurat,
        @JsonKey(name: "m_kary.nama_kontak_darurat")
        String? mKaryNamaKontakDarurat,
        @JsonKey(name: "m_kary.agama_id")
        int? mKaryAgamaId,
        @JsonKey(name: "m_kary.gol_darah_id")
        int? mKaryGolDarahId,
        @JsonKey(name: "m_kary.status_nikah_id")
        int? mKaryStatusNikahId,
        @JsonKey(name: "m_kary.tanggungan_id")
        int? mKaryTanggunganId,
        @JsonKey(name: "m_kary.hub_dgn_karyawan")
        String? mKaryHubDgnKaryawan,
        @JsonKey(name: "m_kary.cuti_jatah_reguler")
        int? mKaryCutiJatahReguler,
        @JsonKey(name: "m_kary.cuti_sisa_reguler")
        int? mKaryCutiSisaReguler,
        @JsonKey(name: "m_kary.cuti_panjang")
        int? mKaryCutiPanjang,
        @JsonKey(name: "m_kary.cuti_sisa_panjang")
        int? mKaryCutiSisaPanjang,
        @JsonKey(name: "m_kary.status_kary_id")
        dynamic mKaryStatusKaryId,
        @JsonKey(name: "m_kary.lama_kontrak_awal")
        dynamic mKaryLamaKontrakAwal,
        @JsonKey(name: "m_kary.lama_kontrak_akhir")
        dynamic mKaryLamaKontrakAkhir,
        @JsonKey(name: "m_kary.tgl_masuk")
        String? mKaryTglMasuk,
        @JsonKey(name: "m_kary.tgl_berhenti")
        dynamic mKaryTglBerhenti,
        @JsonKey(name: "m_kary.alasan_berhenti")
        dynamic mKaryAlasanBerhenti,
        @JsonKey(name: "m_kary.uk_baju")
        String? mKaryUkBaju,
        @JsonKey(name: "m_kary.uk_celana")
        String? mKaryUkCelana,
        @JsonKey(name: "m_kary.uk_sepatu")
        String? mKaryUkSepatu,
        @JsonKey(name: "m_kary.desc")
        String? mKaryDesc,
        @JsonKey(name: "m_kary.is_active")
        bool? mKaryIsActive,
        @JsonKey(name: "m_kary.creator_id")
        dynamic mKaryCreatorId,
        @JsonKey(name: "m_kary.last_editor_id")
        int? mKaryLastEditorId,
        @JsonKey(name: "m_kary.created_at")
        String? mKaryCreatedAt,
        @JsonKey(name: "m_kary.updated_at")
        String? mKaryUpdatedAt,
        @JsonKey(name: "m_kary.m_standart_gaji_id")
        int? mKaryMStandartGajiId,
        @JsonKey(name: "m_kary.periode_gaji_id")
        int? mKaryPeriodeGajiId,
        @JsonKey(name: "m_kary.ref_id")
        dynamic mKaryRefId,
        @JsonKey(name: "m_kary.presensi_lokasi_default_id")
        dynamic mKaryPresensiLokasiDefaultId,
        @JsonKey(name: "m_kary.exp_date_cuti")
        dynamic mKaryExpDateCuti,
        @JsonKey(name: "m_kary.limit_potong")
        int? mKaryLimitPotong,
        @JsonKey(name: "m_kary.atasan_id")
        int? mKaryAtasanId,
        @JsonKey(name: "m_kary.cuti_p24")
        dynamic mKaryCutiP24,
        @JsonKey(name: "m_kary.cuti_sisa_p24")
        dynamic mKaryCutiSisaP24,
        @JsonKey(name: "pic.id")
        int? picId,
        @JsonKey(name: "pic.name")
        String? picName,
        @JsonKey(name: "pic.email")
        String? picEmail,
        @JsonKey(name: "pic.username")
        String? picUsername,
        @JsonKey(name: "pic.email_verified_at")
        dynamic picEmailVerifiedAt,
        @JsonKey(name: "pic.password")
        String? picPassword,
        @JsonKey(name: "pic.m_comp_id")
        int? picMCompId,
        @JsonKey(name: "pic.m_dir_id")
        int? picMDirId,
        @JsonKey(name: "pic.is_active")
        bool? picIsActive,
        @JsonKey(name: "pic.creator_id")
        dynamic picCreatorId,
        @JsonKey(name: "pic.last_editor_id")
        int? picLastEditorId,
        @JsonKey(name: "pic.remember_token")
        dynamic picRememberToken,
        @JsonKey(name: "pic.created_at")
        dynamic picCreatedAt,
        @JsonKey(name: "pic.updated_at")
        String? picUpdatedAt,
        @JsonKey(name: "pic.profil_image")
        String? picProfilImage,
        @JsonKey(name: "pic.telp")
        String? picTelp,
        @JsonKey(name: "pic.m_kary_id")
        int? picMKaryId,
        @JsonKey(name: "creator.id")
        int? creatorId,
        @JsonKey(name: "creator.name")
        String? creatorName,
        @JsonKey(name: "creator.email")
        String? creatorEmail,
        @JsonKey(name: "creator.username")
        String? creatorUsername,
        @JsonKey(name: "creator.email_verified_at")
        dynamic creatorEmailVerifiedAt,
        @JsonKey(name: "creator.password")
        String? creatorPassword,
        @JsonKey(name: "creator.m_comp_id")
        int? creatorMCompId,
        @JsonKey(name: "creator.m_dir_id")
        int? creatorMDirId,
        @JsonKey(name: "creator.is_active")
        bool? creatorIsActive,
        @JsonKey(name: "creator.creator_id")
        dynamic creatorCreatorId,
        @JsonKey(name: "creator.last_editor_id")
        int? creatorLastEditorId,
        @JsonKey(name: "creator.remember_token")
        dynamic creatorRememberToken,
        @JsonKey(name: "creator.created_at")
        dynamic creatorCreatedAt,
        @JsonKey(name: "creator.updated_at")
        String? creatorUpdatedAt,
        @JsonKey(name: "creator.profil_image")
        String? creatorProfilImage,
        @JsonKey(name: "creator.telp")
        String? creatorTelp,
        @JsonKey(name: "creator.m_kary_id")
        int? creatorMKaryId,
        @JsonKey(name: "last_editor.id")
        dynamic lastEditorId,
        @JsonKey(name: "last_editor.name")
        dynamic lastEditorName,
        @JsonKey(name: "last_editor.email")
        dynamic lastEditorEmail,
        @JsonKey(name: "last_editor.username")
        dynamic lastEditorUsername,
        @JsonKey(name: "last_editor.email_verified_at")
        dynamic lastEditorEmailVerifiedAt,
        @JsonKey(name: "last_editor.password")
        dynamic lastEditorPassword,
        @JsonKey(name: "last_editor.m_comp_id")
        dynamic lastEditorMCompId,
        @JsonKey(name: "last_editor.m_dir_id")
        dynamic lastEditorMDirId,
        @JsonKey(name: "last_editor.is_active")
        dynamic lastEditorIsActive,
        @JsonKey(name: "last_editor.creator_id")
        dynamic lastEditorCreatorId,
        @JsonKey(name: "last_editor.last_editor_id")
        dynamic lastEditorLastEditorId,
        @JsonKey(name: "last_editor.remember_token")
        dynamic lastEditorRememberToken,
        @JsonKey(name: "last_editor.created_at")
        dynamic lastEditorCreatedAt,
        @JsonKey(name: "last_editor.updated_at")
        dynamic lastEditorUpdatedAt,
        @JsonKey(name: "last_editor.profil_image")
        dynamic lastEditorProfilImage,
        @JsonKey(name: "last_editor.telp")
        dynamic lastEditorTelp,
        @JsonKey(name: "last_editor.m_kary_id")
        dynamic lastEditorMKaryId,
        @JsonKey(name: "pic.nama_lengkap")
        String? picNamaLengkap,
        @JsonKey(name: "approval_note")
        String? approvalNote,
        @JsonKey(name: "nama_pic")
        String? namaPic,
        @JsonKey(name: "det_biaya")
        List<DetBiaya>? detBiaya,
        @JsonKey(name: "t_spd_det")
        List<dynamic>? tSpdDet,
    }) = _DataDetailDinas;

    factory DataDetailDinas.fromJson(Map<String, dynamic> json) => _$DataDetailDinasFromJson(json);
}

@freezed
class DetBiaya with _$DetBiaya {
    const factory DetBiaya({
        @JsonKey(name: "total_biaya")
        String? totalBiaya,
        @JsonKey(name: "tipe_id")
        int? tipeId,
        @JsonKey(name: "keterangan")
        String? keterangan,
        @JsonKey(name: "tipe_value")
        String? tipeValue,
    }) = _DetBiaya;

    factory DetBiaya.fromJson(Map<String, dynamic> json) => _$DetBiayaFromJson(json);
}