import 'package:freezed_annotation/freezed_annotation.dart';
import 'dart:convert';

part 'history_attendance_model.freezed.dart';
part 'history_attendance_model.g.dart';

@freezed
class HistoryAttendanceModel with _$HistoryAttendanceModel {
    const factory HistoryAttendanceModel({
        @JsonKey(name: "data")
        List<Datum>? data,
        @JsonKey(name: "total")
        int? total,
        @JsonKey(name: "current_page")
        int? currentPage,
        @JsonKey(name: "per_page")
        int? perPage,
        @JsonKey(name: "from")
        int? from,
        @JsonKey(name: "to")
        int? to,
        @JsonKey(name: "last_page")
        int? lastPage,
        @JsonKey(name: "has_next")
        bool? hasNext,
        @JsonKey(name: "prev")
        dynamic prev,
        @JsonKey(name: "next")
        dynamic next,
        @JsonKey(name: "processed_time")
        double? processedTime,
    }) = _HistoryAttendanceModel;

    factory HistoryAttendanceModel.fromJson(Map<String, dynamic> json) => _$HistoryAttendanceModelFromJson(json);
}

@freezed
class Datum with _$Datum {
    const factory Datum({
         @JsonKey(name: "meta_read")
        bool? metaRead,
        @JsonKey(name: "meta_delete")
        bool? metaDelete,
        @JsonKey(name: "meta_update")
        bool? metaUpdate,
        @JsonKey(name: "meta_create")
        bool? metaCreate,
        @JsonKey(name: "id")
        int? id,
        @JsonKey(name: "m_comp_id")
        int? datumMCompId,
        @JsonKey(name: "default_user_id")
        int? datumDefaultUserId,
        @JsonKey(name: "tanggal")
        String? tanggal,
        @JsonKey(name: "status")
        String? status,
        @JsonKey(name: "checkin_time")
        String? checkinTime,
        @JsonKey(name: "checkin_foto")
        String? checkinFoto,
        @JsonKey(name: "checkin_lat")
        String? checkinLat,
        @JsonKey(name: "checkin_long")
        String? checkinLong,
        @JsonKey(name: "checkin_address")
        String? checkinAddress,
        @JsonKey(name: "checkin_region")
        String? checkinRegion,
        @JsonKey(name: "checkin_on_scope")
        bool? checkinOnScope,
        @JsonKey(name: "checkout_time")
        String? checkoutTime,
        @JsonKey(name: "checkout_foto")
        String? checkoutFoto,
        @JsonKey(name: "checkout_lat")
        String? checkoutLat,
        @JsonKey(name: "checkout_long")
        String? checkoutLong,
        @JsonKey(name: "checkout_address")
        String? checkoutAddress,
        @JsonKey(name: "checkout_region")
        String? checkoutRegion,
        @JsonKey(name: "checkout_on_scope")
        bool? checkoutOnScope,
        @JsonKey(name: "creator_id")
        int? datumCreatorId,
        @JsonKey(name: "last_editor_id")
        dynamic datumLastEditorId,
        @JsonKey(name: "created_at")
        String? createdAt,
        @JsonKey(name: "updated_at")
        String? updatedAt,
        @JsonKey(name: "catatan_in")
        String? catatanIn,
        @JsonKey(name: "catatan_out")
        dynamic catatanOut,
        @JsonKey(name: "m_comp.id")
        int? mCompId,
        @JsonKey(name: "m_comp.nama")
        String? mCompNama,
        @JsonKey(name: "m_comp.is_active")
        bool? mCompIsActive,
        @JsonKey(name: "m_comp.desc")
        dynamic mCompDesc,
        @JsonKey(name: "m_comp.creator_id")
        dynamic mCompCreatorId,
        @JsonKey(name: "m_comp.last_editor_id")
        dynamic mCompLastEditorId,
        @JsonKey(name: "m_comp.created_at")
        dynamic mCompCreatedAt,
        @JsonKey(name: "m_comp.updated_at")
        dynamic mCompUpdatedAt,
        @JsonKey(name: "default_user.id")
        int? defaultUserId,
        @JsonKey(name: "default_user.name")
        String? defaultUserName,
        @JsonKey(name: "default_user.email")
        String? defaultUserEmail,
        @JsonKey(name: "default_user.username")
        String? defaultUserUsername,
        @JsonKey(name: "default_user.email_verified_at")
        dynamic defaultUserEmailVerifiedAt,
        @JsonKey(name: "default_user.password")
        String? defaultUserPassword,
        @JsonKey(name: "default_user.m_comp_id")
        int? defaultUserMCompId,
        @JsonKey(name: "default_user.m_dir_id")
        int? defaultUserMDirId,
        @JsonKey(name: "default_user.is_active")
        bool? defaultUserIsActive,
        @JsonKey(name: "default_user.creator_id")
        dynamic defaultUserCreatorId,
        @JsonKey(name: "default_user.last_editor_id")
        int? defaultUserLastEditorId,
        @JsonKey(name: "default_user.remember_token")
        dynamic defaultUserRememberToken,
        @JsonKey(name: "default_user.created_at")
        dynamic defaultUserCreatedAt,
        @JsonKey(name: "default_user.updated_at")
        String? defaultUserUpdatedAt,
        @JsonKey(name: "default_user.profil_image")
        String? defaultUserProfilImage,
        @JsonKey(name: "default_user.telp")
        String? defaultUserTelp,
        @JsonKey(name: "default_user.m_kary_id")
        int? defaultUserMKaryId,
        @JsonKey(name: "creator.id")
        int? creatorId,
        @JsonKey(name: "creator.name")
        String? creatorName,
        @JsonKey(name: "creator.email")
        String? creatorEmail,
        @JsonKey(name: "creator.username")
        String? creatorUsername,
        @JsonKey(name: "creator.email_verified_at")
        dynamic creatorEmailVerifiedAt,
        @JsonKey(name: "creator.password")
        String? creatorPassword,
        @JsonKey(name: "creator.m_comp_id")
        int? creatorMCompId,
        @JsonKey(name: "creator.m_dir_id")
        int? creatorMDirId,
        @JsonKey(name: "creator.is_active")
        bool? creatorIsActive,
        @JsonKey(name: "creator.creator_id")
        dynamic creatorCreatorId,
        @JsonKey(name: "creator.last_editor_id")
        int? creatorLastEditorId,
        @JsonKey(name: "creator.remember_token")
        dynamic creatorRememberToken,
        @JsonKey(name: "creator.created_at")
        dynamic creatorCreatedAt,
        @JsonKey(name: "creator.updated_at")
        String? creatorUpdatedAt,
        @JsonKey(name: "creator.profil_image")
        String? creatorProfilImage,
        @JsonKey(name: "creator.telp")
        String? creatorTelp,
        @JsonKey(name: "creator.m_kary_id")
        int? creatorMKaryId,
        @JsonKey(name: "last_editor.id")
        dynamic lastEditorId,
        @JsonKey(name: "last_editor.name")
        dynamic lastEditorName,
        @JsonKey(name: "last_editor.email")
        dynamic lastEditorEmail,
        @JsonKey(name: "last_editor.username")
        dynamic lastEditorUsername,
        @JsonKey(name: "last_editor.email_verified_at")
        dynamic lastEditorEmailVerifiedAt,
        @JsonKey(name: "last_editor.password")
        dynamic lastEditorPassword,
        @JsonKey(name: "last_editor.m_comp_id")
        dynamic lastEditorMCompId,
        @JsonKey(name: "last_editor.m_dir_id")
        dynamic lastEditorMDirId,
        @JsonKey(name: "last_editor.is_active")
        dynamic lastEditorIsActive,
        @JsonKey(name: "last_editor.creator_id")
        dynamic lastEditorCreatorId,
        @JsonKey(name: "last_editor.last_editor_id")
        dynamic lastEditorLastEditorId,
        @JsonKey(name: "last_editor.remember_token")
        dynamic lastEditorRememberToken,
        @JsonKey(name: "last_editor.created_at")
        dynamic lastEditorCreatedAt,
        @JsonKey(name: "last_editor.updated_at")
        dynamic lastEditorUpdatedAt,
        @JsonKey(name: "last_editor.profil_image")
        dynamic lastEditorProfilImage,
        @JsonKey(name: "last_editor.telp")
        dynamic lastEditorTelp,
        @JsonKey(name: "last_editor.m_kary_id")
        dynamic lastEditorMKaryId,
    }) = _Datum;

    factory Datum.fromJson(Map<String, dynamic> json) => _$DatumFromJson(json);
}
