import 'package:freezed_annotation/freezed_annotation.dart';
import 'dart:convert';

part 'response_all_karyawan.freezed.dart';
part 'response_all_karyawan.g.dart';

@freezed
class ResponseAllKaryawan with _$ResponseAllKaryawan {
  const factory ResponseAllKaryawan({
    @JsonKey(name: "data") List<DataAllKaryawan>? data,
    @JsonKey(name: "total") int? total,
    @JsonKey(name: "current_page") int? currentPage,
    @JsonKey(name: "per_page") int? perPage,
    @JsonKey(name: "from") int? from,
    @JsonKey(name: "to") int? to,
    @JsonKey(name: "last_page") int? lastPage,
    @JsonKey(name: "has_next") bool? hasNext,
    @JsonKey(name: "prev") dynamic prev,
    @JsonKey(name: "next") String? next,
    @JsonKey(name: "processed_time") double? processedTime,
  }) = _ResponseAllKaryawan;

  factory ResponseAllKaryawan.fromJson(Map<String, dynamic> json) =>
      _$ResponseAllKaryawanFromJson(json);
}

@freezed
class DataAllKaryawan with _$DataAllKaryawan {
  const factory DataAllKaryawan({
    @JsonKey(name: "meta_read") bool? metaRead,
    @JsonKey(name: "meta_delete") bool? metaDelete,
    @JsonKey(name: "meta_update") bool? metaUpdate,
    @JsonKey(name: "meta_create") bool? metaCreate,
    @JsonKey(name: "id") int? id,
    @JsonKey(name: "m_comp_id") dynamic DataAllKaryawanMCompId,
    @JsonKey(name: "m_dir_id") dynamic DataAllKaryawanMDirId,
    @JsonKey(name: "m_divisi_id") int? DataAllKaryawanMDivisiId,
    @JsonKey(name: "m_dept_id") int? DataAllKaryawanMDeptId,
    @JsonKey(name: "m_zona_id") dynamic DataAllKaryawanMZonaId,
    @JsonKey(name: "grading_id") dynamic DataAllKaryawanGradingId,
    @JsonKey(name: "costcontre_id") dynamic DataAllKaryawanCostcontreId,
    @JsonKey(name: "kode") String? kode,
    @JsonKey(name: "m_posisi_id") int? DataAllKaryawanMPosisiId,
    @JsonKey(name: "m_jam_kerja_id") dynamic DataAllKaryawanMJamKerjaId,
    @JsonKey(name: "kode_presensi") String? kodePresensi,
    @JsonKey(name: "nik") String? nik,
    @JsonKey(name: "nama_depan") String? namaDepan,
    @JsonKey(name: "nama_belakang") String? namaBelakang,
    @JsonKey(name: "nama_lengkap") String? namaLengkap,
    @JsonKey(name: "nama_panggilan") String? namaPanggilan,
    @JsonKey(name: "jk_id") int? DataAllKaryawanJkId,
    @JsonKey(name: "tempat_lahir") String? tempatLahir,
    @JsonKey(name: "tgl_lahir") String? tglLahir,
    @JsonKey(name: "provinsi_id") int? DataAllKaryawanProvinsiId,
    @JsonKey(name: "kota_id") int? DataAllKaryawanKotaId,
    @JsonKey(name: "kecamatan_id") int? DataAllKaryawanKecamatanId,
    @JsonKey(name: "kode_pos") String? kodePos,
    @JsonKey(name: "alamat_asli") String? alamatAsli,
    @JsonKey(name: "alamat_domisili") String? alamatDomisili,
    @JsonKey(name: "no_tlp") String? noTlp,
    @JsonKey(name: "no_tlp_lainnya") String? noTlpLainnya,
    @JsonKey(name: "no_darurat") String? noDarurat,
    @JsonKey(name: "nama_kontak_darurat") String? namaKontakDarurat,
    @JsonKey(name: "agama_id") int? DataAllKaryawanAgamaId,
    @JsonKey(name: "gol_darah_id") int? DataAllKaryawanGolDarahId,
    @JsonKey(name: "status_nikah_id") int? DataAllKaryawanStatusNikahId,
    @JsonKey(name: "tanggungan_id") int? DataAllKaryawanTanggunganId,
    @JsonKey(name: "hub_dgn_karyawan") String? hubDgnKaryawan,
    @JsonKey(name: "cuti_jatah_reguler") dynamic cutiJatahReguler,
    @JsonKey(name: "cuti_sisa_reguler") dynamic cutiSisaReguler,
    @JsonKey(name: "cuti_panjang") dynamic cutiPanjang,
    @JsonKey(name: "cuti_sisa_panjang") dynamic cutiSisaPanjang,
    @JsonKey(name: "status_kary_id") dynamic DataAllKaryawanStatusKaryId,
    @JsonKey(name: "lama_kontrak_awal") dynamic lamaKontrakAwal,
    @JsonKey(name: "lama_kontrak_akhir") dynamic lamaKontrakAkhir,
    @JsonKey(name: "tgl_masuk") String? tglMasuk,
    @JsonKey(name: "tgl_berhenti") dynamic tglBerhenti,
    @JsonKey(name: "alasan_berhenti") dynamic alasanBerhenti,
    @JsonKey(name: "uk_baju") String? ukBaju,
    @JsonKey(name: "uk_celana") String? ukCelana,
    @JsonKey(name: "uk_sepatu") String? ukSepatu,
    @JsonKey(name: "desc") dynamic desc,
    @JsonKey(name: "is_active") bool? isActive,
    @JsonKey(name: "creator_id") int? DataAllKaryawanCreatorId,
    @JsonKey(name: "last_editor_id") int? DataAllKaryawanLastEditorId,
    @JsonKey(name: "created_at") String? createdAt,
    @JsonKey(name: "updated_at") String? updatedAt,
    @JsonKey(name: "m_standart_gaji_id") dynamic DataAllKaryawanMStandartGajiId,
    @JsonKey(name: "periode_gaji_id") int? DataAllKaryawanPeriodeGajiId,
    @JsonKey(name: "ref_id") dynamic DataAllKaryawanRefId,
    @JsonKey(name: "presensi_lokasi_default_id")
    int? DataAllKaryawanPresensiLokasiDefaultId,
    @JsonKey(name: "exp_date_cuti") dynamic expDateCuti,
    @JsonKey(name: "limit_potong") int? limitPotong,
    @JsonKey(name: "atasan_id") int? DataAllKaryawanAtasanId,
    @JsonKey(name: "cuti_p24") int? cutiP24,
    @JsonKey(name: "cuti_sisa_p24") dynamic cutiSisaP24,
    @JsonKey(name: "tipe_jam_kerja_id") dynamic DataAllKaryawanTipeJamKerjaId,
    @JsonKey(name: "t_jadwal_kerja_id") dynamic DataAllKaryawanTJadwalKerjaId,
    @JsonKey(name: "m_comp.id") dynamic mCompId,
    @JsonKey(name: "m_comp.nama") dynamic mCompNama,
    @JsonKey(name: "m_comp.is_active") dynamic mCompIsActive,
    @JsonKey(name: "m_comp.desc") dynamic mCompDesc,
    @JsonKey(name: "m_comp.creator_id") dynamic mCompCreatorId,
    @JsonKey(name: "m_comp.last_editor_id") dynamic mCompLastEditorId,
    @JsonKey(name: "m_comp.created_at") dynamic mCompCreatedAt,
    @JsonKey(name: "m_comp.updated_at") dynamic mCompUpdatedAt,
    @JsonKey(name: "m_dir.id") dynamic mDirId,
    @JsonKey(name: "m_dir.m_comp_id") dynamic mDirMCompId,
    @JsonKey(name: "m_dir.nama") dynamic mDirNama,
    @JsonKey(name: "m_dir.desc") dynamic mDirDesc,
    @JsonKey(name: "m_dir.is_active") dynamic mDirIsActive,
    @JsonKey(name: "m_dir.creator_id") dynamic mDirCreatorId,
    @JsonKey(name: "m_dir.last_editor_id") dynamic mDirLastEditorId,
    @JsonKey(name: "m_dir.created_at") dynamic mDirCreatedAt,
    @JsonKey(name: "m_dir.updated_at") dynamic mDirUpdatedAt,
    @JsonKey(name: "m_divisi.id") int? mDivisiId,
    @JsonKey(name: "m_divisi.m_comp_id") dynamic mDivisiMCompId,
    @JsonKey(name: "m_divisi.m_dir_id") int? mDivisiMDirId,
    @JsonKey(name: "m_divisi.nama") String? mDivisiNama,
    @JsonKey(name: "m_divisi.desc") dynamic mDivisiDesc,
    @JsonKey(name: "m_divisi.is_active") bool? mDivisiIsActive,
    @JsonKey(name: "m_divisi.creator_id") int? mDivisiCreatorId,
    @JsonKey(name: "m_divisi.last_editor_id") dynamic mDivisiLastEditorId,
    @JsonKey(name: "m_divisi.created_at") String? mDivisiCreatedAt,
    @JsonKey(name: "m_divisi.updated_at") String? mDivisiUpdatedAt,
    @JsonKey(name: "m_dept.id") int? mDeptId,
    @JsonKey(name: "m_dept.m_dir_id") int? mDeptMDirId,
    @JsonKey(name: "m_dept.m_divisi_id") int? mDeptMDivisiId,
    @JsonKey(name: "m_dept.nama") String? mDeptNama,
    @JsonKey(name: "m_dept.desc") dynamic mDeptDesc,
    @JsonKey(name: "m_dept.is_active") bool? mDeptIsActive,
    @JsonKey(name: "m_dept.creator_id") dynamic mDeptCreatorId,
    @JsonKey(name: "m_dept.last_editor_id") dynamic mDeptLastEditorId,
    @JsonKey(name: "m_dept.created_at") String? mDeptCreatedAt,
    @JsonKey(name: "m_dept.updated_at") String? mDeptUpdatedAt,
    @JsonKey(name: "m_zona.id") dynamic mZonaId,
    @JsonKey(name: "m_zona.m_comp_id") dynamic mZonaMCompId,
    @JsonKey(name: "m_zona.m_dir_id") dynamic mZonaMDirId,
    @JsonKey(name: "m_zona.kode") dynamic mZonaKode,
    @JsonKey(name: "m_zona.nama") dynamic mZonaNama,
    @JsonKey(name: "m_zona.desc") dynamic mZonaDesc,
    @JsonKey(name: "m_zona.is_active") dynamic mZonaIsActive,
    @JsonKey(name: "m_zona.creator_id") dynamic mZonaCreatorId,
    @JsonKey(name: "m_zona.last_editor_id") dynamic mZonaLastEditorId,
    @JsonKey(name: "m_zona.created_at") dynamic mZonaCreatedAt,
    @JsonKey(name: "m_zona.updated_at") dynamic mZonaUpdatedAt,
    @JsonKey(name: "grading.id") dynamic gradingId,
    @JsonKey(name: "grading.m_comp_id") dynamic gradingMCompId,
    @JsonKey(name: "grading.m_dir_id") dynamic gradingMDirId,
    @JsonKey(name: "grading.group") dynamic gradingGroup,
    @JsonKey(name: "grading.key") dynamic gradingKey,
    @JsonKey(name: "grading.code") dynamic gradingCode,
    @JsonKey(name: "grading.value") dynamic gradingValue,
    @JsonKey(name: "grading.is_active") dynamic gradingIsActive,
    @JsonKey(name: "grading.creator_id") dynamic gradingCreatorId,
    @JsonKey(name: "grading.last_editor_id") dynamic gradingLastEditorId,
    @JsonKey(name: "grading.created_at") dynamic gradingCreatedAt,
    @JsonKey(name: "grading.updated_at") dynamic gradingUpdatedAt,
    @JsonKey(name: "grading.value_2") dynamic gradingValue2,
    @JsonKey(name: "grading.value_3") dynamic gradingValue3,
    @JsonKey(name: "costcontre.id") dynamic costcontreId,
    @JsonKey(name: "costcontre.m_comp_id") dynamic costcontreMCompId,
    @JsonKey(name: "costcontre.m_dir_id") dynamic costcontreMDirId,
    @JsonKey(name: "costcontre.group") dynamic costcontreGroup,
    @JsonKey(name: "costcontre.key") dynamic costcontreKey,
    @JsonKey(name: "costcontre.code") dynamic costcontreCode,
    @JsonKey(name: "costcontre.value") dynamic costcontreValue,
    @JsonKey(name: "costcontre.is_active") dynamic costcontreIsActive,
    @JsonKey(name: "costcontre.creator_id") dynamic costcontreCreatorId,
    @JsonKey(name: "costcontre.last_editor_id") dynamic costcontreLastEditorId,
    @JsonKey(name: "costcontre.created_at") dynamic costcontreCreatedAt,
    @JsonKey(name: "costcontre.updated_at") dynamic costcontreUpdatedAt,
    @JsonKey(name: "costcontre.value_2") dynamic costcontreValue2,
    @JsonKey(name: "costcontre.value_3") dynamic costcontreValue3,
    @JsonKey(name: "m_posisi.id") int? mPosisiId,
    @JsonKey(name: "m_posisi.m_comp_id") dynamic mPosisiMCompId,
    @JsonKey(name: "m_posisi.m_dir_id") dynamic mPosisiMDirId,
    @JsonKey(name: "m_posisi.kode") String? mPosisiKode,
    @JsonKey(name: "m_posisi.desc_kerja") String? mPosisiDescKerja,
    @JsonKey(name: "m_posisi.desc_kerja_1") String? mPosisiDescKerja1,
    @JsonKey(name: "m_posisi.desc_kerja_2") dynamic mPosisiDescKerja2,
    @JsonKey(name: "m_posisi.min_pengalaman") String? mPosisiMinPengalaman,
    @JsonKey(name: "m_posisi.min_pendidikan_id") int? mPosisiMinPendidikanId,
    @JsonKey(name: "m_posisi.min_gaji_pokok") String? mPosisiMinGajiPokok,
    @JsonKey(name: "m_posisi.max_gaji_pokok") String? mPosisiMaxGajiPokok,
    @JsonKey(name: "m_posisi.biaya") dynamic mPosisiBiaya,
    @JsonKey(name: "m_posisi.tipe_bpjs_id") dynamic mPosisiTipeBpjsId,
    @JsonKey(name: "m_posisi.potongan_bpjs") dynamic mPosisiPotonganBpjs,
    @JsonKey(name: "m_posisi.desc") dynamic mPosisiDesc,
    @JsonKey(name: "m_posisi.is_active") bool? mPosisiIsActive,
    @JsonKey(name: "m_posisi.creator_id") dynamic mPosisiCreatorId,
    @JsonKey(name: "m_posisi.last_editor_id") dynamic mPosisiLastEditorId,
    @JsonKey(name: "m_posisi.created_at") String? mPosisiCreatedAt,
    @JsonKey(name: "m_posisi.updated_at") String? mPosisiUpdatedAt,
    @JsonKey(name: "m_jam_kerja.id") dynamic mJamKerjaId,
    @JsonKey(name: "m_jam_kerja.m_comp_id") dynamic mJamKerjaMCompId,
    @JsonKey(name: "m_jam_kerja.m_dir_id") dynamic mJamKerjaMDirId,
    @JsonKey(name: "m_jam_kerja.kode") dynamic mJamKerjaKode,
    @JsonKey(name: "m_jam_kerja.tipe_jam_kerja_id")
    dynamic mJamKerjaTipeJamKerjaId,
    @JsonKey(name: "m_jam_kerja.waktu_mulai") dynamic mJamKerjaWaktuMulai,
    @JsonKey(name: "m_jam_kerja.waktu_akhir") dynamic mJamKerjaWaktuAkhir,
    @JsonKey(name: "m_jam_kerja.is_hari_berikutnya")
    dynamic mJamKerjaIsHariBerikutnya,
    @JsonKey(name: "m_jam_kerja.desc") dynamic mJamKerjaDesc,
    @JsonKey(name: "m_jam_kerja.is_active") dynamic mJamKerjaIsActive,
    @JsonKey(name: "m_jam_kerja.creator_id") dynamic mJamKerjaCreatorId,
    @JsonKey(name: "m_jam_kerja.last_editor_id") dynamic mJamKerjaLastEditorId,
    @JsonKey(name: "m_jam_kerja.created_at") dynamic mJamKerjaCreatedAt,
    @JsonKey(name: "m_jam_kerja.updated_at") dynamic mJamKerjaUpdatedAt,
    @JsonKey(name: "jk.id") int? jkId,
    @JsonKey(name: "jk.m_comp_id") int? jkMCompId,
    @JsonKey(name: "jk.m_dir_id") dynamic jkMDirId,
    @JsonKey(name: "jk.group") String? jkGroup,
    @JsonKey(name: "jk.key") String? jkKey,
    @JsonKey(name: "jk.code") String? jkCode,
    @JsonKey(name: "jk.value") String? jkValue,
    @JsonKey(name: "jk.is_active") bool? jkIsActive,
    @JsonKey(name: "jk.creator_id") dynamic jkCreatorId,
    @JsonKey(name: "jk.last_editor_id") dynamic jkLastEditorId,
    @JsonKey(name: "jk.created_at") String? jkCreatedAt,
    @JsonKey(name: "jk.updated_at") String? jkUpdatedAt,
    @JsonKey(name: "jk.value_2") dynamic jkValue2,
    @JsonKey(name: "jk.value_3") dynamic jkValue3,
    @JsonKey(name: "provinsi.id") int? provinsiId,
    @JsonKey(name: "provinsi.m_comp_id") int? provinsiMCompId,
    @JsonKey(name: "provinsi.m_dir_id") dynamic provinsiMDirId,
    @JsonKey(name: "provinsi.group") String? provinsiGroup,
    @JsonKey(name: "provinsi.key") dynamic provinsiKey,
    @JsonKey(name: "provinsi.code") dynamic provinsiCode,
    @JsonKey(name: "provinsi.value") String? provinsiValue,
    @JsonKey(name: "provinsi.is_active") bool? provinsiIsActive,
    @JsonKey(name: "provinsi.creator_id") dynamic provinsiCreatorId,
    @JsonKey(name: "provinsi.last_editor_id") dynamic provinsiLastEditorId,
    @JsonKey(name: "provinsi.created_at") dynamic provinsiCreatedAt,
    @JsonKey(name: "provinsi.updated_at") String? provinsiUpdatedAt,
    @JsonKey(name: "provinsi.value_2") dynamic provinsiValue2,
    @JsonKey(name: "provinsi.value_3") dynamic provinsiValue3,
    @JsonKey(name: "kota.id") int? kotaId,
    @JsonKey(name: "kota.m_comp_id") int? kotaMCompId,
    @JsonKey(name: "kota.m_dir_id") dynamic kotaMDirId,
    @JsonKey(name: "kota.group") String? kotaGroup,
    @JsonKey(name: "kota.key") String? kotaKey,
    @JsonKey(name: "kota.code") dynamic kotaCode,
    @JsonKey(name: "kota.value") String? kotaValue,
    @JsonKey(name: "kota.is_active") bool? kotaIsActive,
    @JsonKey(name: "kota.creator_id") dynamic kotaCreatorId,
    @JsonKey(name: "kota.last_editor_id") dynamic kotaLastEditorId,
    @JsonKey(name: "kota.created_at") dynamic kotaCreatedAt,
    @JsonKey(name: "kota.updated_at") dynamic kotaUpdatedAt,
    @JsonKey(name: "kota.value_2") dynamic kotaValue2,
    @JsonKey(name: "kota.value_3") dynamic kotaValue3,
    @JsonKey(name: "kecamatan.id") int? kecamatanId,
    @JsonKey(name: "kecamatan.m_comp_id") int? kecamatanMCompId,
    @JsonKey(name: "kecamatan.m_dir_id") dynamic kecamatanMDirId,
    @JsonKey(name: "kecamatan.group") String? kecamatanGroup,
    @JsonKey(name: "kecamatan.key") String? kecamatanKey,
    @JsonKey(name: "kecamatan.code") dynamic kecamatanCode,
    @JsonKey(name: "kecamatan.value") String? kecamatanValue,
    @JsonKey(name: "kecamatan.is_active") bool? kecamatanIsActive,
    @JsonKey(name: "kecamatan.creator_id") dynamic kecamatanCreatorId,
    @JsonKey(name: "kecamatan.last_editor_id") dynamic kecamatanLastEditorId,
    @JsonKey(name: "kecamatan.created_at") dynamic kecamatanCreatedAt,
    @JsonKey(name: "kecamatan.updated_at") dynamic kecamatanUpdatedAt,
    @JsonKey(name: "kecamatan.value_2") dynamic kecamatanValue2,
    @JsonKey(name: "kecamatan.value_3") dynamic kecamatanValue3,
    @JsonKey(name: "agama.id") int? agamaId,
    @JsonKey(name: "agama.m_comp_id") int? agamaMCompId,
    @JsonKey(name: "agama.m_dir_id") dynamic agamaMDirId,
    @JsonKey(name: "agama.group") String? agamaGroup,
    @JsonKey(name: "agama.key") String? agamaKey,
    @JsonKey(name: "agama.code") String? agamaCode,
    @JsonKey(name: "agama.value") String? agamaValue,
    @JsonKey(name: "agama.is_active") bool? agamaIsActive,
    @JsonKey(name: "agama.creator_id") dynamic agamaCreatorId,
    @JsonKey(name: "agama.last_editor_id") dynamic agamaLastEditorId,
    @JsonKey(name: "agama.created_at") String? agamaCreatedAt,
    @JsonKey(name: "agama.updated_at") String? agamaUpdatedAt,
    @JsonKey(name: "agama.value_2") dynamic agamaValue2,
    @JsonKey(name: "agama.value_3") dynamic agamaValue3,
    @JsonKey(name: "gol_darah.id") int? golDarahId,
    @JsonKey(name: "gol_darah.m_comp_id") int? golDarahMCompId,
    @JsonKey(name: "gol_darah.m_dir_id") dynamic golDarahMDirId,
    @JsonKey(name: "gol_darah.group") String? golDarahGroup,
    @JsonKey(name: "gol_darah.key") String? golDarahKey,
    @JsonKey(name: "gol_darah.code") String? golDarahCode,
    @JsonKey(name: "gol_darah.value") String? golDarahValue,
    @JsonKey(name: "gol_darah.is_active") bool? golDarahIsActive,
    @JsonKey(name: "gol_darah.creator_id") dynamic golDarahCreatorId,
    @JsonKey(name: "gol_darah.last_editor_id") dynamic golDarahLastEditorId,
    @JsonKey(name: "gol_darah.created_at") String? golDarahCreatedAt,
    @JsonKey(name: "gol_darah.updated_at") String? golDarahUpdatedAt,
    @JsonKey(name: "gol_darah.value_2") dynamic golDarahValue2,
    @JsonKey(name: "gol_darah.value_3") dynamic golDarahValue3,
    @JsonKey(name: "status_nikah.id") int? statusNikahId,
    @JsonKey(name: "status_nikah.m_comp_id") int? statusNikahMCompId,
    @JsonKey(name: "status_nikah.m_dir_id") dynamic statusNikahMDirId,
    @JsonKey(name: "status_nikah.group") String? statusNikahGroup,
    @JsonKey(name: "status_nikah.key") String? statusNikahKey,
    @JsonKey(name: "status_nikah.code") String? statusNikahCode,
    @JsonKey(name: "status_nikah.value") String? statusNikahValue,
    @JsonKey(name: "status_nikah.is_active") bool? statusNikahIsActive,
    @JsonKey(name: "status_nikah.creator_id") dynamic statusNikahCreatorId,
    @JsonKey(name: "status_nikah.last_editor_id")
    dynamic statusNikahLastEditorId,
    @JsonKey(name: "status_nikah.created_at") String? statusNikahCreatedAt,
    @JsonKey(name: "status_nikah.updated_at") String? statusNikahUpdatedAt,
    @JsonKey(name: "status_nikah.value_2") dynamic statusNikahValue2,
    @JsonKey(name: "status_nikah.value_3") dynamic statusNikahValue3,
    @JsonKey(name: "tanggungan.id") int? tanggunganId,
    @JsonKey(name: "tanggungan.m_comp_id") int? tanggunganMCompId,
    @JsonKey(name: "tanggungan.m_dir_id") int? tanggunganMDirId,
    @JsonKey(name: "tanggungan.group") String? tanggunganGroup,
    @JsonKey(name: "tanggungan.key") String? tanggunganKey,
    @JsonKey(name: "tanggungan.code") String? tanggunganCode,
    @JsonKey(name: "tanggungan.value") String? tanggunganValue,
    @JsonKey(name: "tanggungan.is_active") bool? tanggunganIsActive,
    @JsonKey(name: "tanggungan.creator_id") dynamic tanggunganCreatorId,
    @JsonKey(name: "tanggungan.last_editor_id") dynamic tanggunganLastEditorId,
    @JsonKey(name: "tanggungan.created_at") String? tanggunganCreatedAt,
    @JsonKey(name: "tanggungan.updated_at") String? tanggunganUpdatedAt,
    @JsonKey(name: "tanggungan.value_2") String? tanggunganValue2,
    @JsonKey(name: "tanggungan.value_3") dynamic tanggunganValue3,
    @JsonKey(name: "status_kary.id") dynamic statusKaryId,
    @JsonKey(name: "status_kary.m_comp_id") dynamic statusKaryMCompId,
    @JsonKey(name: "status_kary.m_dir_id") dynamic statusKaryMDirId,
    @JsonKey(name: "status_kary.group") dynamic statusKaryGroup,
    @JsonKey(name: "status_kary.key") dynamic statusKaryKey,
    @JsonKey(name: "status_kary.code") dynamic statusKaryCode,
    @JsonKey(name: "status_kary.value") dynamic statusKaryValue,
    @JsonKey(name: "status_kary.is_active") dynamic statusKaryIsActive,
    @JsonKey(name: "status_kary.creator_id") dynamic statusKaryCreatorId,
    @JsonKey(name: "status_kary.last_editor_id") dynamic statusKaryLastEditorId,
    @JsonKey(name: "status_kary.created_at") dynamic statusKaryCreatedAt,
    @JsonKey(name: "status_kary.updated_at") dynamic statusKaryUpdatedAt,
    @JsonKey(name: "status_kary.value_2") dynamic statusKaryValue2,
    @JsonKey(name: "status_kary.value_3") dynamic statusKaryValue3,
    @JsonKey(name: "creator.id") int? creatorId,
    @JsonKey(name: "creator.name") String? creatorName,
    @JsonKey(name: "creator.email") String? creatorEmail,
    @JsonKey(name: "creator.username") String? creatorUsername,
    @JsonKey(name: "creator.email_verified_at") dynamic creatorEmailVerifiedAt,
    @JsonKey(name: "creator.password") String? creatorPassword,
    @JsonKey(name: "creator.m_comp_id") int? creatorMCompId,
    @JsonKey(name: "creator.m_dir_id") int? creatorMDirId,
    @JsonKey(name: "creator.is_active") bool? creatorIsActive,
    @JsonKey(name: "creator.creator_id") dynamic creatorCreatorId,
    @JsonKey(name: "creator.last_editor_id") dynamic creatorLastEditorId,
    @JsonKey(name: "creator.remember_token") dynamic creatorRememberToken,
    @JsonKey(name: "creator.created_at") String? creatorCreatedAt,
    @JsonKey(name: "creator.updated_at") String? creatorUpdatedAt,
    @JsonKey(name: "creator.profil_image") String? creatorProfilImage,
    @JsonKey(name: "creator.telp") dynamic creatorTelp,
    @JsonKey(name: "creator.m_kary_id") int? creatorMKaryId,
    @JsonKey(name: "last_editor.id") int? lastEditorId,
    @JsonKey(name: "last_editor.name") String? lastEditorName,
    @JsonKey(name: "last_editor.email") String? lastEditorEmail,
    @JsonKey(name: "last_editor.username") String? lastEditorUsername,
    @JsonKey(name: "last_editor.email_verified_at")
    dynamic lastEditorEmailVerifiedAt,
    @JsonKey(name: "last_editor.password") String? lastEditorPassword,
    @JsonKey(name: "last_editor.m_comp_id") int? lastEditorMCompId,
    @JsonKey(name: "last_editor.m_dir_id") int? lastEditorMDirId,
    @JsonKey(name: "last_editor.is_active") bool? lastEditorIsActive,
    @JsonKey(name: "last_editor.creator_id") dynamic lastEditorCreatorId,
    @JsonKey(name: "last_editor.last_editor_id") dynamic lastEditorLastEditorId,
    @JsonKey(name: "last_editor.remember_token")
    dynamic lastEditorRememberToken,
    @JsonKey(name: "last_editor.created_at") String? lastEditorCreatedAt,
    @JsonKey(name: "last_editor.updated_at") String? lastEditorUpdatedAt,
    @JsonKey(name: "last_editor.profil_image") String? lastEditorProfilImage,
    @JsonKey(name: "last_editor.telp") dynamic lastEditorTelp,
    @JsonKey(name: "last_editor.m_kary_id") int? lastEditorMKaryId,
    @JsonKey(name: "m_standart_gaji.id") dynamic mStandartGajiId,
    @JsonKey(name: "m_standart_gaji.m_comp_id") dynamic mStandartGajiMCompId,
    @JsonKey(name: "m_standart_gaji.m_dir_id") dynamic mStandartGajiMDirId,
    @JsonKey(name: "m_standart_gaji.kode") dynamic mStandartGajiKode,
    @JsonKey(name: "m_standart_gaji.m_divisi_id")
    dynamic mStandartGajiMDivisiId,
    @JsonKey(name: "m_standart_gaji.m_dept_id") dynamic mStandartGajiMDeptId,
    @JsonKey(name: "m_standart_gaji.m_zona_id") dynamic mStandartGajiMZonaId,
    @JsonKey(name: "m_standart_gaji.m_posisi_id")
    dynamic mStandartGajiMPosisiId,
    @JsonKey(name: "m_standart_gaji.grading_id") dynamic mStandartGajiGradingId,
    @JsonKey(name: "m_standart_gaji.gaji_pokok") dynamic mStandartGajiGajiPokok,
    @JsonKey(name: "m_standart_gaji.gaji_pokok_periode")
    dynamic mStandartGajiGajiPokokPeriode,
    @JsonKey(name: "m_standart_gaji.uang_saku") dynamic mStandartGajiUangSaku,
    @JsonKey(name: "m_standart_gaji.uang_saku_periode")
    dynamic mStandartGajiUangSakuPeriode,
    @JsonKey(name: "m_standart_gaji.tunjangan_posisi")
    dynamic mStandartGajiTunjanganPosisi,
    @JsonKey(name: "m_standart_gaji.tunjangan_posisi_periode")
    dynamic mStandartGajiTunjanganPosisiPeriode,
    @JsonKey(name: "m_standart_gaji.tunjangan_kemahalan_id")
    dynamic mStandartGajiTunjanganKemahalanId,
    @JsonKey(name: "m_standart_gaji.tunjangan_kemahalan_periode")
    dynamic mStandartGajiTunjanganKemahalanPeriode,
    @JsonKey(name: "m_standart_gaji.uang_makan") dynamic mStandartGajiUangMakan,
    @JsonKey(name: "m_standart_gaji.uang_makan_periode")
    dynamic mStandartGajiUangMakanPeriode,
    @JsonKey(name: "m_standart_gaji.tunjangan_tetap")
    dynamic mStandartGajiTunjanganTetap,
    @JsonKey(name: "m_standart_gaji.tunjangan_tetap_periode")
    dynamic mStandartGajiTunjanganTetapPeriode,
    @JsonKey(name: "m_standart_gaji.desc") dynamic mStandartGajiDesc,
    @JsonKey(name: "m_standart_gaji.is_active") dynamic mStandartGajiIsActive,
    @JsonKey(name: "m_standart_gaji.creator_id") dynamic mStandartGajiCreatorId,
    @JsonKey(name: "m_standart_gaji.last_editor_id")
    dynamic mStandartGajiLastEditorId,
    @JsonKey(name: "m_standart_gaji.created_at") dynamic mStandartGajiCreatedAt,
    @JsonKey(name: "m_standart_gaji.updated_at") dynamic mStandartGajiUpdatedAt,
    @JsonKey(name: "periode_gaji.id") int? periodeGajiId,
    @JsonKey(name: "periode_gaji.m_comp_id") int? periodeGajiMCompId,
    @JsonKey(name: "periode_gaji.m_dir_id") dynamic periodeGajiMDirId,
    @JsonKey(name: "periode_gaji.group") String? periodeGajiGroup,
    @JsonKey(name: "periode_gaji.key") String? periodeGajiKey,
    @JsonKey(name: "periode_gaji.code") String? periodeGajiCode,
    @JsonKey(name: "periode_gaji.value") String? periodeGajiValue,
    @JsonKey(name: "periode_gaji.is_active") bool? periodeGajiIsActive,
    @JsonKey(name: "periode_gaji.creator_id") dynamic periodeGajiCreatorId,
    @JsonKey(name: "periode_gaji.last_editor_id")
    dynamic periodeGajiLastEditorId,
    @JsonKey(name: "periode_gaji.created_at") String? periodeGajiCreatedAt,
    @JsonKey(name: "periode_gaji.updated_at") String? periodeGajiUpdatedAt,
    @JsonKey(name: "periode_gaji.value_2") dynamic periodeGajiValue2,
    @JsonKey(name: "periode_gaji.value_3") dynamic periodeGajiValue3,
    @JsonKey(name: "ref.id") dynamic refId,
    @JsonKey(name: "ref.nomor") dynamic refNomor,
    @JsonKey(name: "ref.m_comp_id") dynamic refMCompId,
    @JsonKey(name: "ref.m_dir_id") dynamic refMDirId,
    @JsonKey(name: "ref.nama_pelamar") dynamic refNamaPelamar,
    @JsonKey(name: "ref.ktp_no") dynamic refKtpNo,
    @JsonKey(name: "ref.tanggal") dynamic refTanggal,
    @JsonKey(name: "ref.ref") dynamic refRef,
    @JsonKey(name: "ref.telp") dynamic refTelp,
    @JsonKey(name: "ref.jk_id") dynamic refJkId,
    @JsonKey(name: "ref.tgl_lahir") dynamic refTglLahir,
    @JsonKey(name: "ref.salary") dynamic refSalary,
    @JsonKey(name: "ref.deskripsi") dynamic refDeskripsi,
    @JsonKey(name: "ref.status") dynamic refStatus,
    @JsonKey(name: "ref.creator_id") dynamic refCreatorId,
    @JsonKey(name: "ref.last_editor_id") dynamic refLastEditorId,
    @JsonKey(name: "ref.created_at") dynamic refCreatedAt,
    @JsonKey(name: "ref.updated_at") dynamic refUpdatedAt,
    @JsonKey(name: "ref.m_divisi_id") dynamic refMDivisiId,
    @JsonKey(name: "ref.m_dept_id") dynamic refMDeptId,
    @JsonKey(name: "ref.m_posisi_id") dynamic refMPosisiId,
    @JsonKey(name: "ref.tempat_lahir") dynamic refTempatLahir,
    @JsonKey(name: "ref.t_loker_id") dynamic refTLokerId,
    @JsonKey(name: "presensi_lokasi_default.id") int? presensiLokasiDefaultId,
    @JsonKey(name: "presensi_lokasi_default.comp_id")
    int? presensiLokasiDefaultCompId,
    @JsonKey(name: "presensi_lokasi_default.default_user_id")
    dynamic presensiLokasiDefaultDefaultUserId,
    @JsonKey(name: "presensi_lokasi_default.nama")
    String? presensiLokasiDefaultNama,
    @JsonKey(name: "presensi_lokasi_default.lat")
    String? presensiLokasiDefaultLat,
    @JsonKey(name: "presensi_lokasi_default.long")
    String? presensiLokasiDefaultLong,
    @JsonKey(name: "presensi_lokasi_default.is_active")
    bool? presensiLokasiDefaultIsActive,
    @JsonKey(name: "presensi_lokasi_default.creator_id")
    int? presensiLokasiDefaultCreatorId,
    @JsonKey(name: "presensi_lokasi_default.last_editor_id")
    dynamic presensiLokasiDefaultLastEditorId,
    @JsonKey(name: "presensi_lokasi_default.created_at")
    String? presensiLokasiDefaultCreatedAt,
    @JsonKey(name: "presensi_lokasi_default.updated_at")
    dynamic presensiLokasiDefaultUpdatedAt,
    @JsonKey(name: "atasan.id") dynamic atasanId,
    @JsonKey(name: "atasan.m_comp_id") dynamic atasanMCompId,
    @JsonKey(name: "atasan.m_dir_id") dynamic atasanMDirId,
    @JsonKey(name: "atasan.m_divisi_id") dynamic atasanMDivisiId,
    @JsonKey(name: "atasan.m_dept_id") dynamic atasanMDeptId,
    @JsonKey(name: "atasan.m_zona_id") dynamic atasanMZonaId,
    @JsonKey(name: "atasan.grading_id") dynamic atasanGradingId,
    @JsonKey(name: "atasan.costcontre_id") dynamic atasanCostcontreId,
    @JsonKey(name: "atasan.kode") dynamic atasanKode,
    @JsonKey(name: "atasan.m_posisi_id") dynamic atasanMPosisiId,
    @JsonKey(name: "atasan.m_jam_kerja_id") dynamic atasanMJamKerjaId,
    @JsonKey(name: "atasan.kode_presensi") dynamic atasanKodePresensi,
    @JsonKey(name: "atasan.nik") dynamic atasanNik,
    @JsonKey(name: "atasan.nama_depan") dynamic atasanNamaDepan,
    @JsonKey(name: "atasan.nama_belakang") dynamic atasanNamaBelakang,
    @JsonKey(name: "atasan.nama_lengkap") dynamic atasanNamaLengkap,
    @JsonKey(name: "atasan.nama_panggilan") dynamic atasanNamaPanggilan,
    @JsonKey(name: "atasan.jk_id") dynamic atasanJkId,
    @JsonKey(name: "atasan.tempat_lahir") dynamic atasanTempatLahir,
    @JsonKey(name: "atasan.tgl_lahir") dynamic atasanTglLahir,
    @JsonKey(name: "atasan.provinsi_id") dynamic atasanProvinsiId,
    @JsonKey(name: "atasan.kota_id") dynamic atasanKotaId,
    @JsonKey(name: "atasan.kecamatan_id") dynamic atasanKecamatanId,
    @JsonKey(name: "atasan.kode_pos") dynamic atasanKodePos,
    @JsonKey(name: "atasan.alamat_asli") dynamic atasanAlamatAsli,
    @JsonKey(name: "atasan.alamat_domisili") dynamic atasanAlamatDomisili,
    @JsonKey(name: "atasan.no_tlp") dynamic atasanNoTlp,
    @JsonKey(name: "atasan.no_tlp_lainnya") dynamic atasanNoTlpLainnya,
    @JsonKey(name: "atasan.no_darurat") dynamic atasanNoDarurat,
    @JsonKey(name: "atasan.nama_kontak_darurat")
    dynamic atasanNamaKontakDarurat,
    @JsonKey(name: "atasan.agama_id") dynamic atasanAgamaId,
    @JsonKey(name: "atasan.gol_darah_id") dynamic atasanGolDarahId,
    @JsonKey(name: "atasan.status_nikah_id") dynamic atasanStatusNikahId,
    @JsonKey(name: "atasan.tanggungan_id") dynamic atasanTanggunganId,
    @JsonKey(name: "atasan.hub_dgn_karyawan") dynamic atasanHubDgnKaryawan,
    @JsonKey(name: "atasan.cuti_jatah_reguler") dynamic atasanCutiJatahReguler,
    @JsonKey(name: "atasan.cuti_sisa_reguler") dynamic atasanCutiSisaReguler,
    @JsonKey(name: "atasan.cuti_panjang") dynamic atasanCutiPanjang,
    @JsonKey(name: "atasan.cuti_sisa_panjang") dynamic atasanCutiSisaPanjang,
    @JsonKey(name: "atasan.status_kary_id") dynamic atasanStatusKaryId,
    @JsonKey(name: "atasan.lama_kontrak_awal") dynamic atasanLamaKontrakAwal,
    @JsonKey(name: "atasan.lama_kontrak_akhir") dynamic atasanLamaKontrakAkhir,
    @JsonKey(name: "atasan.tgl_masuk") dynamic atasanTglMasuk,
    @JsonKey(name: "atasan.tgl_berhenti") dynamic atasanTglBerhenti,
    @JsonKey(name: "atasan.alasan_berhenti") dynamic atasanAlasanBerhenti,
    @JsonKey(name: "atasan.uk_baju") dynamic atasanUkBaju,
    @JsonKey(name: "atasan.uk_celana") dynamic atasanUkCelana,
    @JsonKey(name: "atasan.uk_sepatu") dynamic atasanUkSepatu,
    @JsonKey(name: "atasan.desc") dynamic atasanDesc,
    @JsonKey(name: "atasan.is_active") dynamic atasanIsActive,
    @JsonKey(name: "atasan.creator_id") dynamic atasanCreatorId,
    @JsonKey(name: "atasan.last_editor_id") dynamic atasanLastEditorId,
    @JsonKey(name: "atasan.created_at") dynamic atasanCreatedAt,
    @JsonKey(name: "atasan.updated_at") dynamic atasanUpdatedAt,
    @JsonKey(name: "atasan.m_standart_gaji_id") dynamic atasanMStandartGajiId,
    @JsonKey(name: "atasan.periode_gaji_id") dynamic atasanPeriodeGajiId,
    @JsonKey(name: "atasan.ref_id") dynamic atasanRefId,
    @JsonKey(name: "atasan.presensi_lokasi_default_id")
    dynamic atasanPresensiLokasiDefaultId,
    @JsonKey(name: "atasan.exp_date_cuti") dynamic atasanExpDateCuti,
    @JsonKey(name: "atasan.limit_potong") dynamic atasanLimitPotong,
    @JsonKey(name: "atasan.atasan_id") dynamic atasanAtasanId,
    @JsonKey(name: "atasan.cuti_p24") dynamic atasanCutiP24,
    @JsonKey(name: "atasan.cuti_sisa_p24") dynamic atasanCutiSisaP24,
    @JsonKey(name: "atasan.tipe_jam_kerja_id") dynamic atasanTipeJamKerjaId,
    @JsonKey(name: "atasan.t_jadwal_kerja_id") dynamic atasanTJadwalKerjaId,
    @JsonKey(name: "tipe_jam_kerja.id") dynamic tipeJamKerjaId,
    @JsonKey(name: "tipe_jam_kerja.m_comp_id") dynamic tipeJamKerjaMCompId,
    @JsonKey(name: "tipe_jam_kerja.m_dir_id") dynamic tipeJamKerjaMDirId,
    @JsonKey(name: "tipe_jam_kerja.group") dynamic tipeJamKerjaGroup,
    @JsonKey(name: "tipe_jam_kerja.key") dynamic tipeJamKerjaKey,
    @JsonKey(name: "tipe_jam_kerja.code") dynamic tipeJamKerjaCode,
    @JsonKey(name: "tipe_jam_kerja.value") dynamic tipeJamKerjaValue,
    @JsonKey(name: "tipe_jam_kerja.is_active") dynamic tipeJamKerjaIsActive,
    @JsonKey(name: "tipe_jam_kerja.creator_id") dynamic tipeJamKerjaCreatorId,
    @JsonKey(name: "tipe_jam_kerja.last_editor_id")
    dynamic tipeJamKerjaLastEditorId,
    @JsonKey(name: "tipe_jam_kerja.created_at") dynamic tipeJamKerjaCreatedAt,
    @JsonKey(name: "tipe_jam_kerja.updated_at") dynamic tipeJamKerjaUpdatedAt,
    @JsonKey(name: "tipe_jam_kerja.value_2") dynamic tipeJamKerjaValue2,
    @JsonKey(name: "tipe_jam_kerja.value_3") dynamic tipeJamKerjaValue3,
    @JsonKey(name: "t_jadwal_kerja.id") dynamic tJadwalKerjaId,
    @JsonKey(name: "t_jadwal_kerja.nomor") dynamic tJadwalKerjaNomor,
    @JsonKey(name: "t_jadwal_kerja.m_comp_id") dynamic tJadwalKerjaMCompId,
    @JsonKey(name: "t_jadwal_kerja.m_dir_id") dynamic tJadwalKerjaMDirId,
    @JsonKey(name: "t_jadwal_kerja.m_divisi_id") dynamic tJadwalKerjaMDivisiId,
    @JsonKey(name: "t_jadwal_kerja.m_dept_id") dynamic tJadwalKerjaMDeptId,
    @JsonKey(name: "t_jadwal_kerja.tipe_jam_kerja_id")
    dynamic tJadwalKerjaTipeJamKerjaId,
    @JsonKey(name: "t_jadwal_kerja.keterangan") dynamic tJadwalKerjaKeterangan,
    @JsonKey(name: "t_jadwal_kerja.status") dynamic tJadwalKerjaStatus,
    @JsonKey(name: "t_jadwal_kerja.creator_id") dynamic tJadwalKerjaCreatorId,
    @JsonKey(name: "t_jadwal_kerja.last_editor_id")
    dynamic tJadwalKerjaLastEditorId,
    @JsonKey(name: "t_jadwal_kerja.created_at") dynamic tJadwalKerjaCreatedAt,
    @JsonKey(name: "t_jadwal_kerja.updated_at") dynamic tJadwalKerjaUpdatedAt,
    @JsonKey(name: "nomor_ktp") String? nomorKtp,
  }) = _DataAllKaryawan;

  factory DataAllKaryawan.fromJson(Map<String, dynamic> json) =>
      _$DataAllKaryawanFromJson(json);
}
