// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'response_all_karyawan.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

_$ResponseAllKaryawanImpl _$$ResponseAllKaryawanImplFromJson(
        Map<String, dynamic> json) =>
    _$ResponseAllKaryawanImpl(
      data: (json['data'] as List<dynamic>?)
          ?.map((e) => DataAllKaryawan.fromJson(e as Map<String, dynamic>))
          .toList(),
      total: json['total'] as int?,
      currentPage: json['current_page'] as int?,
      perPage: json['per_page'] as int?,
      from: json['from'] as int?,
      to: json['to'] as int?,
      lastPage: json['last_page'] as int?,
      hasNext: json['has_next'] as bool?,
      prev: json['prev'],
      next: json['next'] as String?,
      processedTime: (json['processed_time'] as num?)?.toDouble(),
    );

Map<String, dynamic> _$$ResponseAllKaryawanImplToJson(
        _$ResponseAllKaryawanImpl instance) =>
    <String, dynamic>{
      'data': instance.data,
      'total': instance.total,
      'current_page': instance.currentPage,
      'per_page': instance.perPage,
      'from': instance.from,
      'to': instance.to,
      'last_page': instance.lastPage,
      'has_next': instance.hasNext,
      'prev': instance.prev,
      'next': instance.next,
      'processed_time': instance.processedTime,
    };

_$DataAllKaryawanImpl _$$DataAllKaryawanImplFromJson(
        Map<String, dynamic> json) =>
    _$DataAllKaryawanImpl(
      metaRead: json['meta_read'] as bool?,
      metaDelete: json['meta_delete'] as bool?,
      metaUpdate: json['meta_update'] as bool?,
      metaCreate: json['meta_create'] as bool?,
      id: json['id'] as int?,
      DataAllKaryawanMCompId: json['m_comp_id'],
      DataAllKaryawanMDirId: json['m_dir_id'],
      DataAllKaryawanMDivisiId: json['m_divisi_id'] as int?,
      DataAllKaryawanMDeptId: json['m_dept_id'] as int?,
      DataAllKaryawanMZonaId: json['m_zona_id'],
      DataAllKaryawanGradingId: json['grading_id'],
      DataAllKaryawanCostcontreId: json['costcontre_id'],
      kode: json['kode'] as String?,
      DataAllKaryawanMPosisiId: json['m_posisi_id'] as int?,
      DataAllKaryawanMJamKerjaId: json['m_jam_kerja_id'],
      kodePresensi: json['kode_presensi'] as String?,
      nik: json['nik'] as String?,
      namaDepan: json['nama_depan'] as String?,
      namaBelakang: json['nama_belakang'] as String?,
      namaLengkap: json['nama_lengkap'] as String?,
      namaPanggilan: json['nama_panggilan'] as String?,
      DataAllKaryawanJkId: json['jk_id'] as int?,
      tempatLahir: json['tempat_lahir'] as String?,
      tglLahir: json['tgl_lahir'] as String?,
      DataAllKaryawanProvinsiId: json['provinsi_id'] as int?,
      DataAllKaryawanKotaId: json['kota_id'] as int?,
      DataAllKaryawanKecamatanId: json['kecamatan_id'] as int?,
      kodePos: json['kode_pos'] as String?,
      alamatAsli: json['alamat_asli'] as String?,
      alamatDomisili: json['alamat_domisili'] as String?,
      noTlp: json['no_tlp'] as String?,
      noTlpLainnya: json['no_tlp_lainnya'] as String?,
      noDarurat: json['no_darurat'] as String?,
      namaKontakDarurat: json['nama_kontak_darurat'] as String?,
      DataAllKaryawanAgamaId: json['agama_id'] as int?,
      DataAllKaryawanGolDarahId: json['gol_darah_id'] as int?,
      DataAllKaryawanStatusNikahId: json['status_nikah_id'] as int?,
      DataAllKaryawanTanggunganId: json['tanggungan_id'] as int?,
      hubDgnKaryawan: json['hub_dgn_karyawan'] as String?,
      cutiJatahReguler: json['cuti_jatah_reguler'],
      cutiSisaReguler: json['cuti_sisa_reguler'],
      cutiPanjang: json['cuti_panjang'],
      cutiSisaPanjang: json['cuti_sisa_panjang'],
      DataAllKaryawanStatusKaryId: json['status_kary_id'],
      lamaKontrakAwal: json['lama_kontrak_awal'],
      lamaKontrakAkhir: json['lama_kontrak_akhir'],
      tglMasuk: json['tgl_masuk'] as String?,
      tglBerhenti: json['tgl_berhenti'],
      alasanBerhenti: json['alasan_berhenti'],
      ukBaju: json['uk_baju'] as String?,
      ukCelana: json['uk_celana'] as String?,
      ukSepatu: json['uk_sepatu'] as String?,
      desc: json['desc'],
      isActive: json['is_active'] as bool?,
      DataAllKaryawanCreatorId: json['creator_id'] as int?,
      DataAllKaryawanLastEditorId: json['last_editor_id'] as int?,
      createdAt: json['created_at'] as String?,
      updatedAt: json['updated_at'] as String?,
      DataAllKaryawanMStandartGajiId: json['m_standart_gaji_id'],
      DataAllKaryawanPeriodeGajiId: json['periode_gaji_id'] as int?,
      DataAllKaryawanRefId: json['ref_id'],
      DataAllKaryawanPresensiLokasiDefaultId:
          json['presensi_lokasi_default_id'] as int?,
      expDateCuti: json['exp_date_cuti'],
      limitPotong: json['limit_potong'] as int?,
      DataAllKaryawanAtasanId: json['atasan_id'] as int?,
      cutiP24: json['cuti_p24'] as int?,
      cutiSisaP24: json['cuti_sisa_p24'],
      DataAllKaryawanTipeJamKerjaId: json['tipe_jam_kerja_id'],
      DataAllKaryawanTJadwalKerjaId: json['t_jadwal_kerja_id'],
      mCompId: json['m_comp.id'],
      mCompNama: json['m_comp.nama'],
      mCompIsActive: json['m_comp.is_active'],
      mCompDesc: json['m_comp.desc'],
      mCompCreatorId: json['m_comp.creator_id'],
      mCompLastEditorId: json['m_comp.last_editor_id'],
      mCompCreatedAt: json['m_comp.created_at'],
      mCompUpdatedAt: json['m_comp.updated_at'],
      mDirId: json['m_dir.id'],
      mDirMCompId: json['m_dir.m_comp_id'],
      mDirNama: json['m_dir.nama'],
      mDirDesc: json['m_dir.desc'],
      mDirIsActive: json['m_dir.is_active'],
      mDirCreatorId: json['m_dir.creator_id'],
      mDirLastEditorId: json['m_dir.last_editor_id'],
      mDirCreatedAt: json['m_dir.created_at'],
      mDirUpdatedAt: json['m_dir.updated_at'],
      mDivisiId: json['m_divisi.id'] as int?,
      mDivisiMCompId: json['m_divisi.m_comp_id'],
      mDivisiMDirId: json['m_divisi.m_dir_id'] as int?,
      mDivisiNama: json['m_divisi.nama'] as String?,
      mDivisiDesc: json['m_divisi.desc'],
      mDivisiIsActive: json['m_divisi.is_active'] as bool?,
      mDivisiCreatorId: json['m_divisi.creator_id'] as int?,
      mDivisiLastEditorId: json['m_divisi.last_editor_id'],
      mDivisiCreatedAt: json['m_divisi.created_at'] as String?,
      mDivisiUpdatedAt: json['m_divisi.updated_at'] as String?,
      mDeptId: json['m_dept.id'] as int?,
      mDeptMDirId: json['m_dept.m_dir_id'] as int?,
      mDeptMDivisiId: json['m_dept.m_divisi_id'] as int?,
      mDeptNama: json['m_dept.nama'] as String?,
      mDeptDesc: json['m_dept.desc'],
      mDeptIsActive: json['m_dept.is_active'] as bool?,
      mDeptCreatorId: json['m_dept.creator_id'],
      mDeptLastEditorId: json['m_dept.last_editor_id'],
      mDeptCreatedAt: json['m_dept.created_at'] as String?,
      mDeptUpdatedAt: json['m_dept.updated_at'] as String?,
      mZonaId: json['m_zona.id'],
      mZonaMCompId: json['m_zona.m_comp_id'],
      mZonaMDirId: json['m_zona.m_dir_id'],
      mZonaKode: json['m_zona.kode'],
      mZonaNama: json['m_zona.nama'],
      mZonaDesc: json['m_zona.desc'],
      mZonaIsActive: json['m_zona.is_active'],
      mZonaCreatorId: json['m_zona.creator_id'],
      mZonaLastEditorId: json['m_zona.last_editor_id'],
      mZonaCreatedAt: json['m_zona.created_at'],
      mZonaUpdatedAt: json['m_zona.updated_at'],
      gradingId: json['grading.id'],
      gradingMCompId: json['grading.m_comp_id'],
      gradingMDirId: json['grading.m_dir_id'],
      gradingGroup: json['grading.group'],
      gradingKey: json['grading.key'],
      gradingCode: json['grading.code'],
      gradingValue: json['grading.value'],
      gradingIsActive: json['grading.is_active'],
      gradingCreatorId: json['grading.creator_id'],
      gradingLastEditorId: json['grading.last_editor_id'],
      gradingCreatedAt: json['grading.created_at'],
      gradingUpdatedAt: json['grading.updated_at'],
      gradingValue2: json['grading.value_2'],
      gradingValue3: json['grading.value_3'],
      costcontreId: json['costcontre.id'],
      costcontreMCompId: json['costcontre.m_comp_id'],
      costcontreMDirId: json['costcontre.m_dir_id'],
      costcontreGroup: json['costcontre.group'],
      costcontreKey: json['costcontre.key'],
      costcontreCode: json['costcontre.code'],
      costcontreValue: json['costcontre.value'],
      costcontreIsActive: json['costcontre.is_active'],
      costcontreCreatorId: json['costcontre.creator_id'],
      costcontreLastEditorId: json['costcontre.last_editor_id'],
      costcontreCreatedAt: json['costcontre.created_at'],
      costcontreUpdatedAt: json['costcontre.updated_at'],
      costcontreValue2: json['costcontre.value_2'],
      costcontreValue3: json['costcontre.value_3'],
      mPosisiId: json['m_posisi.id'] as int?,
      mPosisiMCompId: json['m_posisi.m_comp_id'],
      mPosisiMDirId: json['m_posisi.m_dir_id'],
      mPosisiKode: json['m_posisi.kode'] as String?,
      mPosisiDescKerja: json['m_posisi.desc_kerja'] as String?,
      mPosisiDescKerja1: json['m_posisi.desc_kerja_1'] as String?,
      mPosisiDescKerja2: json['m_posisi.desc_kerja_2'],
      mPosisiMinPengalaman: json['m_posisi.min_pengalaman'] as String?,
      mPosisiMinPendidikanId: json['m_posisi.min_pendidikan_id'] as int?,
      mPosisiMinGajiPokok: json['m_posisi.min_gaji_pokok'] as String?,
      mPosisiMaxGajiPokok: json['m_posisi.max_gaji_pokok'] as String?,
      mPosisiBiaya: json['m_posisi.biaya'],
      mPosisiTipeBpjsId: json['m_posisi.tipe_bpjs_id'],
      mPosisiPotonganBpjs: json['m_posisi.potongan_bpjs'],
      mPosisiDesc: json['m_posisi.desc'],
      mPosisiIsActive: json['m_posisi.is_active'] as bool?,
      mPosisiCreatorId: json['m_posisi.creator_id'],
      mPosisiLastEditorId: json['m_posisi.last_editor_id'],
      mPosisiCreatedAt: json['m_posisi.created_at'] as String?,
      mPosisiUpdatedAt: json['m_posisi.updated_at'] as String?,
      mJamKerjaId: json['m_jam_kerja.id'],
      mJamKerjaMCompId: json['m_jam_kerja.m_comp_id'],
      mJamKerjaMDirId: json['m_jam_kerja.m_dir_id'],
      mJamKerjaKode: json['m_jam_kerja.kode'],
      mJamKerjaTipeJamKerjaId: json['m_jam_kerja.tipe_jam_kerja_id'],
      mJamKerjaWaktuMulai: json['m_jam_kerja.waktu_mulai'],
      mJamKerjaWaktuAkhir: json['m_jam_kerja.waktu_akhir'],
      mJamKerjaIsHariBerikutnya: json['m_jam_kerja.is_hari_berikutnya'],
      mJamKerjaDesc: json['m_jam_kerja.desc'],
      mJamKerjaIsActive: json['m_jam_kerja.is_active'],
      mJamKerjaCreatorId: json['m_jam_kerja.creator_id'],
      mJamKerjaLastEditorId: json['m_jam_kerja.last_editor_id'],
      mJamKerjaCreatedAt: json['m_jam_kerja.created_at'],
      mJamKerjaUpdatedAt: json['m_jam_kerja.updated_at'],
      jkId: json['jk.id'] as int?,
      jkMCompId: json['jk.m_comp_id'] as int?,
      jkMDirId: json['jk.m_dir_id'],
      jkGroup: json['jk.group'] as String?,
      jkKey: json['jk.key'] as String?,
      jkCode: json['jk.code'] as String?,
      jkValue: json['jk.value'] as String?,
      jkIsActive: json['jk.is_active'] as bool?,
      jkCreatorId: json['jk.creator_id'],
      jkLastEditorId: json['jk.last_editor_id'],
      jkCreatedAt: json['jk.created_at'] as String?,
      jkUpdatedAt: json['jk.updated_at'] as String?,
      jkValue2: json['jk.value_2'],
      jkValue3: json['jk.value_3'],
      provinsiId: json['provinsi.id'] as int?,
      provinsiMCompId: json['provinsi.m_comp_id'] as int?,
      provinsiMDirId: json['provinsi.m_dir_id'],
      provinsiGroup: json['provinsi.group'] as String?,
      provinsiKey: json['provinsi.key'],
      provinsiCode: json['provinsi.code'],
      provinsiValue: json['provinsi.value'] as String?,
      provinsiIsActive: json['provinsi.is_active'] as bool?,
      provinsiCreatorId: json['provinsi.creator_id'],
      provinsiLastEditorId: json['provinsi.last_editor_id'],
      provinsiCreatedAt: json['provinsi.created_at'],
      provinsiUpdatedAt: json['provinsi.updated_at'] as String?,
      provinsiValue2: json['provinsi.value_2'],
      provinsiValue3: json['provinsi.value_3'],
      kotaId: json['kota.id'] as int?,
      kotaMCompId: json['kota.m_comp_id'] as int?,
      kotaMDirId: json['kota.m_dir_id'],
      kotaGroup: json['kota.group'] as String?,
      kotaKey: json['kota.key'] as String?,
      kotaCode: json['kota.code'],
      kotaValue: json['kota.value'] as String?,
      kotaIsActive: json['kota.is_active'] as bool?,
      kotaCreatorId: json['kota.creator_id'],
      kotaLastEditorId: json['kota.last_editor_id'],
      kotaCreatedAt: json['kota.created_at'],
      kotaUpdatedAt: json['kota.updated_at'],
      kotaValue2: json['kota.value_2'],
      kotaValue3: json['kota.value_3'],
      kecamatanId: json['kecamatan.id'] as int?,
      kecamatanMCompId: json['kecamatan.m_comp_id'] as int?,
      kecamatanMDirId: json['kecamatan.m_dir_id'],
      kecamatanGroup: json['kecamatan.group'] as String?,
      kecamatanKey: json['kecamatan.key'] as String?,
      kecamatanCode: json['kecamatan.code'],
      kecamatanValue: json['kecamatan.value'] as String?,
      kecamatanIsActive: json['kecamatan.is_active'] as bool?,
      kecamatanCreatorId: json['kecamatan.creator_id'],
      kecamatanLastEditorId: json['kecamatan.last_editor_id'],
      kecamatanCreatedAt: json['kecamatan.created_at'],
      kecamatanUpdatedAt: json['kecamatan.updated_at'],
      kecamatanValue2: json['kecamatan.value_2'],
      kecamatanValue3: json['kecamatan.value_3'],
      agamaId: json['agama.id'] as int?,
      agamaMCompId: json['agama.m_comp_id'] as int?,
      agamaMDirId: json['agama.m_dir_id'],
      agamaGroup: json['agama.group'] as String?,
      agamaKey: json['agama.key'] as String?,
      agamaCode: json['agama.code'] as String?,
      agamaValue: json['agama.value'] as String?,
      agamaIsActive: json['agama.is_active'] as bool?,
      agamaCreatorId: json['agama.creator_id'],
      agamaLastEditorId: json['agama.last_editor_id'],
      agamaCreatedAt: json['agama.created_at'] as String?,
      agamaUpdatedAt: json['agama.updated_at'] as String?,
      agamaValue2: json['agama.value_2'],
      agamaValue3: json['agama.value_3'],
      golDarahId: json['gol_darah.id'] as int?,
      golDarahMCompId: json['gol_darah.m_comp_id'] as int?,
      golDarahMDirId: json['gol_darah.m_dir_id'],
      golDarahGroup: json['gol_darah.group'] as String?,
      golDarahKey: json['gol_darah.key'] as String?,
      golDarahCode: json['gol_darah.code'] as String?,
      golDarahValue: json['gol_darah.value'] as String?,
      golDarahIsActive: json['gol_darah.is_active'] as bool?,
      golDarahCreatorId: json['gol_darah.creator_id'],
      golDarahLastEditorId: json['gol_darah.last_editor_id'],
      golDarahCreatedAt: json['gol_darah.created_at'] as String?,
      golDarahUpdatedAt: json['gol_darah.updated_at'] as String?,
      golDarahValue2: json['gol_darah.value_2'],
      golDarahValue3: json['gol_darah.value_3'],
      statusNikahId: json['status_nikah.id'] as int?,
      statusNikahMCompId: json['status_nikah.m_comp_id'] as int?,
      statusNikahMDirId: json['status_nikah.m_dir_id'],
      statusNikahGroup: json['status_nikah.group'] as String?,
      statusNikahKey: json['status_nikah.key'] as String?,
      statusNikahCode: json['status_nikah.code'] as String?,
      statusNikahValue: json['status_nikah.value'] as String?,
      statusNikahIsActive: json['status_nikah.is_active'] as bool?,
      statusNikahCreatorId: json['status_nikah.creator_id'],
      statusNikahLastEditorId: json['status_nikah.last_editor_id'],
      statusNikahCreatedAt: json['status_nikah.created_at'] as String?,
      statusNikahUpdatedAt: json['status_nikah.updated_at'] as String?,
      statusNikahValue2: json['status_nikah.value_2'],
      statusNikahValue3: json['status_nikah.value_3'],
      tanggunganId: json['tanggungan.id'] as int?,
      tanggunganMCompId: json['tanggungan.m_comp_id'] as int?,
      tanggunganMDirId: json['tanggungan.m_dir_id'] as int?,
      tanggunganGroup: json['tanggungan.group'] as String?,
      tanggunganKey: json['tanggungan.key'] as String?,
      tanggunganCode: json['tanggungan.code'] as String?,
      tanggunganValue: json['tanggungan.value'] as String?,
      tanggunganIsActive: json['tanggungan.is_active'] as bool?,
      tanggunganCreatorId: json['tanggungan.creator_id'],
      tanggunganLastEditorId: json['tanggungan.last_editor_id'],
      tanggunganCreatedAt: json['tanggungan.created_at'] as String?,
      tanggunganUpdatedAt: json['tanggungan.updated_at'] as String?,
      tanggunganValue2: json['tanggungan.value_2'] as String?,
      tanggunganValue3: json['tanggungan.value_3'],
      statusKaryId: json['status_kary.id'],
      statusKaryMCompId: json['status_kary.m_comp_id'],
      statusKaryMDirId: json['status_kary.m_dir_id'],
      statusKaryGroup: json['status_kary.group'],
      statusKaryKey: json['status_kary.key'],
      statusKaryCode: json['status_kary.code'],
      statusKaryValue: json['status_kary.value'],
      statusKaryIsActive: json['status_kary.is_active'],
      statusKaryCreatorId: json['status_kary.creator_id'],
      statusKaryLastEditorId: json['status_kary.last_editor_id'],
      statusKaryCreatedAt: json['status_kary.created_at'],
      statusKaryUpdatedAt: json['status_kary.updated_at'],
      statusKaryValue2: json['status_kary.value_2'],
      statusKaryValue3: json['status_kary.value_3'],
      creatorId: json['creator.id'] as int?,
      creatorName: json['creator.name'] as String?,
      creatorEmail: json['creator.email'] as String?,
      creatorUsername: json['creator.username'] as String?,
      creatorEmailVerifiedAt: json['creator.email_verified_at'],
      creatorPassword: json['creator.password'] as String?,
      creatorMCompId: json['creator.m_comp_id'] as int?,
      creatorMDirId: json['creator.m_dir_id'] as int?,
      creatorIsActive: json['creator.is_active'] as bool?,
      creatorCreatorId: json['creator.creator_id'],
      creatorLastEditorId: json['creator.last_editor_id'],
      creatorRememberToken: json['creator.remember_token'],
      creatorCreatedAt: json['creator.created_at'] as String?,
      creatorUpdatedAt: json['creator.updated_at'] as String?,
      creatorProfilImage: json['creator.profil_image'] as String?,
      creatorTelp: json['creator.telp'],
      creatorMKaryId: json['creator.m_kary_id'] as int?,
      lastEditorId: json['last_editor.id'] as int?,
      lastEditorName: json['last_editor.name'] as String?,
      lastEditorEmail: json['last_editor.email'] as String?,
      lastEditorUsername: json['last_editor.username'] as String?,
      lastEditorEmailVerifiedAt: json['last_editor.email_verified_at'],
      lastEditorPassword: json['last_editor.password'] as String?,
      lastEditorMCompId: json['last_editor.m_comp_id'] as int?,
      lastEditorMDirId: json['last_editor.m_dir_id'] as int?,
      lastEditorIsActive: json['last_editor.is_active'] as bool?,
      lastEditorCreatorId: json['last_editor.creator_id'],
      lastEditorLastEditorId: json['last_editor.last_editor_id'],
      lastEditorRememberToken: json['last_editor.remember_token'],
      lastEditorCreatedAt: json['last_editor.created_at'] as String?,
      lastEditorUpdatedAt: json['last_editor.updated_at'] as String?,
      lastEditorProfilImage: json['last_editor.profil_image'] as String?,
      lastEditorTelp: json['last_editor.telp'],
      lastEditorMKaryId: json['last_editor.m_kary_id'] as int?,
      mStandartGajiId: json['m_standart_gaji.id'],
      mStandartGajiMCompId: json['m_standart_gaji.m_comp_id'],
      mStandartGajiMDirId: json['m_standart_gaji.m_dir_id'],
      mStandartGajiKode: json['m_standart_gaji.kode'],
      mStandartGajiMDivisiId: json['m_standart_gaji.m_divisi_id'],
      mStandartGajiMDeptId: json['m_standart_gaji.m_dept_id'],
      mStandartGajiMZonaId: json['m_standart_gaji.m_zona_id'],
      mStandartGajiMPosisiId: json['m_standart_gaji.m_posisi_id'],
      mStandartGajiGradingId: json['m_standart_gaji.grading_id'],
      mStandartGajiGajiPokok: json['m_standart_gaji.gaji_pokok'],
      mStandartGajiGajiPokokPeriode: json['m_standart_gaji.gaji_pokok_periode'],
      mStandartGajiUangSaku: json['m_standart_gaji.uang_saku'],
      mStandartGajiUangSakuPeriode: json['m_standart_gaji.uang_saku_periode'],
      mStandartGajiTunjanganPosisi: json['m_standart_gaji.tunjangan_posisi'],
      mStandartGajiTunjanganPosisiPeriode:
          json['m_standart_gaji.tunjangan_posisi_periode'],
      mStandartGajiTunjanganKemahalanId:
          json['m_standart_gaji.tunjangan_kemahalan_id'],
      mStandartGajiTunjanganKemahalanPeriode:
          json['m_standart_gaji.tunjangan_kemahalan_periode'],
      mStandartGajiUangMakan: json['m_standart_gaji.uang_makan'],
      mStandartGajiUangMakanPeriode: json['m_standart_gaji.uang_makan_periode'],
      mStandartGajiTunjanganTetap: json['m_standart_gaji.tunjangan_tetap'],
      mStandartGajiTunjanganTetapPeriode:
          json['m_standart_gaji.tunjangan_tetap_periode'],
      mStandartGajiDesc: json['m_standart_gaji.desc'],
      mStandartGajiIsActive: json['m_standart_gaji.is_active'],
      mStandartGajiCreatorId: json['m_standart_gaji.creator_id'],
      mStandartGajiLastEditorId: json['m_standart_gaji.last_editor_id'],
      mStandartGajiCreatedAt: json['m_standart_gaji.created_at'],
      mStandartGajiUpdatedAt: json['m_standart_gaji.updated_at'],
      periodeGajiId: json['periode_gaji.id'] as int?,
      periodeGajiMCompId: json['periode_gaji.m_comp_id'] as int?,
      periodeGajiMDirId: json['periode_gaji.m_dir_id'],
      periodeGajiGroup: json['periode_gaji.group'] as String?,
      periodeGajiKey: json['periode_gaji.key'] as String?,
      periodeGajiCode: json['periode_gaji.code'] as String?,
      periodeGajiValue: json['periode_gaji.value'] as String?,
      periodeGajiIsActive: json['periode_gaji.is_active'] as bool?,
      periodeGajiCreatorId: json['periode_gaji.creator_id'],
      periodeGajiLastEditorId: json['periode_gaji.last_editor_id'],
      periodeGajiCreatedAt: json['periode_gaji.created_at'] as String?,
      periodeGajiUpdatedAt: json['periode_gaji.updated_at'] as String?,
      periodeGajiValue2: json['periode_gaji.value_2'],
      periodeGajiValue3: json['periode_gaji.value_3'],
      refId: json['ref.id'],
      refNomor: json['ref.nomor'],
      refMCompId: json['ref.m_comp_id'],
      refMDirId: json['ref.m_dir_id'],
      refNamaPelamar: json['ref.nama_pelamar'],
      refKtpNo: json['ref.ktp_no'],
      refTanggal: json['ref.tanggal'],
      refRef: json['ref.ref'],
      refTelp: json['ref.telp'],
      refJkId: json['ref.jk_id'],
      refTglLahir: json['ref.tgl_lahir'],
      refSalary: json['ref.salary'],
      refDeskripsi: json['ref.deskripsi'],
      refStatus: json['ref.status'],
      refCreatorId: json['ref.creator_id'],
      refLastEditorId: json['ref.last_editor_id'],
      refCreatedAt: json['ref.created_at'],
      refUpdatedAt: json['ref.updated_at'],
      refMDivisiId: json['ref.m_divisi_id'],
      refMDeptId: json['ref.m_dept_id'],
      refMPosisiId: json['ref.m_posisi_id'],
      refTempatLahir: json['ref.tempat_lahir'],
      refTLokerId: json['ref.t_loker_id'],
      presensiLokasiDefaultId: json['presensi_lokasi_default.id'] as int?,
      presensiLokasiDefaultCompId:
          json['presensi_lokasi_default.comp_id'] as int?,
      presensiLokasiDefaultDefaultUserId:
          json['presensi_lokasi_default.default_user_id'],
      presensiLokasiDefaultNama:
          json['presensi_lokasi_default.nama'] as String?,
      presensiLokasiDefaultLat: json['presensi_lokasi_default.lat'] as String?,
      presensiLokasiDefaultLong:
          json['presensi_lokasi_default.long'] as String?,
      presensiLokasiDefaultIsActive:
          json['presensi_lokasi_default.is_active'] as bool?,
      presensiLokasiDefaultCreatorId:
          json['presensi_lokasi_default.creator_id'] as int?,
      presensiLokasiDefaultLastEditorId:
          json['presensi_lokasi_default.last_editor_id'],
      presensiLokasiDefaultCreatedAt:
          json['presensi_lokasi_default.created_at'] as String?,
      presensiLokasiDefaultUpdatedAt:
          json['presensi_lokasi_default.updated_at'],
      atasanId: json['atasan.id'],
      atasanMCompId: json['atasan.m_comp_id'],
      atasanMDirId: json['atasan.m_dir_id'],
      atasanMDivisiId: json['atasan.m_divisi_id'],
      atasanMDeptId: json['atasan.m_dept_id'],
      atasanMZonaId: json['atasan.m_zona_id'],
      atasanGradingId: json['atasan.grading_id'],
      atasanCostcontreId: json['atasan.costcontre_id'],
      atasanKode: json['atasan.kode'],
      atasanMPosisiId: json['atasan.m_posisi_id'],
      atasanMJamKerjaId: json['atasan.m_jam_kerja_id'],
      atasanKodePresensi: json['atasan.kode_presensi'],
      atasanNik: json['atasan.nik'],
      atasanNamaDepan: json['atasan.nama_depan'],
      atasanNamaBelakang: json['atasan.nama_belakang'],
      atasanNamaLengkap: json['atasan.nama_lengkap'],
      atasanNamaPanggilan: json['atasan.nama_panggilan'],
      atasanJkId: json['atasan.jk_id'],
      atasanTempatLahir: json['atasan.tempat_lahir'],
      atasanTglLahir: json['atasan.tgl_lahir'],
      atasanProvinsiId: json['atasan.provinsi_id'],
      atasanKotaId: json['atasan.kota_id'],
      atasanKecamatanId: json['atasan.kecamatan_id'],
      atasanKodePos: json['atasan.kode_pos'],
      atasanAlamatAsli: json['atasan.alamat_asli'],
      atasanAlamatDomisili: json['atasan.alamat_domisili'],
      atasanNoTlp: json['atasan.no_tlp'],
      atasanNoTlpLainnya: json['atasan.no_tlp_lainnya'],
      atasanNoDarurat: json['atasan.no_darurat'],
      atasanNamaKontakDarurat: json['atasan.nama_kontak_darurat'],
      atasanAgamaId: json['atasan.agama_id'],
      atasanGolDarahId: json['atasan.gol_darah_id'],
      atasanStatusNikahId: json['atasan.status_nikah_id'],
      atasanTanggunganId: json['atasan.tanggungan_id'],
      atasanHubDgnKaryawan: json['atasan.hub_dgn_karyawan'],
      atasanCutiJatahReguler: json['atasan.cuti_jatah_reguler'],
      atasanCutiSisaReguler: json['atasan.cuti_sisa_reguler'],
      atasanCutiPanjang: json['atasan.cuti_panjang'],
      atasanCutiSisaPanjang: json['atasan.cuti_sisa_panjang'],
      atasanStatusKaryId: json['atasan.status_kary_id'],
      atasanLamaKontrakAwal: json['atasan.lama_kontrak_awal'],
      atasanLamaKontrakAkhir: json['atasan.lama_kontrak_akhir'],
      atasanTglMasuk: json['atasan.tgl_masuk'],
      atasanTglBerhenti: json['atasan.tgl_berhenti'],
      atasanAlasanBerhenti: json['atasan.alasan_berhenti'],
      atasanUkBaju: json['atasan.uk_baju'],
      atasanUkCelana: json['atasan.uk_celana'],
      atasanUkSepatu: json['atasan.uk_sepatu'],
      atasanDesc: json['atasan.desc'],
      atasanIsActive: json['atasan.is_active'],
      atasanCreatorId: json['atasan.creator_id'],
      atasanLastEditorId: json['atasan.last_editor_id'],
      atasanCreatedAt: json['atasan.created_at'],
      atasanUpdatedAt: json['atasan.updated_at'],
      atasanMStandartGajiId: json['atasan.m_standart_gaji_id'],
      atasanPeriodeGajiId: json['atasan.periode_gaji_id'],
      atasanRefId: json['atasan.ref_id'],
      atasanPresensiLokasiDefaultId: json['atasan.presensi_lokasi_default_id'],
      atasanExpDateCuti: json['atasan.exp_date_cuti'],
      atasanLimitPotong: json['atasan.limit_potong'],
      atasanAtasanId: json['atasan.atasan_id'],
      atasanCutiP24: json['atasan.cuti_p24'],
      atasanCutiSisaP24: json['atasan.cuti_sisa_p24'],
      atasanTipeJamKerjaId: json['atasan.tipe_jam_kerja_id'],
      atasanTJadwalKerjaId: json['atasan.t_jadwal_kerja_id'],
      tipeJamKerjaId: json['tipe_jam_kerja.id'],
      tipeJamKerjaMCompId: json['tipe_jam_kerja.m_comp_id'],
      tipeJamKerjaMDirId: json['tipe_jam_kerja.m_dir_id'],
      tipeJamKerjaGroup: json['tipe_jam_kerja.group'],
      tipeJamKerjaKey: json['tipe_jam_kerja.key'],
      tipeJamKerjaCode: json['tipe_jam_kerja.code'],
      tipeJamKerjaValue: json['tipe_jam_kerja.value'],
      tipeJamKerjaIsActive: json['tipe_jam_kerja.is_active'],
      tipeJamKerjaCreatorId: json['tipe_jam_kerja.creator_id'],
      tipeJamKerjaLastEditorId: json['tipe_jam_kerja.last_editor_id'],
      tipeJamKerjaCreatedAt: json['tipe_jam_kerja.created_at'],
      tipeJamKerjaUpdatedAt: json['tipe_jam_kerja.updated_at'],
      tipeJamKerjaValue2: json['tipe_jam_kerja.value_2'],
      tipeJamKerjaValue3: json['tipe_jam_kerja.value_3'],
      tJadwalKerjaId: json['t_jadwal_kerja.id'],
      tJadwalKerjaNomor: json['t_jadwal_kerja.nomor'],
      tJadwalKerjaMCompId: json['t_jadwal_kerja.m_comp_id'],
      tJadwalKerjaMDirId: json['t_jadwal_kerja.m_dir_id'],
      tJadwalKerjaMDivisiId: json['t_jadwal_kerja.m_divisi_id'],
      tJadwalKerjaMDeptId: json['t_jadwal_kerja.m_dept_id'],
      tJadwalKerjaTipeJamKerjaId: json['t_jadwal_kerja.tipe_jam_kerja_id'],
      tJadwalKerjaKeterangan: json['t_jadwal_kerja.keterangan'],
      tJadwalKerjaStatus: json['t_jadwal_kerja.status'],
      tJadwalKerjaCreatorId: json['t_jadwal_kerja.creator_id'],
      tJadwalKerjaLastEditorId: json['t_jadwal_kerja.last_editor_id'],
      tJadwalKerjaCreatedAt: json['t_jadwal_kerja.created_at'],
      tJadwalKerjaUpdatedAt: json['t_jadwal_kerja.updated_at'],
      nomorKtp: json['nomor_ktp'] as String?,
    );

Map<String, dynamic> _$$DataAllKaryawanImplToJson(
        _$DataAllKaryawanImpl instance) =>
    <String, dynamic>{
      'meta_read': instance.metaRead,
      'meta_delete': instance.metaDelete,
      'meta_update': instance.metaUpdate,
      'meta_create': instance.metaCreate,
      'id': instance.id,
      'm_comp_id': instance.DataAllKaryawanMCompId,
      'm_dir_id': instance.DataAllKaryawanMDirId,
      'm_divisi_id': instance.DataAllKaryawanMDivisiId,
      'm_dept_id': instance.DataAllKaryawanMDeptId,
      'm_zona_id': instance.DataAllKaryawanMZonaId,
      'grading_id': instance.DataAllKaryawanGradingId,
      'costcontre_id': instance.DataAllKaryawanCostcontreId,
      'kode': instance.kode,
      'm_posisi_id': instance.DataAllKaryawanMPosisiId,
      'm_jam_kerja_id': instance.DataAllKaryawanMJamKerjaId,
      'kode_presensi': instance.kodePresensi,
      'nik': instance.nik,
      'nama_depan': instance.namaDepan,
      'nama_belakang': instance.namaBelakang,
      'nama_lengkap': instance.namaLengkap,
      'nama_panggilan': instance.namaPanggilan,
      'jk_id': instance.DataAllKaryawanJkId,
      'tempat_lahir': instance.tempatLahir,
      'tgl_lahir': instance.tglLahir,
      'provinsi_id': instance.DataAllKaryawanProvinsiId,
      'kota_id': instance.DataAllKaryawanKotaId,
      'kecamatan_id': instance.DataAllKaryawanKecamatanId,
      'kode_pos': instance.kodePos,
      'alamat_asli': instance.alamatAsli,
      'alamat_domisili': instance.alamatDomisili,
      'no_tlp': instance.noTlp,
      'no_tlp_lainnya': instance.noTlpLainnya,
      'no_darurat': instance.noDarurat,
      'nama_kontak_darurat': instance.namaKontakDarurat,
      'agama_id': instance.DataAllKaryawanAgamaId,
      'gol_darah_id': instance.DataAllKaryawanGolDarahId,
      'status_nikah_id': instance.DataAllKaryawanStatusNikahId,
      'tanggungan_id': instance.DataAllKaryawanTanggunganId,
      'hub_dgn_karyawan': instance.hubDgnKaryawan,
      'cuti_jatah_reguler': instance.cutiJatahReguler,
      'cuti_sisa_reguler': instance.cutiSisaReguler,
      'cuti_panjang': instance.cutiPanjang,
      'cuti_sisa_panjang': instance.cutiSisaPanjang,
      'status_kary_id': instance.DataAllKaryawanStatusKaryId,
      'lama_kontrak_awal': instance.lamaKontrakAwal,
      'lama_kontrak_akhir': instance.lamaKontrakAkhir,
      'tgl_masuk': instance.tglMasuk,
      'tgl_berhenti': instance.tglBerhenti,
      'alasan_berhenti': instance.alasanBerhenti,
      'uk_baju': instance.ukBaju,
      'uk_celana': instance.ukCelana,
      'uk_sepatu': instance.ukSepatu,
      'desc': instance.desc,
      'is_active': instance.isActive,
      'creator_id': instance.DataAllKaryawanCreatorId,
      'last_editor_id': instance.DataAllKaryawanLastEditorId,
      'created_at': instance.createdAt,
      'updated_at': instance.updatedAt,
      'm_standart_gaji_id': instance.DataAllKaryawanMStandartGajiId,
      'periode_gaji_id': instance.DataAllKaryawanPeriodeGajiId,
      'ref_id': instance.DataAllKaryawanRefId,
      'presensi_lokasi_default_id':
          instance.DataAllKaryawanPresensiLokasiDefaultId,
      'exp_date_cuti': instance.expDateCuti,
      'limit_potong': instance.limitPotong,
      'atasan_id': instance.DataAllKaryawanAtasanId,
      'cuti_p24': instance.cutiP24,
      'cuti_sisa_p24': instance.cutiSisaP24,
      'tipe_jam_kerja_id': instance.DataAllKaryawanTipeJamKerjaId,
      't_jadwal_kerja_id': instance.DataAllKaryawanTJadwalKerjaId,
      'm_comp.id': instance.mCompId,
      'm_comp.nama': instance.mCompNama,
      'm_comp.is_active': instance.mCompIsActive,
      'm_comp.desc': instance.mCompDesc,
      'm_comp.creator_id': instance.mCompCreatorId,
      'm_comp.last_editor_id': instance.mCompLastEditorId,
      'm_comp.created_at': instance.mCompCreatedAt,
      'm_comp.updated_at': instance.mCompUpdatedAt,
      'm_dir.id': instance.mDirId,
      'm_dir.m_comp_id': instance.mDirMCompId,
      'm_dir.nama': instance.mDirNama,
      'm_dir.desc': instance.mDirDesc,
      'm_dir.is_active': instance.mDirIsActive,
      'm_dir.creator_id': instance.mDirCreatorId,
      'm_dir.last_editor_id': instance.mDirLastEditorId,
      'm_dir.created_at': instance.mDirCreatedAt,
      'm_dir.updated_at': instance.mDirUpdatedAt,
      'm_divisi.id': instance.mDivisiId,
      'm_divisi.m_comp_id': instance.mDivisiMCompId,
      'm_divisi.m_dir_id': instance.mDivisiMDirId,
      'm_divisi.nama': instance.mDivisiNama,
      'm_divisi.desc': instance.mDivisiDesc,
      'm_divisi.is_active': instance.mDivisiIsActive,
      'm_divisi.creator_id': instance.mDivisiCreatorId,
      'm_divisi.last_editor_id': instance.mDivisiLastEditorId,
      'm_divisi.created_at': instance.mDivisiCreatedAt,
      'm_divisi.updated_at': instance.mDivisiUpdatedAt,
      'm_dept.id': instance.mDeptId,
      'm_dept.m_dir_id': instance.mDeptMDirId,
      'm_dept.m_divisi_id': instance.mDeptMDivisiId,
      'm_dept.nama': instance.mDeptNama,
      'm_dept.desc': instance.mDeptDesc,
      'm_dept.is_active': instance.mDeptIsActive,
      'm_dept.creator_id': instance.mDeptCreatorId,
      'm_dept.last_editor_id': instance.mDeptLastEditorId,
      'm_dept.created_at': instance.mDeptCreatedAt,
      'm_dept.updated_at': instance.mDeptUpdatedAt,
      'm_zona.id': instance.mZonaId,
      'm_zona.m_comp_id': instance.mZonaMCompId,
      'm_zona.m_dir_id': instance.mZonaMDirId,
      'm_zona.kode': instance.mZonaKode,
      'm_zona.nama': instance.mZonaNama,
      'm_zona.desc': instance.mZonaDesc,
      'm_zona.is_active': instance.mZonaIsActive,
      'm_zona.creator_id': instance.mZonaCreatorId,
      'm_zona.last_editor_id': instance.mZonaLastEditorId,
      'm_zona.created_at': instance.mZonaCreatedAt,
      'm_zona.updated_at': instance.mZonaUpdatedAt,
      'grading.id': instance.gradingId,
      'grading.m_comp_id': instance.gradingMCompId,
      'grading.m_dir_id': instance.gradingMDirId,
      'grading.group': instance.gradingGroup,
      'grading.key': instance.gradingKey,
      'grading.code': instance.gradingCode,
      'grading.value': instance.gradingValue,
      'grading.is_active': instance.gradingIsActive,
      'grading.creator_id': instance.gradingCreatorId,
      'grading.last_editor_id': instance.gradingLastEditorId,
      'grading.created_at': instance.gradingCreatedAt,
      'grading.updated_at': instance.gradingUpdatedAt,
      'grading.value_2': instance.gradingValue2,
      'grading.value_3': instance.gradingValue3,
      'costcontre.id': instance.costcontreId,
      'costcontre.m_comp_id': instance.costcontreMCompId,
      'costcontre.m_dir_id': instance.costcontreMDirId,
      'costcontre.group': instance.costcontreGroup,
      'costcontre.key': instance.costcontreKey,
      'costcontre.code': instance.costcontreCode,
      'costcontre.value': instance.costcontreValue,
      'costcontre.is_active': instance.costcontreIsActive,
      'costcontre.creator_id': instance.costcontreCreatorId,
      'costcontre.last_editor_id': instance.costcontreLastEditorId,
      'costcontre.created_at': instance.costcontreCreatedAt,
      'costcontre.updated_at': instance.costcontreUpdatedAt,
      'costcontre.value_2': instance.costcontreValue2,
      'costcontre.value_3': instance.costcontreValue3,
      'm_posisi.id': instance.mPosisiId,
      'm_posisi.m_comp_id': instance.mPosisiMCompId,
      'm_posisi.m_dir_id': instance.mPosisiMDirId,
      'm_posisi.kode': instance.mPosisiKode,
      'm_posisi.desc_kerja': instance.mPosisiDescKerja,
      'm_posisi.desc_kerja_1': instance.mPosisiDescKerja1,
      'm_posisi.desc_kerja_2': instance.mPosisiDescKerja2,
      'm_posisi.min_pengalaman': instance.mPosisiMinPengalaman,
      'm_posisi.min_pendidikan_id': instance.mPosisiMinPendidikanId,
      'm_posisi.min_gaji_pokok': instance.mPosisiMinGajiPokok,
      'm_posisi.max_gaji_pokok': instance.mPosisiMaxGajiPokok,
      'm_posisi.biaya': instance.mPosisiBiaya,
      'm_posisi.tipe_bpjs_id': instance.mPosisiTipeBpjsId,
      'm_posisi.potongan_bpjs': instance.mPosisiPotonganBpjs,
      'm_posisi.desc': instance.mPosisiDesc,
      'm_posisi.is_active': instance.mPosisiIsActive,
      'm_posisi.creator_id': instance.mPosisiCreatorId,
      'm_posisi.last_editor_id': instance.mPosisiLastEditorId,
      'm_posisi.created_at': instance.mPosisiCreatedAt,
      'm_posisi.updated_at': instance.mPosisiUpdatedAt,
      'm_jam_kerja.id': instance.mJamKerjaId,
      'm_jam_kerja.m_comp_id': instance.mJamKerjaMCompId,
      'm_jam_kerja.m_dir_id': instance.mJamKerjaMDirId,
      'm_jam_kerja.kode': instance.mJamKerjaKode,
      'm_jam_kerja.tipe_jam_kerja_id': instance.mJamKerjaTipeJamKerjaId,
      'm_jam_kerja.waktu_mulai': instance.mJamKerjaWaktuMulai,
      'm_jam_kerja.waktu_akhir': instance.mJamKerjaWaktuAkhir,
      'm_jam_kerja.is_hari_berikutnya': instance.mJamKerjaIsHariBerikutnya,
      'm_jam_kerja.desc': instance.mJamKerjaDesc,
      'm_jam_kerja.is_active': instance.mJamKerjaIsActive,
      'm_jam_kerja.creator_id': instance.mJamKerjaCreatorId,
      'm_jam_kerja.last_editor_id': instance.mJamKerjaLastEditorId,
      'm_jam_kerja.created_at': instance.mJamKerjaCreatedAt,
      'm_jam_kerja.updated_at': instance.mJamKerjaUpdatedAt,
      'jk.id': instance.jkId,
      'jk.m_comp_id': instance.jkMCompId,
      'jk.m_dir_id': instance.jkMDirId,
      'jk.group': instance.jkGroup,
      'jk.key': instance.jkKey,
      'jk.code': instance.jkCode,
      'jk.value': instance.jkValue,
      'jk.is_active': instance.jkIsActive,
      'jk.creator_id': instance.jkCreatorId,
      'jk.last_editor_id': instance.jkLastEditorId,
      'jk.created_at': instance.jkCreatedAt,
      'jk.updated_at': instance.jkUpdatedAt,
      'jk.value_2': instance.jkValue2,
      'jk.value_3': instance.jkValue3,
      'provinsi.id': instance.provinsiId,
      'provinsi.m_comp_id': instance.provinsiMCompId,
      'provinsi.m_dir_id': instance.provinsiMDirId,
      'provinsi.group': instance.provinsiGroup,
      'provinsi.key': instance.provinsiKey,
      'provinsi.code': instance.provinsiCode,
      'provinsi.value': instance.provinsiValue,
      'provinsi.is_active': instance.provinsiIsActive,
      'provinsi.creator_id': instance.provinsiCreatorId,
      'provinsi.last_editor_id': instance.provinsiLastEditorId,
      'provinsi.created_at': instance.provinsiCreatedAt,
      'provinsi.updated_at': instance.provinsiUpdatedAt,
      'provinsi.value_2': instance.provinsiValue2,
      'provinsi.value_3': instance.provinsiValue3,
      'kota.id': instance.kotaId,
      'kota.m_comp_id': instance.kotaMCompId,
      'kota.m_dir_id': instance.kotaMDirId,
      'kota.group': instance.kotaGroup,
      'kota.key': instance.kotaKey,
      'kota.code': instance.kotaCode,
      'kota.value': instance.kotaValue,
      'kota.is_active': instance.kotaIsActive,
      'kota.creator_id': instance.kotaCreatorId,
      'kota.last_editor_id': instance.kotaLastEditorId,
      'kota.created_at': instance.kotaCreatedAt,
      'kota.updated_at': instance.kotaUpdatedAt,
      'kota.value_2': instance.kotaValue2,
      'kota.value_3': instance.kotaValue3,
      'kecamatan.id': instance.kecamatanId,
      'kecamatan.m_comp_id': instance.kecamatanMCompId,
      'kecamatan.m_dir_id': instance.kecamatanMDirId,
      'kecamatan.group': instance.kecamatanGroup,
      'kecamatan.key': instance.kecamatanKey,
      'kecamatan.code': instance.kecamatanCode,
      'kecamatan.value': instance.kecamatanValue,
      'kecamatan.is_active': instance.kecamatanIsActive,
      'kecamatan.creator_id': instance.kecamatanCreatorId,
      'kecamatan.last_editor_id': instance.kecamatanLastEditorId,
      'kecamatan.created_at': instance.kecamatanCreatedAt,
      'kecamatan.updated_at': instance.kecamatanUpdatedAt,
      'kecamatan.value_2': instance.kecamatanValue2,
      'kecamatan.value_3': instance.kecamatanValue3,
      'agama.id': instance.agamaId,
      'agama.m_comp_id': instance.agamaMCompId,
      'agama.m_dir_id': instance.agamaMDirId,
      'agama.group': instance.agamaGroup,
      'agama.key': instance.agamaKey,
      'agama.code': instance.agamaCode,
      'agama.value': instance.agamaValue,
      'agama.is_active': instance.agamaIsActive,
      'agama.creator_id': instance.agamaCreatorId,
      'agama.last_editor_id': instance.agamaLastEditorId,
      'agama.created_at': instance.agamaCreatedAt,
      'agama.updated_at': instance.agamaUpdatedAt,
      'agama.value_2': instance.agamaValue2,
      'agama.value_3': instance.agamaValue3,
      'gol_darah.id': instance.golDarahId,
      'gol_darah.m_comp_id': instance.golDarahMCompId,
      'gol_darah.m_dir_id': instance.golDarahMDirId,
      'gol_darah.group': instance.golDarahGroup,
      'gol_darah.key': instance.golDarahKey,
      'gol_darah.code': instance.golDarahCode,
      'gol_darah.value': instance.golDarahValue,
      'gol_darah.is_active': instance.golDarahIsActive,
      'gol_darah.creator_id': instance.golDarahCreatorId,
      'gol_darah.last_editor_id': instance.golDarahLastEditorId,
      'gol_darah.created_at': instance.golDarahCreatedAt,
      'gol_darah.updated_at': instance.golDarahUpdatedAt,
      'gol_darah.value_2': instance.golDarahValue2,
      'gol_darah.value_3': instance.golDarahValue3,
      'status_nikah.id': instance.statusNikahId,
      'status_nikah.m_comp_id': instance.statusNikahMCompId,
      'status_nikah.m_dir_id': instance.statusNikahMDirId,
      'status_nikah.group': instance.statusNikahGroup,
      'status_nikah.key': instance.statusNikahKey,
      'status_nikah.code': instance.statusNikahCode,
      'status_nikah.value': instance.statusNikahValue,
      'status_nikah.is_active': instance.statusNikahIsActive,
      'status_nikah.creator_id': instance.statusNikahCreatorId,
      'status_nikah.last_editor_id': instance.statusNikahLastEditorId,
      'status_nikah.created_at': instance.statusNikahCreatedAt,
      'status_nikah.updated_at': instance.statusNikahUpdatedAt,
      'status_nikah.value_2': instance.statusNikahValue2,
      'status_nikah.value_3': instance.statusNikahValue3,
      'tanggungan.id': instance.tanggunganId,
      'tanggungan.m_comp_id': instance.tanggunganMCompId,
      'tanggungan.m_dir_id': instance.tanggunganMDirId,
      'tanggungan.group': instance.tanggunganGroup,
      'tanggungan.key': instance.tanggunganKey,
      'tanggungan.code': instance.tanggunganCode,
      'tanggungan.value': instance.tanggunganValue,
      'tanggungan.is_active': instance.tanggunganIsActive,
      'tanggungan.creator_id': instance.tanggunganCreatorId,
      'tanggungan.last_editor_id': instance.tanggunganLastEditorId,
      'tanggungan.created_at': instance.tanggunganCreatedAt,
      'tanggungan.updated_at': instance.tanggunganUpdatedAt,
      'tanggungan.value_2': instance.tanggunganValue2,
      'tanggungan.value_3': instance.tanggunganValue3,
      'status_kary.id': instance.statusKaryId,
      'status_kary.m_comp_id': instance.statusKaryMCompId,
      'status_kary.m_dir_id': instance.statusKaryMDirId,
      'status_kary.group': instance.statusKaryGroup,
      'status_kary.key': instance.statusKaryKey,
      'status_kary.code': instance.statusKaryCode,
      'status_kary.value': instance.statusKaryValue,
      'status_kary.is_active': instance.statusKaryIsActive,
      'status_kary.creator_id': instance.statusKaryCreatorId,
      'status_kary.last_editor_id': instance.statusKaryLastEditorId,
      'status_kary.created_at': instance.statusKaryCreatedAt,
      'status_kary.updated_at': instance.statusKaryUpdatedAt,
      'status_kary.value_2': instance.statusKaryValue2,
      'status_kary.value_3': instance.statusKaryValue3,
      'creator.id': instance.creatorId,
      'creator.name': instance.creatorName,
      'creator.email': instance.creatorEmail,
      'creator.username': instance.creatorUsername,
      'creator.email_verified_at': instance.creatorEmailVerifiedAt,
      'creator.password': instance.creatorPassword,
      'creator.m_comp_id': instance.creatorMCompId,
      'creator.m_dir_id': instance.creatorMDirId,
      'creator.is_active': instance.creatorIsActive,
      'creator.creator_id': instance.creatorCreatorId,
      'creator.last_editor_id': instance.creatorLastEditorId,
      'creator.remember_token': instance.creatorRememberToken,
      'creator.created_at': instance.creatorCreatedAt,
      'creator.updated_at': instance.creatorUpdatedAt,
      'creator.profil_image': instance.creatorProfilImage,
      'creator.telp': instance.creatorTelp,
      'creator.m_kary_id': instance.creatorMKaryId,
      'last_editor.id': instance.lastEditorId,
      'last_editor.name': instance.lastEditorName,
      'last_editor.email': instance.lastEditorEmail,
      'last_editor.username': instance.lastEditorUsername,
      'last_editor.email_verified_at': instance.lastEditorEmailVerifiedAt,
      'last_editor.password': instance.lastEditorPassword,
      'last_editor.m_comp_id': instance.lastEditorMCompId,
      'last_editor.m_dir_id': instance.lastEditorMDirId,
      'last_editor.is_active': instance.lastEditorIsActive,
      'last_editor.creator_id': instance.lastEditorCreatorId,
      'last_editor.last_editor_id': instance.lastEditorLastEditorId,
      'last_editor.remember_token': instance.lastEditorRememberToken,
      'last_editor.created_at': instance.lastEditorCreatedAt,
      'last_editor.updated_at': instance.lastEditorUpdatedAt,
      'last_editor.profil_image': instance.lastEditorProfilImage,
      'last_editor.telp': instance.lastEditorTelp,
      'last_editor.m_kary_id': instance.lastEditorMKaryId,
      'm_standart_gaji.id': instance.mStandartGajiId,
      'm_standart_gaji.m_comp_id': instance.mStandartGajiMCompId,
      'm_standart_gaji.m_dir_id': instance.mStandartGajiMDirId,
      'm_standart_gaji.kode': instance.mStandartGajiKode,
      'm_standart_gaji.m_divisi_id': instance.mStandartGajiMDivisiId,
      'm_standart_gaji.m_dept_id': instance.mStandartGajiMDeptId,
      'm_standart_gaji.m_zona_id': instance.mStandartGajiMZonaId,
      'm_standart_gaji.m_posisi_id': instance.mStandartGajiMPosisiId,
      'm_standart_gaji.grading_id': instance.mStandartGajiGradingId,
      'm_standart_gaji.gaji_pokok': instance.mStandartGajiGajiPokok,
      'm_standart_gaji.gaji_pokok_periode':
          instance.mStandartGajiGajiPokokPeriode,
      'm_standart_gaji.uang_saku': instance.mStandartGajiUangSaku,
      'm_standart_gaji.uang_saku_periode':
          instance.mStandartGajiUangSakuPeriode,
      'm_standart_gaji.tunjangan_posisi': instance.mStandartGajiTunjanganPosisi,
      'm_standart_gaji.tunjangan_posisi_periode':
          instance.mStandartGajiTunjanganPosisiPeriode,
      'm_standart_gaji.tunjangan_kemahalan_id':
          instance.mStandartGajiTunjanganKemahalanId,
      'm_standart_gaji.tunjangan_kemahalan_periode':
          instance.mStandartGajiTunjanganKemahalanPeriode,
      'm_standart_gaji.uang_makan': instance.mStandartGajiUangMakan,
      'm_standart_gaji.uang_makan_periode':
          instance.mStandartGajiUangMakanPeriode,
      'm_standart_gaji.tunjangan_tetap': instance.mStandartGajiTunjanganTetap,
      'm_standart_gaji.tunjangan_tetap_periode':
          instance.mStandartGajiTunjanganTetapPeriode,
      'm_standart_gaji.desc': instance.mStandartGajiDesc,
      'm_standart_gaji.is_active': instance.mStandartGajiIsActive,
      'm_standart_gaji.creator_id': instance.mStandartGajiCreatorId,
      'm_standart_gaji.last_editor_id': instance.mStandartGajiLastEditorId,
      'm_standart_gaji.created_at': instance.mStandartGajiCreatedAt,
      'm_standart_gaji.updated_at': instance.mStandartGajiUpdatedAt,
      'periode_gaji.id': instance.periodeGajiId,
      'periode_gaji.m_comp_id': instance.periodeGajiMCompId,
      'periode_gaji.m_dir_id': instance.periodeGajiMDirId,
      'periode_gaji.group': instance.periodeGajiGroup,
      'periode_gaji.key': instance.periodeGajiKey,
      'periode_gaji.code': instance.periodeGajiCode,
      'periode_gaji.value': instance.periodeGajiValue,
      'periode_gaji.is_active': instance.periodeGajiIsActive,
      'periode_gaji.creator_id': instance.periodeGajiCreatorId,
      'periode_gaji.last_editor_id': instance.periodeGajiLastEditorId,
      'periode_gaji.created_at': instance.periodeGajiCreatedAt,
      'periode_gaji.updated_at': instance.periodeGajiUpdatedAt,
      'periode_gaji.value_2': instance.periodeGajiValue2,
      'periode_gaji.value_3': instance.periodeGajiValue3,
      'ref.id': instance.refId,
      'ref.nomor': instance.refNomor,
      'ref.m_comp_id': instance.refMCompId,
      'ref.m_dir_id': instance.refMDirId,
      'ref.nama_pelamar': instance.refNamaPelamar,
      'ref.ktp_no': instance.refKtpNo,
      'ref.tanggal': instance.refTanggal,
      'ref.ref': instance.refRef,
      'ref.telp': instance.refTelp,
      'ref.jk_id': instance.refJkId,
      'ref.tgl_lahir': instance.refTglLahir,
      'ref.salary': instance.refSalary,
      'ref.deskripsi': instance.refDeskripsi,
      'ref.status': instance.refStatus,
      'ref.creator_id': instance.refCreatorId,
      'ref.last_editor_id': instance.refLastEditorId,
      'ref.created_at': instance.refCreatedAt,
      'ref.updated_at': instance.refUpdatedAt,
      'ref.m_divisi_id': instance.refMDivisiId,
      'ref.m_dept_id': instance.refMDeptId,
      'ref.m_posisi_id': instance.refMPosisiId,
      'ref.tempat_lahir': instance.refTempatLahir,
      'ref.t_loker_id': instance.refTLokerId,
      'presensi_lokasi_default.id': instance.presensiLokasiDefaultId,
      'presensi_lokasi_default.comp_id': instance.presensiLokasiDefaultCompId,
      'presensi_lokasi_default.default_user_id':
          instance.presensiLokasiDefaultDefaultUserId,
      'presensi_lokasi_default.nama': instance.presensiLokasiDefaultNama,
      'presensi_lokasi_default.lat': instance.presensiLokasiDefaultLat,
      'presensi_lokasi_default.long': instance.presensiLokasiDefaultLong,
      'presensi_lokasi_default.is_active':
          instance.presensiLokasiDefaultIsActive,
      'presensi_lokasi_default.creator_id':
          instance.presensiLokasiDefaultCreatorId,
      'presensi_lokasi_default.last_editor_id':
          instance.presensiLokasiDefaultLastEditorId,
      'presensi_lokasi_default.created_at':
          instance.presensiLokasiDefaultCreatedAt,
      'presensi_lokasi_default.updated_at':
          instance.presensiLokasiDefaultUpdatedAt,
      'atasan.id': instance.atasanId,
      'atasan.m_comp_id': instance.atasanMCompId,
      'atasan.m_dir_id': instance.atasanMDirId,
      'atasan.m_divisi_id': instance.atasanMDivisiId,
      'atasan.m_dept_id': instance.atasanMDeptId,
      'atasan.m_zona_id': instance.atasanMZonaId,
      'atasan.grading_id': instance.atasanGradingId,
      'atasan.costcontre_id': instance.atasanCostcontreId,
      'atasan.kode': instance.atasanKode,
      'atasan.m_posisi_id': instance.atasanMPosisiId,
      'atasan.m_jam_kerja_id': instance.atasanMJamKerjaId,
      'atasan.kode_presensi': instance.atasanKodePresensi,
      'atasan.nik': instance.atasanNik,
      'atasan.nama_depan': instance.atasanNamaDepan,
      'atasan.nama_belakang': instance.atasanNamaBelakang,
      'atasan.nama_lengkap': instance.atasanNamaLengkap,
      'atasan.nama_panggilan': instance.atasanNamaPanggilan,
      'atasan.jk_id': instance.atasanJkId,
      'atasan.tempat_lahir': instance.atasanTempatLahir,
      'atasan.tgl_lahir': instance.atasanTglLahir,
      'atasan.provinsi_id': instance.atasanProvinsiId,
      'atasan.kota_id': instance.atasanKotaId,
      'atasan.kecamatan_id': instance.atasanKecamatanId,
      'atasan.kode_pos': instance.atasanKodePos,
      'atasan.alamat_asli': instance.atasanAlamatAsli,
      'atasan.alamat_domisili': instance.atasanAlamatDomisili,
      'atasan.no_tlp': instance.atasanNoTlp,
      'atasan.no_tlp_lainnya': instance.atasanNoTlpLainnya,
      'atasan.no_darurat': instance.atasanNoDarurat,
      'atasan.nama_kontak_darurat': instance.atasanNamaKontakDarurat,
      'atasan.agama_id': instance.atasanAgamaId,
      'atasan.gol_darah_id': instance.atasanGolDarahId,
      'atasan.status_nikah_id': instance.atasanStatusNikahId,
      'atasan.tanggungan_id': instance.atasanTanggunganId,
      'atasan.hub_dgn_karyawan': instance.atasanHubDgnKaryawan,
      'atasan.cuti_jatah_reguler': instance.atasanCutiJatahReguler,
      'atasan.cuti_sisa_reguler': instance.atasanCutiSisaReguler,
      'atasan.cuti_panjang': instance.atasanCutiPanjang,
      'atasan.cuti_sisa_panjang': instance.atasanCutiSisaPanjang,
      'atasan.status_kary_id': instance.atasanStatusKaryId,
      'atasan.lama_kontrak_awal': instance.atasanLamaKontrakAwal,
      'atasan.lama_kontrak_akhir': instance.atasanLamaKontrakAkhir,
      'atasan.tgl_masuk': instance.atasanTglMasuk,
      'atasan.tgl_berhenti': instance.atasanTglBerhenti,
      'atasan.alasan_berhenti': instance.atasanAlasanBerhenti,
      'atasan.uk_baju': instance.atasanUkBaju,
      'atasan.uk_celana': instance.atasanUkCelana,
      'atasan.uk_sepatu': instance.atasanUkSepatu,
      'atasan.desc': instance.atasanDesc,
      'atasan.is_active': instance.atasanIsActive,
      'atasan.creator_id': instance.atasanCreatorId,
      'atasan.last_editor_id': instance.atasanLastEditorId,
      'atasan.created_at': instance.atasanCreatedAt,
      'atasan.updated_at': instance.atasanUpdatedAt,
      'atasan.m_standart_gaji_id': instance.atasanMStandartGajiId,
      'atasan.periode_gaji_id': instance.atasanPeriodeGajiId,
      'atasan.ref_id': instance.atasanRefId,
      'atasan.presensi_lokasi_default_id':
          instance.atasanPresensiLokasiDefaultId,
      'atasan.exp_date_cuti': instance.atasanExpDateCuti,
      'atasan.limit_potong': instance.atasanLimitPotong,
      'atasan.atasan_id': instance.atasanAtasanId,
      'atasan.cuti_p24': instance.atasanCutiP24,
      'atasan.cuti_sisa_p24': instance.atasanCutiSisaP24,
      'atasan.tipe_jam_kerja_id': instance.atasanTipeJamKerjaId,
      'atasan.t_jadwal_kerja_id': instance.atasanTJadwalKerjaId,
      'tipe_jam_kerja.id': instance.tipeJamKerjaId,
      'tipe_jam_kerja.m_comp_id': instance.tipeJamKerjaMCompId,
      'tipe_jam_kerja.m_dir_id': instance.tipeJamKerjaMDirId,
      'tipe_jam_kerja.group': instance.tipeJamKerjaGroup,
      'tipe_jam_kerja.key': instance.tipeJamKerjaKey,
      'tipe_jam_kerja.code': instance.tipeJamKerjaCode,
      'tipe_jam_kerja.value': instance.tipeJamKerjaValue,
      'tipe_jam_kerja.is_active': instance.tipeJamKerjaIsActive,
      'tipe_jam_kerja.creator_id': instance.tipeJamKerjaCreatorId,
      'tipe_jam_kerja.last_editor_id': instance.tipeJamKerjaLastEditorId,
      'tipe_jam_kerja.created_at': instance.tipeJamKerjaCreatedAt,
      'tipe_jam_kerja.updated_at': instance.tipeJamKerjaUpdatedAt,
      'tipe_jam_kerja.value_2': instance.tipeJamKerjaValue2,
      'tipe_jam_kerja.value_3': instance.tipeJamKerjaValue3,
      't_jadwal_kerja.id': instance.tJadwalKerjaId,
      't_jadwal_kerja.nomor': instance.tJadwalKerjaNomor,
      't_jadwal_kerja.m_comp_id': instance.tJadwalKerjaMCompId,
      't_jadwal_kerja.m_dir_id': instance.tJadwalKerjaMDirId,
      't_jadwal_kerja.m_divisi_id': instance.tJadwalKerjaMDivisiId,
      't_jadwal_kerja.m_dept_id': instance.tJadwalKerjaMDeptId,
      't_jadwal_kerja.tipe_jam_kerja_id': instance.tJadwalKerjaTipeJamKerjaId,
      't_jadwal_kerja.keterangan': instance.tJadwalKerjaKeterangan,
      't_jadwal_kerja.status': instance.tJadwalKerjaStatus,
      't_jadwal_kerja.creator_id': instance.tJadwalKerjaCreatorId,
      't_jadwal_kerja.last_editor_id': instance.tJadwalKerjaLastEditorId,
      't_jadwal_kerja.created_at': instance.tJadwalKerjaCreatedAt,
      't_jadwal_kerja.updated_at': instance.tJadwalKerjaUpdatedAt,
      'nomor_ktp': instance.nomorKtp,
    };
